// Code generated by go-swagger; DO NOT EDIT.

// Package restapi TAF-K8S Admin
//
//  Tars Admin接口文档
//  Schemes:
//    http
//    ws
//  Host: tarsadmin.com
//  BasePath: /admin/v1alpha1/
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
