apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2e-framework
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: e2e-framework
rules:
  - apiGroups: [ k8s.tars.io ]
    resources: [ '*' ]
    verbs: [ '*' ]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: e2e-framework
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: e2e-framework
subjects:
  - kind: ServiceAccount
    name: e2e-framework
