/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta3

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1beta3 "k8s.tars.io/apis/tars/v1beta3"
	scheme "k8s.tars.io/client-go/clientset/versioned/scheme"
)

// TConfigsGetter has a method to return a TConfigInterface.
// A group's client should implement this interface.
type TConfigsGetter interface {
	TConfigs(namespace string) TConfigInterface
}

// TConfigInterface has methods to work with TConfig resources.
type TConfigInterface interface {
	Create(ctx context.Context, tConfig *v1beta3.TConfig, opts v1.CreateOptions) (*v1beta3.TConfig, error)
	Update(ctx context.Context, tConfig *v1beta3.TConfig, opts v1.UpdateOptions) (*v1beta3.TConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta3.TConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta3.TConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta3.TConfig, err error)
	TConfigExpansion
}

// tConfigs implements TConfigInterface
type tConfigs struct {
	client rest.Interface
	ns     string
}

// newTConfigs returns a TConfigs
func newTConfigs(c *TarsV1beta3Client, namespace string) *tConfigs {
	return &tConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the tConfig, and returns the corresponding tConfig object, and an error if there is any.
func (c *tConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta3.TConfig, err error) {
	result = &v1beta3.TConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TConfigs that match those selectors.
func (c *tConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1beta3.TConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta3.TConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tConfigs.
func (c *tConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("tconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a tConfig and creates it.  Returns the server's representation of the tConfig, and an error, if there is any.
func (c *tConfigs) Create(ctx context.Context, tConfig *v1beta3.TConfig, opts v1.CreateOptions) (result *v1beta3.TConfig, err error) {
	result = &v1beta3.TConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("tconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a tConfig and updates it. Returns the server's representation of the tConfig, and an error, if there is any.
func (c *tConfigs) Update(ctx context.Context, tConfig *v1beta3.TConfig, opts v1.UpdateOptions) (result *v1beta3.TConfig, err error) {
	result = &v1beta3.TConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tconfigs").
		Name(tConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the tConfig and deletes it. Returns an error if one occurs.
func (c *tConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched tConfig.
func (c *tConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta3.TConfig, err error) {
	result = &v1beta3.TConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("tconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
