apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tconfigs.k8s.tars.io
spec:
  conversion:
    strategy: None
  group: k8s.tars.io
  names:
    kind: TConfig
    listKind: TConfigList
    plural: tconfigs
    shortNames:
      - tc
    singular: tconfig
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          oneOf:
            - required:
                - appConfig
            - required:
                - serverConfig
          properties:
            appConfig:
              properties:
                app:
                  pattern: ^[a-zA-Z][a-zA-Z0-9]{0,23}$
                  type: string
                configName:
                  type: string
                  pattern: ^[a-zA-Z][a-zA-Z0-9_.-]{0,48}$
                configContent:
                  type: string
                  maxLength: 819200
                updatePerson:
                  type: string
                  pattern: ^[a-zA-Z][a-zA-Z0-9_.-]{0,15}$
                updateReason:
                  type: string
                  maxLength: 300
                updateTime:
                  type: string
                  format: date-time
              required:
                - app
                - configName
                - configContent
                - updateTime
                - updatePerson
                - updateReason
              type: object
            serverConfig:
              properties:
                app:
                  type: string
                  pattern: ^[a-zA-Z][a-zA-Z0-9]{0,23}$
                server:
                  type: string
                  pattern: ^[a-zA-Z][a-zA-Z0-9]{1,35}$
                configName:
                  type: string
                  pattern: ^[a-zA-Z][a-zA-Z0-9_.-]{0,48}$
                configContent:
                  type: string
                  maxLength: 819200
                podSeq:
                  type: string
                  pattern: ^[1-9]$|[1-3][0-9]$
                updatePerson:
                  type: string
                  pattern: ^[a-zA-Z][a-zA-Z0-9_.-]{0,15}$
                updateReason:
                  type: string
                  maxLength: 300
                updateTime:
                  type: string
                  format: date-time
              required:
                - app
                - server
                - configName
                - configContent
                - updateTime
                - updatePerson
                - updateReason
              type: object
          type: object
      served: true
      storage: true