apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: treleases.k8s.tars.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: k8s.tars.io
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                list:
                  type: array
                  items:
                    type: object
                    properties:
                      tag:
                        type: string
                        pattern: ^[1-9][0-9]{4,5}$
                      image:
                        type: string
                        pattern: ^([a-zA-Z0-9.:-]{1,128}\/){0,5}[a-zA-Z0-9.-]{1,128}:[a-zA-Z0-9.]{1,32}$
                      imagePullSecret:
                        type: string
                        pattern: ^([a-zA-Z][a-zA-Z0-9-.]{1,50}){0,1}$
                      remark:
                        type: string
                      createPerson:
                        type: string
                      createTime:
                        type: string
                      serverType:
                        type: string
                        enum: [ tars_cpp, tars_java_war, tars_java_jar, tars_nodejs, not_tars ]
                    required: [ image,tag,imagePullSecret ]
              required: [ list ]
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: treleases
    # singular name to be used as an alias on the CLI and for display
    singular: trelease
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: TRelease
    shortNames:
      - tr