apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  finalizers:
  - finalizers.tservers.k8s.tars.io
  name: tservers.k8s.tars.io
spec:
  conversion:
    strategy: None
  group: k8s.tars.io
  names:
    kind: TServer
    listKind: TServerList
    plural: tservers
    shortNames:
    - ts
    singular: tserver
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            oneOf:
            - required:
              - tars
              - k8s
            - required:
              - normal
              - k8s
            properties:
              app:
                pattern: ^[a-zA-Z][a-zA-Z0-9]{0,23}$
                type: string
              important:
                default: 3
                maximum: 20
                minimum: 1
                type: integer
              k8s:
                properties:
                  env:
                    items:
                      oneOf:
                      - required:
                        - value
                      - required:
                        - valueFrom
                      properties:
                        name:
                          pattern: ^[a-zA-Z][a-zA-Z0-9-_]{1,47}$
                          type: string
                        value:
                          pattern: ^[$a-zA-Z0-9{}/:]{0,180}$
                          required:
                          - value
                          type: string
                        valueFrom:
                          oneOf:
                          - required:
                            - fieldRef
                          - required:
                            - resourceFieldRef
                          - required:
                            - configMapKeyRef
                          - required:
                            - secretKeyRef
                          properties:
                            configMapKeyRef:
                              properties:
                                key:
                                  pattern: ^[a-zA-Z][a-zA-Z0-9-]{1,47}$
                                  type: string
                                name:
                                  pattern: ^[a-zA-Z][a-zA-Z0-9-]{1,47}$
                                  type: string
                                optional:
                                  type: boolean
                              required:
                              - name
                              - key
                              type: object
                            fieldRef:
                              properties:
                                apiVersion:
                                  type: string
                                fieldPath:
                                  type: string
                              type: object
                            resourceFieldRef:
                              properties:
                                containerName:
                                  type: string
                                divisor:
                                  x-kubernetes-int-or-string: true
                                resource:
                                  type: string
                              type: object
                            secretKeyRef:
                              properties:
                                key:
                                  pattern: ^[a-zA-Z][a-zA-Z0-9-]{1,47}$h
                                  type: string
                                name:
                                  pattern: ^[a-zA-Z][a-zA-Z0-9-]{1,47}$
                                  type: string
                                optional:
                                  type: boolean
                              required:
                              - name
                              - key
                              type: object
                          type: object
                      required:
                      - name
                      type: object
                    type: array
                  envFrom:
                    items:
                      oneOf:
                      - required:
                        - configMapRef
                      - required:
                        - secretRef
                      properties:
                        configMapRef:
                          properties:
                            name:
                              pattern: ^[a-zA-Z][a-zA-Z0-9-]{1,47}$
                              type: string
                            optional:
                              type: boolean
                          required:
                          - name
                          type: object
                        prefix:
                          type: string
                        secretRef:
                          properties:
                            name:
                              pattern: ^[a-zA-Z][a-zA-Z0-9-]{1,47}$
                              type: string
                            optional:
                              type: boolean
                          required:
                          - name
                          type: object
                      type: object
                    type: array
                  hostNetwork:
                    default: false
                    type: boolean
                  hostIPC:
                    default: false
                    type: boolean
                  hostPorts:
                    items:
                      properties:
                        nameRef:
                          pattern: ^[a-zA-Z0-9]{1,45}Obj$
                          type: string
                        port:
                          maximum: 65535
                          minimum: 1
                          type: integer
                      required:
                      - nameRef
                      - port
                      type: object
                    type: array
                  mounts:
                    items:
                      properties:
                        mountPath:
                          type: string
                        mountPropagation:
                          enum:
                          - None
                          - MountPropagationHostToContainer
                          - MountPropagationBidirectional
                          type: string
                        name:
                          pattern: ^[a-zA-Z][a-zA-Z0-9-]{1,47}$
                          type: string
                        readOnly:
                          type: boolean
                        source:
                          oneOf:
                          - required:
                            - hostPath
                          - required:
                            - emptyDir
                          - required:
                            - configMap
                          - required:
                            - secret
                          - required:
                            - persistentVolumeClaim
                          - required:
                            - downwardAPI
                          properties:
                            configMap:
                              properties:
                                items:
                                  items:
                                    properties:
                                      fsType:
                                        type: string
                                      key:
                                        type: string
                                      path:
                                        type: string
                                    type: object
                                  required:
                                  - key
                                  - path
                                  type: array
                                name:
                                  type: string
                              type: object
                            emptyDir:
                              properties:
                                medium:
                                  enum:
                                  - ""
                                  - Memory
                                  - HugePages
                                  type: string
                                sizeLimit:
                                  type: integer
                              type: object
                            hostPath:
                              properties:
                                path:
                                  type: string
                                type:
                                  enum:
                                  - ""
                                  - DirectoryOrCreate
                                  - Directory
                                  - FileOrCreate
                                  - File
                                  - Socket
                                  - CharDevice
                                  - BlockDevice
                                  type: string
                              required:
                              - path
                              type: object
                            persistentVolumeClaim:
                              properties:
                                claimName:
                                  type: string
                                readOnly:
                                  type: boolean
                              type: object
                            secret:
                              properties:
                                defaultMode:
                                  type: integer
                                items:
                                  items:
                                    properties:
                                      fsType:
                                        type: string
                                      key:
                                        type: string
                                      path:
                                        type: string
                                    type: object
                                  minItems: 1
                                  required:
                                  - key
                                  - path
                                  type: array
                                name:
                                  type: string
                                optional:
                                  type: boolean
                              required:
                              - name
                              type: object
                          type: object
                        subPath:
                          type: string
                        subPathExpr:
                          type: string
                      type: object
                    type: array
                  nodeSelector:
                    oneOf:
                    - required:
                      - nodeBind
                    - required:
                      - publicPool
                    - required:
                      - abilityPool
                    - required:
                      - daemonSet
                    properties:
                      abilityPool:
                        properties:
                          values:
                            items:
                              type: string
                            maxItems: 0
                            type: array
                        type: object
                      nodeBind:
                        properties:
                          values:
                            items:
                              type: string
                            minItems: 1
                            type: array
                        required:
                        - values
                        type: object
                      publicPool:
                        properties:
                          values:
                            items:
                              type: string
                            maxItems: 0
                            type: array
                        type: object
                      daemonSet:
                        properties:
                          values:
                            items:
                              type: string
                            maxItems: 0
                            type: array
                        type: object
                    type: object
                  notStacked:
                    default: false
                    type: boolean
                  podManagementPolicy:
                    default: Parallel
                    enum:
                    - OrderedReady
                    - Parallel
                    type: string
                  readinessGate:
                    enum:
                    - ""
                    - tars.io/active
                    type: string
                  replicas:
                    maximum: 12
                    minimum: 0
                    type: integer
                  serviceAccount:
                    pattern: ^[a-zA-Z][a-zA-Z0-9-]{1,47}$
                    type: string
                required:
                - replicas
                - nodeSelector
                type: object
              normal:
                properties:
                  ports:
                    items:
                      properties:
                        isTcp:
                          default: true
                          type: boolean
                        name:
                          pattern: ^[a-zA-Z][a-zA-Z0-9-]{0,44}$
                          type: string
                        port:
                          maximum: 65535
                          minimum: 1
                          type: integer
                      required:
                      - name
                      - port
                      type: object
                    minItems: 1
                    type: array
                required:
                - ports
                type: object
              release:
                properties:
                  image:
                    pattern: ^([a-zA-Z0-9.:-]{1,}\/){0,}[a-zA-Z0-9.-]{1,120}:[a-zA-Z0-9.]{1,32}$
                    type: string
                  imagePullSecret:
                    pattern: ^([a-zA-Z][a-zA-Z0-9-.]{1,50}){0,1}$
                    type: string
                  serverType:
                    enum:
                    - ""
                    - tars_cpp
                    - tars_java_war
                    - tars_java_jar
                    - tars_node
                    - tars_node8
                    - tars_node10
                    - tars_node_pkg
                    - not_tars
                    type: string
                  source:
                    pattern: ^[a-zA-Z][a-zA-Z0-9-_]{1,47}$
                    type: string
                  tag:
                    pattern: ^[1-9][0-9]{4,5}$
                    type: string
                required:
                - source
                - tag
                - image
                - imagePullSecret
                type: object
              server:
                pattern: ^[a-zA-Z][a-zA-Z0-9]{1,35}$
                type: string
              subType:
                enum:
                - tars
                - normal
                type: string
              tars:
                properties:
                  asyncThread:
                    default: 3
                    maximum: 5
                    minimum: 1
                    type: integer
                  foreground:
                    default: false
                    type: boolean
                  profile:
                    type: string
                  servants:
                    items:
                      properties:
                        name:
                          pattern: ^[a-zA-Z][a-zA-Z0-9]{0,44}Obj$
                          type: string
                        port:
                          maximum: 65535
                          minimum: 1
                          type: integer
                        thread:
                          default: 3
                          maximum: 16
                          minimum: 1
                          type: integer
                        capacity:
                          default: 10000
                          maximum: 3000000
                          minimum: 1
                          type: integer
                        connection:
                          default: 10000
                          maximum: 3000000
                          minimum: 1
                          type: integer
                        isTars:
                          default: true
                          type: boolean
                        isTcp:
                          default: true
                          type: boolean
                        timeout:
                          default: 60000
                          maximum: 6000000
                          minimum: 0
                          type: integer
                      required:
                      - name
                      - port
                      type: object
                    minItems: 1
                    type: array
                  template:
                    pattern: ^[a-zA-Z][a-zA-Z0-9-.]{1,35}$
                    type: string
                type: object
            required:
            - app
            - server
            - subType
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
