//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TAccount) DeepCopyInto(out *TAccount) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TAccount.
func (in *TAccount) DeepCopy() *TAccount {
	if in == nil {
		return nil
	}
	out := new(TAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TAccount) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TAccountAuthentication) DeepCopyInto(out *TAccountAuthentication) {
	*out = *in
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(string)
		**out = **in
	}
	if in.BCryptPassword != nil {
		in, out := &in.BCryptPassword, &out.BCryptPassword
		*out = new(string)
		**out = **in
	}
	if in.Tokens != nil {
		in, out := &in.Tokens, &out.Tokens
		*out = make([]*TAccountAuthenticationToken, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TAccountAuthenticationToken)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TAccountAuthentication.
func (in *TAccountAuthentication) DeepCopy() *TAccountAuthentication {
	if in == nil {
		return nil
	}
	out := new(TAccountAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TAccountAuthenticationToken) DeepCopyInto(out *TAccountAuthenticationToken) {
	*out = *in
	in.UpdateTime.DeepCopyInto(&out.UpdateTime)
	in.ExpirationTime.DeepCopyInto(&out.ExpirationTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TAccountAuthenticationToken.
func (in *TAccountAuthenticationToken) DeepCopy() *TAccountAuthenticationToken {
	if in == nil {
		return nil
	}
	out := new(TAccountAuthenticationToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TAccountAuthorization) DeepCopyInto(out *TAccountAuthorization) {
	*out = *in
	in.UpdateTime.DeepCopyInto(&out.UpdateTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TAccountAuthorization.
func (in *TAccountAuthorization) DeepCopy() *TAccountAuthorization {
	if in == nil {
		return nil
	}
	out := new(TAccountAuthorization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TAccountList) DeepCopyInto(out *TAccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TAccountList.
func (in *TAccountList) DeepCopy() *TAccountList {
	if in == nil {
		return nil
	}
	out := new(TAccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TAccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TAccountRoleElem) DeepCopyInto(out *TAccountRoleElem) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TAccountRoleElem.
func (in *TAccountRoleElem) DeepCopy() *TAccountRoleElem {
	if in == nil {
		return nil
	}
	out := new(TAccountRoleElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TAccountSpec) DeepCopyInto(out *TAccountSpec) {
	*out = *in
	if in.Extra != nil {
		in, out := &in.Extra, &out.Extra
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Authentication.DeepCopyInto(&out.Authentication)
	if in.Authorization != nil {
		in, out := &in.Authorization, &out.Authorization
		*out = make([]*TAccountAuthorization, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TAccountAuthorization)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TAccountSpec.
func (in *TAccountSpec) DeepCopy() *TAccountSpec {
	if in == nil {
		return nil
	}
	out := new(TAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TConfig) DeepCopyInto(out *TConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.UpdateTime.DeepCopyInto(&out.UpdateTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TConfig.
func (in *TConfig) DeepCopy() *TConfig {
	if in == nil {
		return nil
	}
	out := new(TConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TConfigList) DeepCopyInto(out *TConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TConfigList.
func (in *TConfigList) DeepCopy() *TConfigList {
	if in == nil {
		return nil
	}
	out := new(TConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TEndpoint) DeepCopyInto(out *TEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TEndpoint.
func (in *TEndpoint) DeepCopy() *TEndpoint {
	if in == nil {
		return nil
	}
	out := new(TEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TEndpointList) DeepCopyInto(out *TEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TEndpointList.
func (in *TEndpointList) DeepCopy() *TEndpointList {
	if in == nil {
		return nil
	}
	out := new(TEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TEndpointPodStatus) DeepCopyInto(out *TEndpointPodStatus) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	if in.ContainerStatuses != nil {
		in, out := &in.ContainerStatuses, &out.ContainerStatuses
		*out = make([]v1.ContainerStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TEndpointPodStatus.
func (in *TEndpointPodStatus) DeepCopy() *TEndpointPodStatus {
	if in == nil {
		return nil
	}
	out := new(TEndpointPodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TEndpointSpec) DeepCopyInto(out *TEndpointSpec) {
	*out = *in
	if in.Tars != nil {
		in, out := &in.Tars, &out.Tars
		*out = new(TServerTars)
		(*in).DeepCopyInto(*out)
	}
	if in.Normal != nil {
		in, out := &in.Normal, &out.Normal
		*out = new(TServerNormal)
		(*in).DeepCopyInto(*out)
	}
	if in.HostPorts != nil {
		in, out := &in.HostPorts, &out.HostPorts
		*out = make([]*TK8SHostPort, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TK8SHostPort)
				**out = **in
			}
		}
	}
	if in.Release != nil {
		in, out := &in.Release, &out.Release
		*out = new(TServerRelease)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TEndpointSpec.
func (in *TEndpointSpec) DeepCopy() *TEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(TEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TEndpointStatus) DeepCopyInto(out *TEndpointStatus) {
	*out = *in
	if in.PodStatus != nil {
		in, out := &in.PodStatus, &out.PodStatus
		*out = make([]*TEndpointPodStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TEndpointPodStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TEndpointStatus.
func (in *TEndpointStatus) DeepCopy() *TEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(TEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TExitedPod) DeepCopyInto(out *TExitedPod) {
	*out = *in
	in.CreateTime.DeepCopyInto(&out.CreateTime)
	in.DeleteTime.DeepCopyInto(&out.DeleteTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TExitedPod.
func (in *TExitedPod) DeepCopy() *TExitedPod {
	if in == nil {
		return nil
	}
	out := new(TExitedPod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TExitedRecord) DeepCopyInto(out *TExitedRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = make([]TExitedPod, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TExitedRecord.
func (in *TExitedRecord) DeepCopy() *TExitedRecord {
	if in == nil {
		return nil
	}
	out := new(TExitedRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TExitedRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TExitedRecordList) DeepCopyInto(out *TExitedRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TExitedRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TExitedRecordList.
func (in *TExitedRecordList) DeepCopy() *TExitedRecordList {
	if in == nil {
		return nil
	}
	out := new(TExitedRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TExitedRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TImage) DeepCopyInto(out *TImage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.SupportedType != nil {
		in, out := &in.SupportedType, &out.SupportedType
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Releases != nil {
		in, out := &in.Releases, &out.Releases
		*out = make([]*TImageRelease, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TImageRelease)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Build != nil {
		in, out := &in.Build, &out.Build
		*out = new(TImageBuild)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TImage.
func (in *TImage) DeepCopy() *TImage {
	if in == nil {
		return nil
	}
	out := new(TImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TImage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TImageBuild) DeepCopyInto(out *TImageBuild) {
	*out = *in
	if in.Last != nil {
		in, out := &in.Last, &out.Last
		*out = new(TImageBuildState)
		(*in).DeepCopyInto(*out)
	}
	if in.Running != nil {
		in, out := &in.Running, &out.Running
		*out = new(TImageBuildState)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TImageBuild.
func (in *TImageBuild) DeepCopy() *TImageBuild {
	if in == nil {
		return nil
	}
	out := new(TImageBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TImageBuildState) DeepCopyInto(out *TImageBuildState) {
	*out = *in
	in.CreateTime.DeepCopyInto(&out.CreateTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TImageBuildState.
func (in *TImageBuildState) DeepCopy() *TImageBuildState {
	if in == nil {
		return nil
	}
	out := new(TImageBuildState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TImageList) DeepCopyInto(out *TImageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TImageList.
func (in *TImageList) DeepCopy() *TImageList {
	if in == nil {
		return nil
	}
	out := new(TImageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TImageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TImageRelease) DeepCopyInto(out *TImageRelease) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(string)
		**out = **in
	}
	if in.CreatePerson != nil {
		in, out := &in.CreatePerson, &out.CreatePerson
		*out = new(string)
		**out = **in
	}
	in.CreateTime.DeepCopyInto(&out.CreateTime)
	if in.Mark != nil {
		in, out := &in.Mark, &out.Mark
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TImageRelease.
func (in *TImageRelease) DeepCopy() *TImageRelease {
	if in == nil {
		return nil
	}
	out := new(TImageRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TK8SHostPort) DeepCopyInto(out *TK8SHostPort) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TK8SHostPort.
func (in *TK8SHostPort) DeepCopy() *TK8SHostPort {
	if in == nil {
		return nil
	}
	out := new(TK8SHostPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TK8SMount) DeepCopyInto(out *TK8SMount) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.MountPropagation != nil {
		in, out := &in.MountPropagation, &out.MountPropagation
		*out = new(v1.MountPropagationMode)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TK8SMount.
func (in *TK8SMount) DeepCopy() *TK8SMount {
	if in == nil {
		return nil
	}
	out := new(TK8SMount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TK8SMountSource) DeepCopyInto(out *TK8SMountSource) {
	*out = *in
	if in.HostPath != nil {
		in, out := &in.HostPath, &out.HostPath
		*out = new(v1.HostPathVolumeSource)
		(*in).DeepCopyInto(*out)
	}
	if in.EmptyDir != nil {
		in, out := &in.EmptyDir, &out.EmptyDir
		*out = new(v1.EmptyDirVolumeSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(v1.SecretVolumeSource)
		(*in).DeepCopyInto(*out)
	}
	if in.PersistentVolumeClaim != nil {
		in, out := &in.PersistentVolumeClaim, &out.PersistentVolumeClaim
		*out = new(v1.PersistentVolumeClaimVolumeSource)
		**out = **in
	}
	if in.PersistentVolumeClaimTemplate != nil {
		in, out := &in.PersistentVolumeClaimTemplate, &out.PersistentVolumeClaimTemplate
		*out = new(v1.PersistentVolumeClaim)
		(*in).DeepCopyInto(*out)
	}
	if in.TLocalVolume != nil {
		in, out := &in.TLocalVolume, &out.TLocalVolume
		*out = new(TLocalVolume)
		**out = **in
	}
	if in.DownwardAPI != nil {
		in, out := &in.DownwardAPI, &out.DownwardAPI
		*out = new(v1.DownwardAPIVolumeSource)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(v1.ConfigMapVolumeSource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TK8SMountSource.
func (in *TK8SMountSource) DeepCopy() *TK8SMountSource {
	if in == nil {
		return nil
	}
	out := new(TK8SMountSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLocalVolume) DeepCopyInto(out *TLocalVolume) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLocalVolume.
func (in *TLocalVolume) DeepCopy() *TLocalVolume {
	if in == nil {
		return nil
	}
	out := new(TLocalVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServer) DeepCopyInto(out *TServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServer.
func (in *TServer) DeepCopy() *TServer {
	if in == nil {
		return nil
	}
	out := new(TServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerExternal) DeepCopyInto(out *TServerExternal) {
	*out = *in
	if in.Upstreams != nil {
		in, out := &in.Upstreams, &out.Upstreams
		*out = make([]TServerExternalUPStream, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerExternal.
func (in *TServerExternal) DeepCopy() *TServerExternal {
	if in == nil {
		return nil
	}
	out := new(TServerExternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerExternalAddress) DeepCopyInto(out *TServerExternalAddress) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerExternalAddress.
func (in *TServerExternalAddress) DeepCopy() *TServerExternalAddress {
	if in == nil {
		return nil
	}
	out := new(TServerExternalAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerExternalUPStream) DeepCopyInto(out *TServerExternalUPStream) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]TServerExternalAddress, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerExternalUPStream.
func (in *TServerExternalUPStream) DeepCopy() *TServerExternalUPStream {
	if in == nil {
		return nil
	}
	out := new(TServerExternalUPStream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerK8S) DeepCopyInto(out *TServerK8S) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]v1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HostPorts != nil {
		in, out := &in.HostPorts, &out.HostPorts
		*out = make([]*TK8SHostPort, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TK8SHostPort)
				**out = **in
			}
		}
	}
	if in.Mounts != nil {
		in, out := &in.Mounts, &out.Mounts
		*out = make([]TK8SMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make([]v1.NodeSelectorRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerK8S.
func (in *TServerK8S) DeepCopy() *TServerK8S {
	if in == nil {
		return nil
	}
	out := new(TServerK8S)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerList) DeepCopyInto(out *TServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerList.
func (in *TServerList) DeepCopy() *TServerList {
	if in == nil {
		return nil
	}
	out := new(TServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerNormal) DeepCopyInto(out *TServerNormal) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]*TServerPort, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TServerPort)
				**out = **in
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerNormal.
func (in *TServerNormal) DeepCopy() *TServerNormal {
	if in == nil {
		return nil
	}
	out := new(TServerNormal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerPort) DeepCopyInto(out *TServerPort) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerPort.
func (in *TServerPort) DeepCopy() *TServerPort {
	if in == nil {
		return nil
	}
	out := new(TServerPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerRelease) DeepCopyInto(out *TServerRelease) {
	*out = *in
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerRelease.
func (in *TServerRelease) DeepCopy() *TServerRelease {
	if in == nil {
		return nil
	}
	out := new(TServerRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerServant) DeepCopyInto(out *TServerServant) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerServant.
func (in *TServerServant) DeepCopy() *TServerServant {
	if in == nil {
		return nil
	}
	out := new(TServerServant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerSpec) DeepCopyInto(out *TServerSpec) {
	*out = *in
	if in.Tars != nil {
		in, out := &in.Tars, &out.Tars
		*out = new(TServerTars)
		(*in).DeepCopyInto(*out)
	}
	if in.Normal != nil {
		in, out := &in.Normal, &out.Normal
		*out = new(TServerNormal)
		(*in).DeepCopyInto(*out)
	}
	in.K8S.DeepCopyInto(&out.K8S)
	if in.Release != nil {
		in, out := &in.Release, &out.Release
		*out = new(TServerRelease)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerSpec.
func (in *TServerSpec) DeepCopy() *TServerSpec {
	if in == nil {
		return nil
	}
	out := new(TServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerStatus) DeepCopyInto(out *TServerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerStatus.
func (in *TServerStatus) DeepCopy() *TServerStatus {
	if in == nil {
		return nil
	}
	out := new(TServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerTars) DeepCopyInto(out *TServerTars) {
	*out = *in
	if in.Servants != nil {
		in, out := &in.Servants, &out.Servants
		*out = make([]*TServerServant, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TServerServant)
				**out = **in
			}
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]*TServerPort, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TServerPort)
				**out = **in
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerTars.
func (in *TServerTars) DeepCopy() *TServerTars {
	if in == nil {
		return nil
	}
	out := new(TServerTars)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TTemplate) DeepCopyInto(out *TTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TTemplate.
func (in *TTemplate) DeepCopy() *TTemplate {
	if in == nil {
		return nil
	}
	out := new(TTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TTemplateList) DeepCopyInto(out *TTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TTemplateList.
func (in *TTemplateList) DeepCopy() *TTemplateList {
	if in == nil {
		return nil
	}
	out := new(TTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TTemplateSpec) DeepCopyInto(out *TTemplateSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TTemplateSpec.
func (in *TTemplateSpec) DeepCopy() *TTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(TTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TTree) DeepCopyInto(out *TTree) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Businesses != nil {
		in, out := &in.Businesses, &out.Businesses
		*out = make([]TTreeBusiness, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Apps != nil {
		in, out := &in.Apps, &out.Apps
		*out = make([]TTreeApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TTree.
func (in *TTree) DeepCopy() *TTree {
	if in == nil {
		return nil
	}
	out := new(TTree)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TTree) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TTreeApp) DeepCopyInto(out *TTreeApp) {
	*out = *in
	in.CreateTime.DeepCopyInto(&out.CreateTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TTreeApp.
func (in *TTreeApp) DeepCopy() *TTreeApp {
	if in == nil {
		return nil
	}
	out := new(TTreeApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TTreeBusiness) DeepCopyInto(out *TTreeBusiness) {
	*out = *in
	in.CreateTime.DeepCopyInto(&out.CreateTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TTreeBusiness.
func (in *TTreeBusiness) DeepCopy() *TTreeBusiness {
	if in == nil {
		return nil
	}
	out := new(TTreeBusiness)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TTreeList) DeepCopyInto(out *TTreeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TTree, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TTreeList.
func (in *TTreeList) DeepCopy() *TTreeList {
	if in == nil {
		return nil
	}
	out := new(TTreeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TTreeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
