// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateTemplateHandlerFunc turns a function with the right signature into a create template handler
type CreateTemplateHandlerFunc func(CreateTemplateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateTemplateHandlerFunc) Handle(params CreateTemplateParams) middleware.Responder {
	return fn(params)
}

// CreateTemplateHandler interface for that can handle valid create template params
type CreateTemplateHandler interface {
	Handle(CreateTemplateParams) middleware.Responder
}

// NewCreateTemplate creates a new http.Handler for the create template operation
func NewCreateTemplate(ctx *middleware.Context, handler CreateTemplateHandler) *CreateTemplate {
	return &CreateTemplate{Context: ctx, Handler: handler}
}

/*CreateTemplate swagger:route POST /templates template k8s createTemplate

创建服务模板，web=/template_create

*/
type CreateTemplate struct {
	Context *middleware.Context
	Handler CreateTemplateHandler
}

func (o *CreateTemplate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateTemplateParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CreateTemplateBody create template body
//
// swagger:model CreateTemplateBody
type CreateTemplateBody struct {

	// metadata
	Metadata *CreateTemplateParamsBodyMetadata `json:"metadata,omitempty"`
}

// Validate validates this create template body
func (o *CreateTemplateBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateTemplateBody) validateMetadata(formats strfmt.Registry) error {

	if swag.IsZero(o.Metadata) { // not required
		return nil
	}

	if o.Metadata != nil {
		if err := o.Metadata.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Params" + "." + "metadata")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateTemplateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateTemplateBody) UnmarshalBinary(b []byte) error {
	var res CreateTemplateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// CreateTemplateOKBody create template o k body
//
// swagger:model CreateTemplateOKBody
type CreateTemplateOKBody struct {

	// result
	Result int32 `json:"result,omitempty"`
}

// Validate validates this create template o k body
func (o *CreateTemplateOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateTemplateOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateTemplateOKBody) UnmarshalBinary(b []byte) error {
	var res CreateTemplateOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// CreateTemplateParamsBodyMetadata create template params body metadata
//
// swagger:model CreateTemplateParamsBodyMetadata
type CreateTemplateParamsBodyMetadata struct {

	// template content
	// Required: true
	TemplateContent *string `json:"TemplateContent"`

	// template name
	// Required: true
	TemplateName *string `json:"TemplateName"`

	// template parent
	// Required: true
	TemplateParent *string `json:"TemplateParent"`
}

// Validate validates this create template params body metadata
func (o *CreateTemplateParamsBodyMetadata) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateTemplateContent(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTemplateName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTemplateParent(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateTemplateParamsBodyMetadata) validateTemplateContent(formats strfmt.Registry) error {

	if err := validate.Required("Params"+"."+"metadata"+"."+"TemplateContent", "body", o.TemplateContent); err != nil {
		return err
	}

	return nil
}

func (o *CreateTemplateParamsBodyMetadata) validateTemplateName(formats strfmt.Registry) error {

	if err := validate.Required("Params"+"."+"metadata"+"."+"TemplateName", "body", o.TemplateName); err != nil {
		return err
	}

	return nil
}

func (o *CreateTemplateParamsBodyMetadata) validateTemplateParent(formats strfmt.Registry) error {

	if err := validate.Required("Params"+"."+"metadata"+"."+"TemplateParent", "body", o.TemplateParent); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateTemplateParamsBodyMetadata) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateTemplateParamsBodyMetadata) UnmarshalBinary(b []byte) error {
	var res CreateTemplateParamsBodyMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
