// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"tarsadmin/openapi/models"
)

// DeleteTemplateOKCode is the HTTP code returned for type DeleteTemplateOK
const DeleteTemplateOKCode int = 200

/*DeleteTemplateOK OK

swagger:response deleteTemplateOK
*/
type DeleteTemplateOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteTemplateOKBody `json:"body,omitempty"`
}

// NewDeleteTemplateOK creates DeleteTemplateOK with default headers values
func NewDeleteTemplateOK() *DeleteTemplateOK {

	return &DeleteTemplateOK{}
}

// WithPayload adds the payload to the delete template o k response
func (o *DeleteTemplateOK) WithPayload(payload *DeleteTemplateOKBody) *DeleteTemplateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete template o k response
func (o *DeleteTemplateOK) SetPayload(payload *DeleteTemplateOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTemplateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteTemplateInternalServerErrorCode is the HTTP code returned for type DeleteTemplateInternalServerError
const DeleteTemplateInternalServerErrorCode int = 500

/*DeleteTemplateInternalServerError 内部错误

swagger:response deleteTemplateInternalServerError
*/
type DeleteTemplateInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteTemplateInternalServerError creates DeleteTemplateInternalServerError with default headers values
func NewDeleteTemplateInternalServerError() *DeleteTemplateInternalServerError {

	return &DeleteTemplateInternalServerError{}
}

// WithPayload adds the payload to the delete template internal server error response
func (o *DeleteTemplateInternalServerError) WithPayload(payload *models.Error) *DeleteTemplateInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete template internal server error response
func (o *DeleteTemplateInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTemplateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
