// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"tafadmin/openapi/models"
)

// SelectTemplateOKCode is the HTTP code returned for type SelectTemplateOK
const SelectTemplateOKCode int = 200

/*SelectTemplateOK OK

swagger:response selectTemplateOK
*/
type SelectTemplateOK struct {

	/*
	  In: Body
	*/
	Payload *models.SelectResult `json:"body,omitempty"`
}

// NewSelectTemplateOK creates SelectTemplateOK with default headers values
func NewSelectTemplateOK() *SelectTemplateOK {

	return &SelectTemplateOK{}
}

// WithPayload adds the payload to the select template o k response
func (o *SelectTemplateOK) WithPayload(payload *models.SelectResult) *SelectTemplateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the select template o k response
func (o *SelectTemplateOK) SetPayload(payload *models.SelectResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SelectTemplateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SelectTemplateInternalServerErrorCode is the HTTP code returned for type SelectTemplateInternalServerError
const SelectTemplateInternalServerErrorCode int = 500

/*SelectTemplateInternalServerError 内部错误

swagger:response selectTemplateInternalServerError
*/
type SelectTemplateInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSelectTemplateInternalServerError creates SelectTemplateInternalServerError with default headers values
func NewSelectTemplateInternalServerError() *SelectTemplateInternalServerError {

	return &SelectTemplateInternalServerError{}
}

// WithPayload adds the payload to the select template internal server error response
func (o *SelectTemplateInternalServerError) WithPayload(payload *models.Error) *SelectTemplateInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the select template internal server error response
func (o *SelectTemplateInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SelectTemplateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
