// Code generated by go-swagger; DO NOT EDIT.

package server_servant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"tafadmin/openapi/models"
)

// CreateServerAdapterOKCode is the HTTP code returned for type CreateServerAdapterOK
const CreateServerAdapterOKCode int = 200

/*CreateServerAdapterOK OK

swagger:response createServerAdapterOK
*/
type CreateServerAdapterOK struct {

	/*
	  In: Body
	*/
	Payload *CreateServerAdapterOKBody `json:"body,omitempty"`
}

// NewCreateServerAdapterOK creates CreateServerAdapterOK with default headers values
func NewCreateServerAdapterOK() *CreateServerAdapterOK {

	return &CreateServerAdapterOK{}
}

// WithPayload adds the payload to the create server adapter o k response
func (o *CreateServerAdapterOK) WithPayload(payload *CreateServerAdapterOKBody) *CreateServerAdapterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create server adapter o k response
func (o *CreateServerAdapterOK) SetPayload(payload *CreateServerAdapterOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateServerAdapterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateServerAdapterInternalServerErrorCode is the HTTP code returned for type CreateServerAdapterInternalServerError
const CreateServerAdapterInternalServerErrorCode int = 500

/*CreateServerAdapterInternalServerError 内部错误

swagger:response createServerAdapterInternalServerError
*/
type CreateServerAdapterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateServerAdapterInternalServerError creates CreateServerAdapterInternalServerError with default headers values
func NewCreateServerAdapterInternalServerError() *CreateServerAdapterInternalServerError {

	return &CreateServerAdapterInternalServerError{}
}

// WithPayload adds the payload to the create server adapter internal server error response
func (o *CreateServerAdapterInternalServerError) WithPayload(payload *models.Error) *CreateServerAdapterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create server adapter internal server error response
func (o *CreateServerAdapterInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateServerAdapterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
