// Code generated by go-swagger; DO NOT EDIT.

package server_servant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"tafadmin/openapi/models"
)

// DeleteServerAdapterOKCode is the HTTP code returned for type DeleteServerAdapterOK
const DeleteServerAdapterOKCode int = 200

/*DeleteServerAdapterOK OK

swagger:response deleteServerAdapterOK
*/
type DeleteServerAdapterOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteServerAdapterOKBody `json:"body,omitempty"`
}

// NewDeleteServerAdapterOK creates DeleteServerAdapterOK with default headers values
func NewDeleteServerAdapterOK() *DeleteServerAdapterOK {

	return &DeleteServerAdapterOK{}
}

// WithPayload adds the payload to the delete server adapter o k response
func (o *DeleteServerAdapterOK) WithPayload(payload *DeleteServerAdapterOKBody) *DeleteServerAdapterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete server adapter o k response
func (o *DeleteServerAdapterOK) SetPayload(payload *DeleteServerAdapterOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteServerAdapterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteServerAdapterInternalServerErrorCode is the HTTP code returned for type DeleteServerAdapterInternalServerError
const DeleteServerAdapterInternalServerErrorCode int = 500

/*DeleteServerAdapterInternalServerError 内部错误

swagger:response deleteServerAdapterInternalServerError
*/
type DeleteServerAdapterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteServerAdapterInternalServerError creates DeleteServerAdapterInternalServerError with default headers values
func NewDeleteServerAdapterInternalServerError() *DeleteServerAdapterInternalServerError {

	return &DeleteServerAdapterInternalServerError{}
}

// WithPayload adds the payload to the delete server adapter internal server error response
func (o *DeleteServerAdapterInternalServerError) WithPayload(payload *models.Error) *DeleteServerAdapterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete server adapter internal server error response
func (o *DeleteServerAdapterInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteServerAdapterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
