apiVersion: v2
name: tarscontrol
version: 0.0.1
kubeVersion: ">= 1.17.0 <= 1.19.0"
type: application
keywords: [ tars , tarscontrol ,tarscontroller ]
maintainers:
  - name: adugeek
    email: root@libssl.com
appVersion: v1alpha1