apiVersion: v1
kind: Service
metadata:
  labels:
    app: taf-web
  name: taf-tafweb
  namespace: taf
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: taf-web
  sessionAffinity: None
  type: NodePort

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: taf-web
  name: taf-tafweb
  namespace: taf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taf-web
  serviceName: taf-tafweb
  template:
    metadata:
      labels:
        app: taf-web
      name: taf-tafweb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: taf.io/node
                operator: Exists
              - key: taf.io/ability.taf
                operator: Exists
      containers:
        - image:  _DOCKER_REGISTRY_URL_/taf.tafweb:10000
          imagePullPolicy: Always
          name: taf-tafweb
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      imagePullSecrets:
        - name: taf-image-secret
      restartPolicy: Always
      schedulerName: default-scheduler
