apiVersion: v1
kind: Service
metadata:
  labels:
    app: tars-web
  name: tars-tafweb
  namespace: tars
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: tars-web
  sessionAffinity: None
  type: NodePort

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: tars-web
  name: tars-tafweb
  namespace: tars
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tars-web
  serviceName: tars-tafweb
  template:
    metadata:
      labels:
        app: tars-web
      name: tars-tafweb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tars.io/node
                operator: Exists
              - key: tars.io/ability.tars
                operator: Exists
      containers:
        - image:  _DOCKER_REGISTRY_URL_/tars.tafweb:10000
          imagePullPolicy: Always
          name: tars-tafweb
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      imagePullSecrets:
        - name: tars-image-secret
      restartPolicy: Always
      schedulerName: default-scheduler
