apiVersion: v1
kind: ServiceAccount
metadata:
  name: tars-tarsadmin
  namespace: tars

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tars-tarsadmin
  namespace: tars
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["daemonsets","deployments","deployments/scale","deployments/rollback","statefulsets","statefulsets/scale","statefulsets/rollback"]
    verbs: ["*"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tars-tarsadmin
  namespace: tars
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tars-tarsadmin
subjects:
  - kind: ServiceAccount
    name: tars-tarsadmin
    namespace: tars
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tars-tarsadmin
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch","update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tars-tarsadmin
subjects:
- kind: ServiceAccount
  name: tars-tarsadmin
  namespace: tars
roleRef:
  kind: ClusterRole
  name: tars-tarsadmin
  apiGroup: rbac.authorization.k8s.io
---

kind: Service
apiVersion: v1
metadata:
  labels:
    TafServerApp: tars
    TafServerName: tarsadmin
  name: tars-tarsadmin
  namespace: tars
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: tars-tarsadmin
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: tars-tarsadmin
  name: tars-tarsadmin
  namespace: tars
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tars-tarsadmin
  serviceName: tars-tarsadmin
  template:
    metadata:
      labels:
        app: tars-tarsadmin
      name: tars-tarsadmin
    spec:
      serviceAccountName: tars-tarsadmin
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tars.io/node
                operator: Exists
              - key: tars.io/ability.tars
                operator: Exists
      containers:
        - image: _DOCKER_REGISTRY_URL_/tars.tarsadmin:10000
          imagePullPolicy: Always
          name: tars-tarsadmin
          envFrom:
          - secretRef:
              name: tars-db
          volumeMounts:
            - mountPath: /host-log-path
              name: host-log-path
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      imagePullSecrets:
        - name: tars-image-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /usr/local/app/tars/app_log
            type: DirectoryOrCreate
          name: host-log-path
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate