apiVersion: v1
kind: Service
metadata:
  annotations:
    tars.io/Servant: '{"queryobj":{"Name":"QueryObj","Port":10000,"HostPort":0,"Threads":3,"Connections":10000,"Capacity":10000,"Timeout":60000,"IsTaf":true,"IsTcp":true}}'
  labels:
    tars.io/ServerApp: tars
    tars.io/ServerName: tarsqueryproperty
  name: tars-tarsqueryproperty
  namespace: tars
spec:
  clusterIP: None
  ports:
    - name: queryobj
      port: 10000
      protocol: TCP
      targetPort: 10000
    - name: nodeobj
      port: 19385
      protocol: TCP
      targetPort: 19385
  selector:
    tars.io/ServerApp: tars
    tars.io/ServerName: tarsqueryproperty
  sessionAffinity: None
  type: ClusterIP
  
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    tars.io/NodeSelector: '{"Kind":"AbilityPool","Value":[]}'
    tars.io/NotStacked: "false"
  labels:
    tars.io/ServerApp: tars
    tars.io/ServerName: tarsqueryproperty
  name: tars-tarsqueryproperty
  namespace: tars
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      tars.io/ServerApp: tars
      tars.io/ServerName: tarsqueryproperty
  serviceName: tars-tarsqueryproperty
  template:
    metadata:
      labels:
        tars.io/ServerApp: tars
        tars.io/ServerName: tarsqueryproperty
        tars.io/ServerVersion: "10000"
      name: tars-tarsqueryproperty
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tars.io/node
                operator: Exists
              - key: tars.io/ability.tars
                operator: Exists 
      containers:
        - env:
            - name: ServerApp
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['tars.io/ServerApp']
            - name: PodName
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: _DOCKER_REGISTRY_URL_/tars.tarsqueryproperty:10000
          imagePullPolicy: Always
          name: tars-tarsqueryproperty
          volumeMounts:
            - mountPath: /host-log-path
              name: host-log-path
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      imagePullSecrets:
        - name: tars-image-secret
      readinessGates:
      - conditionType: tars.io/service
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
        - hostPath:
            path: /usr/local/app/tars/app_log
            type: DirectoryOrCreate
          name: host-log-path

