apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tars-tafagent
  namespace: tars
  labels:
    app: tars-tafagent
spec:
  selector:
    matchLabels:
      app: tars-tafagent
  template:
    metadata:
      labels:
        app: tars-tafagent
    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: tars.io/node
                    operator: Exists
      containers:
        - name: tars-tafagent
          image: _DOCKER_REGISTRY_URL_/tars.tafagent:10000
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /usr/local/app/tars/app_log
              name: host-log-path
      volumes:
        - hostPath:
            path: /usr/local/app/tars/app_log
            type: DirectoryOrCreate
          name: host-log-path
      imagePullSecrets:
        - name: tars-image-secret
