apiVersion: v1
kind: ServiceAccount
metadata:
  name: tars-tafregistry
  namespace: tars

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tars-tafregistry
  namespace: tars
rules:
  - apiGroups: [""]
    resources: ["events","pods","endpoints"]
    verbs: ["list","watch"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["patch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tars-tafregistry
  namespace: tars
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tars-tafregistry
subjects:
  - kind: ServiceAccount
    name: tars-tafregistry
    namespace: tars

---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: tars-tafregistry
  name: tars-tafregistry
  namespace: tars
spec:
  clusterIP: None
  ports:
    - name: queryobj
      port: 17891
      protocol: TCP
    - name: registryobj
      port: 17890
      protocol: TCP
  selector:
    app: tars-tafregistry
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: tars-tafregistry
  name: tars-tafregistry
  namespace: tars
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tars-tafregistry
  serviceName: tars-tafregistry
  template:
    metadata:
      labels:
        app: tars-tafregistry
      name: tars-tafregistry
    spec:
      serviceAccountName: tars-tafregistry
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: tars.io/node
                    operator: Exists
                  - key: tars.io/ability.tars
                    operator: Exists
      containers:
        - image: _DOCKER_REGISTRY_URL_/tars.tafregistry:10000
          imagePullPolicy: Always
          name: tars-tafregistry
          envFrom:
            - secretRef:
              name: tars-db
          volumeMounts:
            - mountPath: /host-log-path
              name: host-log-path
          env:
            - name: _EXTERNAL_JCEPROXY_
              value: "external-jceproxy"
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      imagePullSecrets:
        - name: tars-image-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
        - hostPath:
            path: /usr/local/app/tars/app_log
            type: DirectoryOrCreate
          name: host-log-path