// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TConfig) DeepCopyInto(out *TConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.AppConfig != nil {
		in, out := &in.AppConfig, &out.AppConfig
		*out = new(TConfigApp)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerConfig != nil {
		in, out := &in.ServerConfig, &out.ServerConfig
		*out = new(TConfigServer)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TConfig.
func (in *TConfig) DeepCopy() *TConfig {
	if in == nil {
		return nil
	}
	out := new(TConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TConfigApp) DeepCopyInto(out *TConfigApp) {
	*out = *in
	in.UpdateTime.DeepCopyInto(&out.UpdateTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TConfigApp.
func (in *TConfigApp) DeepCopy() *TConfigApp {
	if in == nil {
		return nil
	}
	out := new(TConfigApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TConfigList) DeepCopyInto(out *TConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TConfigList.
func (in *TConfigList) DeepCopy() *TConfigList {
	if in == nil {
		return nil
	}
	out := new(TConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TConfigServer) DeepCopyInto(out *TConfigServer) {
	*out = *in
	if in.PodSeq != nil {
		in, out := &in.PodSeq, &out.PodSeq
		*out = new(string)
		**out = **in
	}
	in.UpdateTime.DeepCopyInto(&out.UpdateTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TConfigServer.
func (in *TConfigServer) DeepCopy() *TConfigServer {
	if in == nil {
		return nil
	}
	out := new(TConfigServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TDeploy) DeepCopyInto(out *TDeploy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Apply.DeepCopyInto(&out.Apply)
	if in.Approve != nil {
		in, out := &in.Approve, &out.Approve
		*out = new(TDeployApprove)
		(*in).DeepCopyInto(*out)
	}
	if in.Deployed != nil {
		in, out := &in.Deployed, &out.Deployed
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TDeploy.
func (in *TDeploy) DeepCopy() *TDeploy {
	if in == nil {
		return nil
	}
	out := new(TDeploy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TDeploy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TDeployApprove) DeepCopyInto(out *TDeployApprove) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TDeployApprove.
func (in *TDeployApprove) DeepCopy() *TDeployApprove {
	if in == nil {
		return nil
	}
	out := new(TDeployApprove)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TDeployList) DeepCopyInto(out *TDeployList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TDeploy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TDeployList.
func (in *TDeployList) DeepCopy() *TDeployList {
	if in == nil {
		return nil
	}
	out := new(TDeployList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TDeployList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TEndpoint) DeepCopyInto(out *TEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TEndpoint.
func (in *TEndpoint) DeepCopy() *TEndpoint {
	if in == nil {
		return nil
	}
	out := new(TEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TEndpointList) DeepCopyInto(out *TEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TEndpointList.
func (in *TEndpointList) DeepCopy() *TEndpointList {
	if in == nil {
		return nil
	}
	out := new(TEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TEndpointPodStatus) DeepCopyInto(out *TEndpointPodStatus) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	if in.ContainerStatuses != nil {
		in, out := &in.ContainerStatuses, &out.ContainerStatuses
		*out = make([]v1.ContainerStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TEndpointPodStatus.
func (in *TEndpointPodStatus) DeepCopy() *TEndpointPodStatus {
	if in == nil {
		return nil
	}
	out := new(TEndpointPodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TEndpointSpec) DeepCopyInto(out *TEndpointSpec) {
	*out = *in
	if in.Taf != nil {
		in, out := &in.Taf, &out.Taf
		*out = new(TServerTaf)
		(*in).DeepCopyInto(*out)
	}
	if in.Normal != nil {
		in, out := &in.Normal, &out.Normal
		*out = new(TServerNormal)
		(*in).DeepCopyInto(*out)
	}
	if in.HostPorts != nil {
		in, out := &in.HostPorts, &out.HostPorts
		*out = make([]TK8SHostPort, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TEndpointSpec.
func (in *TEndpointSpec) DeepCopy() *TEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(TEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TEndpointStatus) DeepCopyInto(out *TEndpointStatus) {
	*out = *in
	if in.PodStatus != nil {
		in, out := &in.PodStatus, &out.PodStatus
		*out = make([]*TEndpointPodStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TEndpointPodStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TEndpointStatus.
func (in *TEndpointStatus) DeepCopy() *TEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(TEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TExitedPod) DeepCopyInto(out *TExitedPod) {
	*out = *in
	in.CreateTime.DeepCopyInto(&out.CreateTime)
	in.DeleteTime.DeepCopyInto(&out.DeleteTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TExitedPod.
func (in *TExitedPod) DeepCopy() *TExitedPod {
	if in == nil {
		return nil
	}
	out := new(TExitedPod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TExitedRecord) DeepCopyInto(out *TExitedRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = make([]TExitedPod, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TExitedRecord.
func (in *TExitedRecord) DeepCopy() *TExitedRecord {
	if in == nil {
		return nil
	}
	out := new(TExitedRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TExitedRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TExitedRecordList) DeepCopyInto(out *TExitedRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TExitedRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TExitedRecordList.
func (in *TExitedRecordList) DeepCopy() *TExitedRecordList {
	if in == nil {
		return nil
	}
	out := new(TExitedRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TExitedRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TK8SHostPort) DeepCopyInto(out *TK8SHostPort) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TK8SHostPort.
func (in *TK8SHostPort) DeepCopy() *TK8SHostPort {
	if in == nil {
		return nil
	}
	out := new(TK8SHostPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TK8SMount) DeepCopyInto(out *TK8SMount) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.MountPropagation != nil {
		in, out := &in.MountPropagation, &out.MountPropagation
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TK8SMount.
func (in *TK8SMount) DeepCopy() *TK8SMount {
	if in == nil {
		return nil
	}
	out := new(TK8SMount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TK8SNodeSelector) DeepCopyInto(out *TK8SNodeSelector) {
	*out = *in
	if in.NodeBind != nil {
		in, out := &in.NodeBind, &out.NodeBind
		*out = new(TK8SNodeSelectorKind)
		(*in).DeepCopyInto(*out)
	}
	if in.PublicPool != nil {
		in, out := &in.PublicPool, &out.PublicPool
		*out = new(TK8SNodeSelectorKind)
		(*in).DeepCopyInto(*out)
	}
	if in.AbilityPool != nil {
		in, out := &in.AbilityPool, &out.AbilityPool
		*out = new(TK8SNodeSelectorKind)
		(*in).DeepCopyInto(*out)
	}
	if in.DaemonSet != nil {
		in, out := &in.DaemonSet, &out.DaemonSet
		*out = new(TK8SNodeSelectorKind)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TK8SNodeSelector.
func (in *TK8SNodeSelector) DeepCopy() *TK8SNodeSelector {
	if in == nil {
		return nil
	}
	out := new(TK8SNodeSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TK8SNodeSelectorKind) DeepCopyInto(out *TK8SNodeSelectorKind) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TK8SNodeSelectorKind.
func (in *TK8SNodeSelectorKind) DeepCopy() *TK8SNodeSelectorKind {
	if in == nil {
		return nil
	}
	out := new(TK8SNodeSelectorKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TRelease) DeepCopyInto(out *TRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TRelease.
func (in *TRelease) DeepCopy() *TRelease {
	if in == nil {
		return nil
	}
	out := new(TRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TReleaseList) DeepCopyInto(out *TReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TReleaseList.
func (in *TReleaseList) DeepCopy() *TReleaseList {
	if in == nil {
		return nil
	}
	out := new(TReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TReleaseSpec) DeepCopyInto(out *TReleaseSpec) {
	*out = *in
	if in.List != nil {
		in, out := &in.List, &out.List
		*out = make([]*TReleaseVersion, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TReleaseVersion)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TReleaseSpec.
func (in *TReleaseSpec) DeepCopy() *TReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(TReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TReleaseVersion) DeepCopyInto(out *TReleaseVersion) {
	*out = *in
	in.CreateTime.DeepCopyInto(&out.CreateTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TReleaseVersion.
func (in *TReleaseVersion) DeepCopy() *TReleaseVersion {
	if in == nil {
		return nil
	}
	out := new(TReleaseVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServant) DeepCopyInto(out *TServant) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServant.
func (in *TServant) DeepCopy() *TServant {
	if in == nil {
		return nil
	}
	out := new(TServant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServer) DeepCopyInto(out *TServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServer.
func (in *TServer) DeepCopy() *TServer {
	if in == nil {
		return nil
	}
	out := new(TServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerExternal) DeepCopyInto(out *TServerExternal) {
	*out = *in
	if in.Upstreams != nil {
		in, out := &in.Upstreams, &out.Upstreams
		*out = make([]TServerExternalUPStream, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerExternal.
func (in *TServerExternal) DeepCopy() *TServerExternal {
	if in == nil {
		return nil
	}
	out := new(TServerExternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerExternalAddress) DeepCopyInto(out *TServerExternalAddress) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerExternalAddress.
func (in *TServerExternalAddress) DeepCopy() *TServerExternalAddress {
	if in == nil {
		return nil
	}
	out := new(TServerExternalAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerExternalUPStream) DeepCopyInto(out *TServerExternalUPStream) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]TServerExternalAddress, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerExternalUPStream.
func (in *TServerExternalUPStream) DeepCopy() *TServerExternalUPStream {
	if in == nil {
		return nil
	}
	out := new(TServerExternalUPStream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerK8S) DeepCopyInto(out *TServerK8S) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]v1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HostPorts != nil {
		in, out := &in.HostPorts, &out.HostPorts
		*out = make([]TK8SHostPort, len(*in))
		copy(*out, *in)
	}
	if in.Mounts != nil {
		in, out := &in.Mounts, &out.Mounts
		*out = make([]TK8SMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	if in.NotStacked != nil {
		in, out := &in.NotStacked, &out.NotStacked
		*out = new(bool)
		**out = **in
	}
	if in.ReadinessGate != nil {
		in, out := &in.ReadinessGate, &out.ReadinessGate
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerK8S.
func (in *TServerK8S) DeepCopy() *TServerK8S {
	if in == nil {
		return nil
	}
	out := new(TServerK8S)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerList) DeepCopyInto(out *TServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerList.
func (in *TServerList) DeepCopy() *TServerList {
	if in == nil {
		return nil
	}
	out := new(TServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerNormal) DeepCopyInto(out *TServerNormal) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]TServerNormalPort, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerNormal.
func (in *TServerNormal) DeepCopy() *TServerNormal {
	if in == nil {
		return nil
	}
	out := new(TServerNormal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerNormalPort) DeepCopyInto(out *TServerNormalPort) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerNormalPort.
func (in *TServerNormalPort) DeepCopy() *TServerNormalPort {
	if in == nil {
		return nil
	}
	out := new(TServerNormalPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerRelease) DeepCopyInto(out *TServerRelease) {
	*out = *in
	in.ActiveTime.DeepCopyInto(&out.ActiveTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerRelease.
func (in *TServerRelease) DeepCopy() *TServerRelease {
	if in == nil {
		return nil
	}
	out := new(TServerRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerSpec) DeepCopyInto(out *TServerSpec) {
	*out = *in
	if in.Taf != nil {
		in, out := &in.Taf, &out.Taf
		*out = new(TServerTaf)
		(*in).DeepCopyInto(*out)
	}
	if in.Normal != nil {
		in, out := &in.Normal, &out.Normal
		*out = new(TServerNormal)
		(*in).DeepCopyInto(*out)
	}
	in.K8S.DeepCopyInto(&out.K8S)
	if in.Release != nil {
		in, out := &in.Release, &out.Release
		*out = new(TServerRelease)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerSpec.
func (in *TServerSpec) DeepCopy() *TServerSpec {
	if in == nil {
		return nil
	}
	out := new(TServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TServerTaf) DeepCopyInto(out *TServerTaf) {
	*out = *in
	if in.Servants != nil {
		in, out := &in.Servants, &out.Servants
		*out = make([]TServant, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TServerTaf.
func (in *TServerTaf) DeepCopy() *TServerTaf {
	if in == nil {
		return nil
	}
	out := new(TServerTaf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TTemplate) DeepCopyInto(out *TTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TTemplate.
func (in *TTemplate) DeepCopy() *TTemplate {
	if in == nil {
		return nil
	}
	out := new(TTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TTemplateList) DeepCopyInto(out *TTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TTemplateList.
func (in *TTemplateList) DeepCopy() *TTemplateList {
	if in == nil {
		return nil
	}
	out := new(TTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TTemplateSpec) DeepCopyInto(out *TTemplateSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TTemplateSpec.
func (in *TTemplateSpec) DeepCopy() *TTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(TTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TTree) DeepCopyInto(out *TTree) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Businesses != nil {
		in, out := &in.Businesses, &out.Businesses
		*out = make([]TTreeBusiness, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Apps != nil {
		in, out := &in.Apps, &out.Apps
		*out = make([]TTreeApps, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TTree.
func (in *TTree) DeepCopy() *TTree {
	if in == nil {
		return nil
	}
	out := new(TTree)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TTree) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TTreeApps) DeepCopyInto(out *TTreeApps) {
	*out = *in
	in.CreateTime.DeepCopyInto(&out.CreateTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TTreeApps.
func (in *TTreeApps) DeepCopy() *TTreeApps {
	if in == nil {
		return nil
	}
	out := new(TTreeApps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TTreeBusiness) DeepCopyInto(out *TTreeBusiness) {
	*out = *in
	in.CreateTime.DeepCopyInto(&out.CreateTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TTreeBusiness.
func (in *TTreeBusiness) DeepCopy() *TTreeBusiness {
	if in == nil {
		return nil
	}
	out := new(TTreeBusiness)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TTreeList) DeepCopyInto(out *TTreeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TTree, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TTreeList.
func (in *TTreeList) DeepCopy() *TTreeList {
	if in == nil {
		return nil
	}
	out := new(TTreeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TTreeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
