// Code generated by go-swagger; DO NOT EDIT.

package agent

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"tarsadmin/openapi/models"
)

// SelectAvailHostPortOKCode is the HTTP code returned for type SelectAvailHostPortOK
const SelectAvailHostPortOKCode int = 200

/*SelectAvailHostPortOK OK

swagger:response selectAvailHostPortOK
*/
type SelectAvailHostPortOK struct {

	/*
	  In: Body
	*/
	Payload *SelectAvailHostPortOKBody `json:"body,omitempty"`
}

// NewSelectAvailHostPortOK creates SelectAvailHostPortOK with default headers values
func NewSelectAvailHostPortOK() *SelectAvailHostPortOK {

	return &SelectAvailHostPortOK{}
}

// WithPayload adds the payload to the select avail host port o k response
func (o *SelectAvailHostPortOK) WithPayload(payload *SelectAvailHostPortOKBody) *SelectAvailHostPortOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the select avail host port o k response
func (o *SelectAvailHostPortOK) SetPayload(payload *SelectAvailHostPortOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SelectAvailHostPortOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SelectAvailHostPortInternalServerErrorCode is the HTTP code returned for type SelectAvailHostPortInternalServerError
const SelectAvailHostPortInternalServerErrorCode int = 500

/*SelectAvailHostPortInternalServerError 内部错误

swagger:response selectAvailHostPortInternalServerError
*/
type SelectAvailHostPortInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSelectAvailHostPortInternalServerError creates SelectAvailHostPortInternalServerError with default headers values
func NewSelectAvailHostPortInternalServerError() *SelectAvailHostPortInternalServerError {

	return &SelectAvailHostPortInternalServerError{}
}

// WithPayload adds the payload to the select avail host port internal server error response
func (o *SelectAvailHostPortInternalServerError) WithPayload(payload *models.Error) *SelectAvailHostPortInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the select avail host port internal server error response
func (o *SelectAvailHostPortInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SelectAvailHostPortInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
