apiVersion: k8s.tars.io/v1alpha1
kind: TTemplate
metadata:
  name: tars.java
  namespace: {{.Release.Namespace}}
spec:
  content: |
    <tars>
      <application>
        <server>
          mainclass=com.tars.server.startup.Main
          classpath=${basepath}/conf:${basepath}/WEB-INF/classes:${basepath}/WEB-INF/lib
          #jvmparams=-Dcom.sun.management.jmxremote.ssl\=false -Dcom.sun.management.jmxremote.authenticate\=false -Xms2000m -Xmx2000m -Xmn1000m -Xss1000k -XX:PermSize\=128M -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction\=60 -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDateStamps -XX:+CMSParallelRemarkEnabled -XX:+CMSScavengeBeforeRemark -XX:+UseCMSCompactAtFullCollection -XX:CMSFullGCsBeforeCompaction\=0 -verbosegc -XX:+PrintGCDetails -XX:ErrorFile\=${logpath}/${app}/${server}/jvm_error.log
          jvmparams=-XX:ErrorFile\=${logpath}/${app}/${server}/jvm_error.log -Dtars=true
          sessiontimeout=120000
          sessioncheckinterval=60000
          tcpnodelay=true
          udpbuffersize=8192
          charsetname=UTF-8
          backupfiles=conf
          loglevel=DEBUG
        </server>
      </application>
    </tars>
  parent: tars.default
