apiVersion: v1
kind: ServiceAccount
metadata:
  name: taf-tafregistry
  namespace: taf

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: taf-tafregistry
  namespace: taf
rules:
  - apiGroups: [""]
    resources: ["services","events","pods","endpoints"]
    verbs: ["*"]
  - apiGroups: ["crd.taf.com"]
    resources: ["estates"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: taf-tafregistry
  namespace: taf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: taf-tafregistry
subjects:
  - kind: ServiceAccount
      name: taf-tafregistry
    namespace: taf

---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: taf-tafregistry
  name: taf-tafregistry
  namespace: taf
spec:
  clusterIP: None
  ports:
    - name: queryobj
      port: 17891
      protocol: TCP
    - name: registryobj
      port: 17890
      protocol: TCP
  selector:
    app: taf-tafregistry
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: taf-tafregistry
  name: taf-tafregistry
  namespace: taf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taf-tafregistry
  serviceName: taf-tafregistry
  template:
    metadata:
      labels:
        app: taf-tafregistry
      name: taf-tafregistry
    spec:
      serviceAccountName: taf-tafregistry
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: taf.io/node
                    operator: Exists
                  - key: taf.io/ability.taf
                    operator: Exists
      containers:
        - image: _DOCKER_REGISTRY_URL_/taf.tafregistry:10000
          imagePullPolicy: Always
          name: taf-tafregistry
          envFrom:
            - secretRef:
                name: taf-db
          volumeMounts:
            - mountPath: /host-log-path
              name: host-log-path
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      imagePullSecrets:
        - name: taf-image-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
        - hostPath:
            path: /usr/local/app/taf/app_log
            type: Directory
          name: host-log-path