apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: taccounts.k8s.tars.io
spec:
  conversion:
    strategy: None
  group: k8s.tars.io
  names:
    kind: TAccount
    listKind: TAccountList
    plural: taccounts
    singular: taccount
    shortNames: [ ta ]
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                username:
                  type: string
                  pattern: ^[\x21-\x7e\p{Han}]*$
                  minLength: 2
                  maxLength: 16
                extra:
                  type: array
                  items:
                    type: string
                    maxLength: 1024
                authentication:
                  type: object
                  properties:
                    password:
                      type: string
                      pattern: ^[\x21-\x7e]*$
                      minLength: 6
                      maxLength: 32
                    bcryptPassword:
                      type: string
                      minLength: 60
                      maxLength: 60
                    activated:
                      type: boolean
                      default: false
                    tokens:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            pattern: ^[\x21-\x7e]*$
                            minLength: 2
                            maxLength: 32
                          content:
                            type: string
                            maxLength: 8092
                          updateTime:
                            type: string
                            format: date-time
                          expirationTime:
                            type: string
                            format: date-time
                          valid:
                            type: boolean
                            default: true
                      required: [ name,content,expirationTime ]
                  oneOf:
                    - required: [ password ]
                    - required: [ bcryptPassword ]
                authorization:
                  type: array
                  items:
                    type: object
                    properties:
                      role:
                        type: string
                        enum: [ admin ,operator ,developer ]
                      flag:
                        type: string
                        maxLength: 1600
                      updateTime:
                        type: string
                        format: date-time
                  required: [ role,flag ]
              required: [ username,authentication,authorization ]
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                username:
                  type: string
                  pattern: ^[\x21-\x7e\p{Han}]*$
                  minLength: 2
                  maxLength: 16
                extra:
                  type: array
                  items:
                    type: string
                    maxLength: 1024
                authentication:
                  type: object
                  properties:
                    password:
                      type: string
                      pattern: ^[\x21-\x7e]*$
                      minLength: 6
                      maxLength: 32
                    bcryptPassword:
                      type: string
                      minLength: 60
                      maxLength: 60
                    activated:
                      type: boolean
                      default: false
                    tokens:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            pattern: ^[\x21-\x7e]*$
                            minLength: 2
                            maxLength: 32
                          content:
                            type: string
                            maxLength: 8092
                          updateTime:
                            type: string
                            format: date-time
                          expirationTime:
                            type: string
                            format: date-time
                          valid:
                            type: boolean
                            default: true
                      required: [ name,content,expirationTime ]
                  oneOf:
                    - required: [ password ]
                    - required: [ bcryptPassword ]
                authorization:
                  type: array
                  items:
                    type: object
                    properties:
                      role:
                        type: string
                        enum: [ admin ,operator ,developer ]
                      flag:
                        type: string
                        maxLength: 1600
                      updateTime:
                        type: string
                        format: date-time
                  required: [ role,flag ]
              required: [ username,authentication,authorization ]
