apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tconfigs.k8s.tars.io
spec:
  conversion:
    strategy: None
  group: k8s.tars.io
  names:
    kind: TConfig
    listKind: TConfigList
    plural: tconfigs
    shortNames:
      - tc
    singular: tconfig
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            app:
              type: string
              pattern: ^[a-zA-Z][a-zA-Z0-9]*$
              maxLength: 63
            server:
              type: string
              pattern: ^([a-zA-Z][a-zA-Z0-9]*){0,1}$
              maxLength: 63
              default: ""
            configName:
              type: string
              pattern: ^[A-Za-z0-9]([-A-Za-z0-9_.]*[A-Za-z0-9])?$
              maxLength: 63
            configContent:
              type: string
              maxLength: 1560000
            podSeq:
              type: string
              pattern: ^(m|0|[1-9][0-9]?)$
              default: "m"
            updateTime:
              type: string
              format: date-time
            updatePerson:
              type: string
              maxLength: 100
            updateReason:
              type: string
              maxLength: 1600
            activated:
              type: boolean
              default: true
            version:
              type: string
              pattern: ^[A-Za-z0-9]([-A-Za-z0-9_.]*[A-Za-z0-9])?$
              maxLength: 63
          required: [ app, configName,configContent ]
      additionalPrinterColumns:
        - name: App
          type: string
          jsonPath: .app
        - name: Server
          type: string
          jsonPath: .server
        - name: PodSeq
          type: string
          jsonPath: .podSeq
        - name: ConfigName
          type: string
          jsonPath: .configName
        - name: Version
          type: string
          jsonPath: .version
        - name: Activated
          type: boolean
          jsonPath: .activated
    - name: v1beta2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            app:
              type: string
              pattern: ^[a-zA-Z][a-zA-Z0-9]*$
              maxLength: 63
            server:
              type: string
              pattern: ^([a-zA-Z][a-zA-Z0-9]*){0,1}$
              maxLength: 63
              default: ""
            configName:
              type: string
              pattern: ^[A-Za-z0-9]([-A-Za-z0-9_.]*[A-Za-z0-9])?$
              maxLength: 63
            configContent:
              type: string
              maxLength: 1560000
            podSeq:
              type: string
              pattern: ^(m|0|[1-9][0-9]?)$
              default: "m"
            updateTime:
              type: string
              format: date-time
            updatePerson:
              type: string
              maxLength: 100
            updateReason:
              type: string
              maxLength: 1600
            activated:
              type: boolean
              default: true
            version:
              type: string
              pattern: ^[A-Za-z0-9]([-A-Za-z0-9_.]*[A-Za-z0-9])?$
              maxLength: 63
          required: [ app, configName,configContent ]
      additionalPrinterColumns:
        - name: App
          type: string
          jsonPath: .app
        - name: Server
          type: string
          jsonPath: .server
        - name: PodSeq
          type: string
          jsonPath: .podSeq
        - name: ConfigName
          type: string
          jsonPath: .configName
        - name: Version
          type: string
          jsonPath: .version
        - name: Activated
          type: boolean
          jsonPath: .activated
