apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tendpoints.k8s.tars.io
spec:
  conversion:
    strategy: None
  group: k8s.tars.io
  names:
    kind: TEndpoint
    listKind: TEndpointList
    plural: tendpoints
    shortNames:
      - te
    singular: tendpoint
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          properties:
            spec:
              type: object
              properties:
                app:
                  type: string
                server:
                  type: string
                important:
                  type: integer
                subType:
                  type: string
                tars:
                  type: object
                  properties:
                    profile:
                      type: string
                    servants:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          port:
                            type: integer
                          thread:
                            type: integer
                          capacity:
                            type: integer
                          connection:
                            type: integer
                          isTars:
                            type: boolean
                          isTcp:
                            type: boolean
                          timeout:
                            type: integer
                    ports:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          port:
                            type: integer
                          isTcp:
                            type: boolean
                    asyncThread:
                      type: integer
                    template:
                      type: string
                normal:
                  type: object
                  properties:
                    ports:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          port:
                            type: integer
                          isTcp:
                            type: boolean
                hostPorts:
                  type: array
                  items:
                    type: object
                    properties:
                      nameRef:
                        type: string
                      port:
                        type: integer
                release:
                  type: object
                  properties:
                    id:
                      type: string
                    image:
                      type: string
                    secret:
                      type: string
                    source:
                      type: string
            status:
              properties:
                pods:
                  items:
                    properties:
                      containerStatuses:
                        items:
                          properties:
                            containerID:
                              type: string
                            image:
                              type: string
                            imageID:
                              type: string
                            lastState:
                              properties:
                                running:
                                  properties:
                                    startedAt:
                                      type: string
                                  type: object
                                terminated:
                                  properties:
                                    containerID:
                                      type: string
                                    exitCode:
                                      type: integer
                                    finishedAt:
                                      type: string
                                    message:
                                      type: string
                                    reason:
                                      type: string
                                    signal:
                                      type: integer
                                    startedAt:
                                      type: string
                                  type: object
                                waiting:
                                  properties:
                                    message:
                                      type: string
                                    reason:
                                      type: string
                                  type: object
                              type: object
                            name:
                              type: string
                            ready:
                              type: boolean
                            restartCount:
                              type: integer
                            started:
                              type: boolean
                            state:
                              properties:
                                running:
                                  properties:
                                    startedAt:
                                      type: string
                                  type: object
                                terminated:
                                  properties:
                                    containerID:
                                      type: string
                                    exitCode:
                                      type: integer
                                    finishedAt:
                                      type: string
                                    message:
                                      type: string
                                    reason:
                                      type: string
                                    signal:
                                      type: integer
                                    startedAt:
                                      type: string
                                  type: object
                                waiting:
                                  properties:
                                    message:
                                      type: string
                                    reason:
                                      type: string
                                  type: object
                              type: object
                          type: object
                        type: array
                      hostIP:
                        type: string
                      name:
                        type: string
                      podIP:
                        type: string
                      presentMessage:
                        type: string
                      presentState:
                        type: string
                      settingState:
                        type: string
                      startTime:
                        type: string
                      id:
                        type: string
                      uid:
                        type: string
                        format: uuid
                    type: object
                  type: array
              required:
                - pods
              type: object
          type: object
      subresources:
        status: { }
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              type: object
              properties:
                app:
                  type: string
                server:
                  type: string
                important:
                  type: integer
                subType:
                  type: string
                tars:
                  type: object
                  properties:
                    profile:
                      type: string
                    servants:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          port:
                            type: integer
                          thread:
                            type: integer
                          capacity:
                            type: integer
                          connection:
                            type: integer
                          isTars:
                            type: boolean
                          isTcp:
                            type: boolean
                          timeout:
                            type: integer
                    ports:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          port:
                            type: integer
                          isTcp:
                            type: boolean
                    asyncThread:
                      type: integer
                    template:
                      type: string
                normal:
                  type: object
                  properties:
                    ports:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          port:
                            type: integer
                          isTcp:
                            type: boolean
                hostPorts:
                  type: array
                  items:
                    type: object
                    properties:
                      nameRef:
                        type: string
                      port:
                        type: integer
                release:
                  type: object
                  properties:
                    id:
                      type: string
                    image:
                      type: string
                    secret:
                      type: string
                    source:
                      type: string
            status:
              properties:
                pods:
                  items:
                    properties:
                      containerStatuses:
                        items:
                          properties:
                            containerID:
                              type: string
                            image:
                              type: string
                            imageID:
                              type: string
                            lastState:
                              properties:
                                running:
                                  properties:
                                    startedAt:
                                      type: string
                                  type: object
                                terminated:
                                  properties:
                                    containerID:
                                      type: string
                                    exitCode:
                                      type: integer
                                    finishedAt:
                                      type: string
                                    message:
                                      type: string
                                    reason:
                                      type: string
                                    signal:
                                      type: integer
                                    startedAt:
                                      type: string
                                  type: object
                                waiting:
                                  properties:
                                    message:
                                      type: string
                                    reason:
                                      type: string
                                  type: object
                              type: object
                            name:
                              type: string
                            ready:
                              type: boolean
                            restartCount:
                              type: integer
                            started:
                              type: boolean
                            state:
                              properties:
                                running:
                                  properties:
                                    startedAt:
                                      type: string
                                  type: object
                                terminated:
                                  properties:
                                    containerID:
                                      type: string
                                    exitCode:
                                      type: integer
                                    finishedAt:
                                      type: string
                                    message:
                                      type: string
                                    reason:
                                      type: string
                                    signal:
                                      type: integer
                                    startedAt:
                                      type: string
                                  type: object
                                waiting:
                                  properties:
                                    message:
                                      type: string
                                    reason:
                                      type: string
                                  type: object
                              type: object
                          type: object
                        type: array
                      hostIP:
                        type: string
                      name:
                        type: string
                      podIP:
                        type: string
                      presentMessage:
                        type: string
                      presentState:
                        type: string
                      settingState:
                        type: string
                      startTime:
                        type: string
                      id:
                        type: string
                      uid:
                        type: string
                        format: uuid
                    type: object
                  type: array
              required:
                - pods
              type: object
          type: object
      subresources:
        status: { }

