apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tgateways.k8s.tars.io
spec:
  conversion:
    strategy: None
  group: k8s.tars.io
  names:
    kind: TGateway
    listKind: TGatewayList
    plural: tgateways
    singular: tgateway
    shortNames:
      - tg
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                obj:
                  type: string
                update_person:
                  type: string
                update_time:
                  type: string
                  format: date-time
                extra:
                  type: array
                  items:
                    type: string
                    maxLength: 1024
    - name: v1beta2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                obj:
                  type: string
                update_person:
                  type: string
                update_time:
                  type: string
                  format: date-time
                extra:
                  type: array
                  items:
                    type: string
                    maxLength: 1024