apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ttemplates.k8s.tars.io
spec:
  conversion:
    strategy: None
  group: k8s.tars.io
  names:
    kind: TTemplate
    listKind: TTemplateList
    plural: ttemplates
    shortNames: [ tt ]
    singular: ttemplate
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                content:
                  type: string
                  maxLength: 1560000
                parent:
                  type: string
                  pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                  maxLength: 253
              required: [ content,parent ]
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                content:
                  type: string
                  maxLength: 1560000
                parent:
                  type: string
                  pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                  maxLength: 253
              required: [ content,parent ]
