apiVersion: k8s.tars.io/{{ .Chart.AppVersion }}
kind: TTemplate
metadata:
  name: tars.cpp
  namespace: {{.Release.Namespace}}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-9"
spec:
  content: ""
  parent: tars.default
