apiVersion: v1
kind: ServiceAccount
metadata:
  name: tars-tarsweb
  namespace: {{.Release.Namespace}}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tars-tarsweb
  namespace: {{.Release.Namespace}}
rules:
  - apiGroups: [ "" ]
    resources: [ pods ]
    verbs: [ get,list,delete ]
  - apiGroups: [ "" ]
    resources: [ pods/exec ]
    verbs: [ create, get ]
  - apiGroups: [ autoscaling ]
    resources: [ horizontalpodautoscalers ]
    verbs: [ create,get,list,watch,patch,update,delete ]
  - apiGroups: [ k8s.tars.io ]
    resources: [ ttrees,tframeworkconfigs ]
    verbs: [ get ,list,watch,patch,update ]
  - apiGroups: [ k8s.tars.io ]
    resources: [ tdeploys, tservers, ttemplates, treleases,tconfigs,taccounts, tgateways, timages ]
    verbs: [ create, get ,list,delete,watch ,patch, update ]
  - apiGroups: [ k8s.tars.io ]
    resources: [ tendpoints,tendpoints/status,texitedrecords ]
    verbs: [ get ,list, watch ]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tars-tarsweb
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tars-tarsweb
subjects:
  - kind: ServiceAccount
    name: tars-tarsweb
    namespace: {{.Release.Namespace}}
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Release.Namespace}}:tars-tarsweb
rules:
  - apiGroups: [ "" ]
    resources: [ nodes ]
    verbs: [ get,list, watch,update,patch ]
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Release.Namespace}}:tars-tarsweb
roleRef:
  kind: ClusterRole
  name: {{.Release.Namespace}}:tars-tarsweb
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: tars-tarsweb
    namespace: {{.Release.Namespace}}

---

apiVersion: k8s.tars.io/{{ .Chart.AppVersion }}
kind: TImage
metadata:
  name: tars-tarsweb
  namespace: {{.Release.Namespace}}
  labels:
    tars.io/ServerApp: tars
    tars.io/ServerName: tarsweb
    tars.io/SubType: normal
imageType: server
releases:
  - id: {{.Values.helm.build.id | quote }}
    image: "{{.Values.helm.dockerhub.registry }}/tars.tarsweb:{{.Values.helm.build.id}}"
{{- include "TImageMerger" (dict "version" .Chart.AppVersion "namespace" .Release.Namespace  "name" "tars-tarsweb" ) | nindent 2 -}}
{{"\n"}}

---

apiVersion: k8s.tars.io/{{ .Chart.AppVersion }}
kind: TServer
metadata:
  name: tars-tarsweb
  namespace: {{.Release.Namespace}}
  annotations:
    tars.io/MinReplicas: "1"
    tars.io/MaxReplicas: "2"
  labels:
    tars.io/ServerApp: tars
    tars.io/ServerName: tarsweb
    tars.io/SubType: normal
spec:
  app: tars
  server: tarsweb
  subType: normal
  normal:
    ports:
      - name: http
        port: 3000
  k8s:
    serviceAccount: tars-tarsweb
    env:
      - name: Namespace
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: ENABLE_K8S
        value: "true"
      - name: PodName
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
    replicas: 1
    mounts:
      - name: host-log-dir
        source:
          hostPath:
            path: /usr/local/app/tars/app_log
            type: DirectoryOrCreate
        mountPath: /tars-web/log
        subPathExpr: $(Namespace)/$(PodName)
  release:
    id: {{.Values.helm.build.id | quote }}
    image: "{{.Values.helm.dockerhub.registry }}/tars.tarsweb:{{.Values.helm.build.id}}"

---
{{ $ingress := lookup "networking.k8s.io/v1beta1"  "Ingress" .Release.Namespace "tars-web" -}}
{{- if not $ingress -}}
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: tars-web
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1200"
spec:
  rules:
    - host: {{.Values.web}}
      http:
        paths:
          - backend:
              serviceName: tars-tarsweb
              servicePort: 3000
{{- else}}
  {{ $ingress | toYaml }}
{{- end }}
