{{ $v := lookup  "k8s.tars.io/v1beta1"  "TTemplate" .Release.Namespace "tars.nodejs" -}}
  {{- if not $v -}}
apiVersion: k8s.tars.io/{{ .Chart.AppVersion }}
kind: TTemplate
metadata:
  name: tars.nodejs
  namespace: {{.Release.Namespace}}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-9"
spec:
  content: |
    <tars>
      <application>
        <client>
          #网络异步回调线程个数
          asyncthread = 2
        </client>
      </application>
    </tars>
  parent: tars.default
  {{- end }}