apiVersion: v1
kind: ServiceAccount
metadata:
  name: tars-tarsimage
  namespace: {{.Release.Namespace}}
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tars-tarsimage
  namespace: {{.Release.Namespace}}
rules:
  - apiGroups: [ "" ]
    resources: [ secrets ]
    verbs: [ get ]
  - apiGroups: [ k8s.tars.io ]
    resources: [ timages ]
    verbs: [ get ,update, patch ]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tars-tarsimage
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tars-tarsimage
subjects:
  - kind: ServiceAccount
    name: tars-tarsimage
    namespace: {{.Release.Namespace}}
---

  {{ $v := lookup "v1"  "ConfigMap" .Release.Namespace "tars-tarsimage" -}}
  {{- if not $v -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tars-tarsimage
  namespace: {{.Release.Namespace}}
data:
  registry: {{.Values.dockerRegistry}}
  secret: {{.Values.dockerSecret}}
  {{- else}}
  {{ $v | toYaml }}
  {{- end }}
---

apiVersion: k8s.tars.io/{{ .Chart.AppVersion }}
kind: TImage
metadata:
  name: tars-tarsimage
  namespace: {{.Release.Namespace}}
  labels:
    tars.io/ServerApp: tars
    tars.io/ServerName: tarsimage
imageType: server
releases:
  - id: {{.Values.helm.build.id | quote }}
    image:
      {{.Values.helm.dockerhub.registry }}/tars.tarsimage:{{.Values.helm.build.id}}
---

apiVersion: k8s.tars.io/{{ .Chart.AppVersion }}
kind: TServer
metadata:
  name: tars-tarsimage
  namespace: {{.Release.Namespace}}
  labels:
    tars.io/ServerApp: tars
    tars.io/ServerName: tarsimage
    tars.io/SubType: normal
    tars.io/Template: tars.default
spec:
  app: tars
  server: tarsimage
  subType: normal
  normal:
    ports:
      - name: http
        port: 80
  k8s:
    replicas: 1
    mounts:
      - name: docker-sock
        source:
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        mountPath: /var/run/docker.sock
      - name: registry-env
        source:
          configMap:
            name: tars-tarsimage
        mountPath: /etc/registry-env
    serviceAccount: tars-tarsimage
  release:
    source: tars-tarsimage
    id: {{.Values.helm.build.id | quote }}
    image:
      {{.Values.helm.dockerhub.registry }}/tars.tarsimage:{{.Values.helm.build.id}}
