{{ $tt := lookup  (printf "k8s.tars.io/%s" $.Chart.AppVersion) "TTemplate" $.Release.Namespace "tars.cpp" -}}
{{- if not $tt -}}
apiVersion: k8s.tars.io/{{ .Chart.AppVersion }}
kind: TTemplate
metadata:
  name: tars.cpp
  namespace: {{.Release.Namespace}}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-9"
spec:
  content: ""
  parent: tars.default
{{- end }}
