// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"tarsadmin/openapi/models"
)

// DeleteServerOKCode is the HTTP code returned for type DeleteServerOK
const DeleteServerOKCode int = 200

/*DeleteServerOK OK

swagger:response deleteServerOK
*/
type DeleteServerOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteServerOKBody `json:"body,omitempty"`
}

// NewDeleteServerOK creates DeleteServerOK with default headers values
func NewDeleteServerOK() *DeleteServerOK {

	return &DeleteServerOK{}
}

// WithPayload adds the payload to the delete server o k response
func (o *DeleteServerOK) WithPayload(payload *DeleteServerOKBody) *DeleteServerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete server o k response
func (o *DeleteServerOK) SetPayload(payload *DeleteServerOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteServerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteServerInternalServerErrorCode is the HTTP code returned for type DeleteServerInternalServerError
const DeleteServerInternalServerErrorCode int = 500

/*DeleteServerInternalServerError 内部错误

swagger:response deleteServerInternalServerError
*/
type DeleteServerInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteServerInternalServerError creates DeleteServerInternalServerError with default headers values
func NewDeleteServerInternalServerError() *DeleteServerInternalServerError {

	return &DeleteServerInternalServerError{}
}

// WithPayload adds the payload to the delete server internal server error response
func (o *DeleteServerInternalServerError) WithPayload(payload *models.Error) *DeleteServerInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete server internal server error response
func (o *DeleteServerInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteServerInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
