apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: tconfigs.k8s.taf.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: k8s.taf.io
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            appConfig:
              type: object
              properties:
                app:
                  type: string
                configName:
                  type: string
                configContent:
                  type: string
                updateTime:
                  type: string
                updatePerson:
                  type: string
                updateReason:
                  type: string
              required: [ app,configName,configContent,updateTime,updatePerson,updateReason ]
            serverConfig:
              type: object
              properties:
                app:
                  type: string
                server:
                  type: string
                configName:
                  type: string
                configContent:
                  type: string
                podSeq:
                  type: string
                updateTime:
                  type: string
                updatePerson:
                  type: string
                updateReason:
                  type: string
              required: [ app,server,configName,configContent,updateTime,updatePerson,updateReason ]
          oneOf:
            - required: [ appConfig ]
            - required: [ serverConfig ]
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: tconfigs
    # singular name to be used as an alias on the CLI and for display
    singular: tconfig
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: TConfig
    shortNames:
      - tc
---
apiVersion: k8s.taf.io/v1alpha1
kind: TConfig
metadata:
  name: taf-taflog-session.conf-3
  namespace: taf
serverConfig:
  app: taf
  server: tafnotify
  configName: Session.conf
  configContent: |
    <taf>中国人民大团结万岁,世界人民大团结万岁</taf>