apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: tendpoints.k8s.tars.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: k8s.tars.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                app:
                  type: string
                  pattern: ^[a-zA-Z][a-zA-Z0-9]{0,23}$
                server:
                  type: string
                  pattern: ^[a-zA-Z][a-zA-Z0-9]{1,35}$
                important:
                  type: integer
                  minimum: 1
                  maximum: 20
                  default: 3
                subType:
                  type: string
                  enum: [ tars,dCache,dCacheProxy,dCacheRouter,dCacheDBAccess,normal,external ]
                tars:
                  type: object
                  properties:
                    template:
                      type: string
                      pattern: ^[a-zA-Z][a-zA-Z0-9-.]{1,35}$
                    profile:
                      type: string
                    foreground:
                      type: boolean
                      default: false
                    asyncThread:
                      type: integer
                      minimum: 0
                      maximum: 5
                      default: 1
                    servants:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            pattern: ^[a-zA-Z][a-zA-Z0-9]{0,44}Obj$
                          port:
                            type: integer
                            minimum: 1
                            maximum: 65535
                          thread:
                            type: integer
                            minimum: 1
                            maximum: 16
                            default: 1
                          connection:
                            type: integer
                            minimum: 1
                            maximum: 3000000
                            default: 10000
                          capacity:
                            type: integer
                            minimum: 1
                            maximum: 3000000
                            default: 10000
                          timeout:
                            type: integer
                            minimum: 0
                            maximum: 6000000
                            default: 60000
                          isTars:
                            type: boolean
                            default: true
                          isTcp:
                            type: boolean
                            default: true
                        required: [ name,port ]
                      minItems: 1
                normal:
                  type: object
                  properties:
                    ports:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            pattern: ^[a-zA-Z][a-zA-Z0-9-]{0,44}$
                          port:
                            type: integer
                            minimum: 1
                            maximum: 65535
                          isTcp:
                            type: boolean
                            default: true
                        required: [ name,port ]
                      minItems: 1
                  required: [ ports ]
                dCache:
                  type: boolean
                dCacheDBAccess:
                  type: boolean
                dCacheProxy:
                  type: boolean
                dCacheRouter:
                  type: boolean
                external:
                  type: object
                  properties:
                    upstreams:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            pattern: ^[a-zA-Z][a-zA-Z0-9-]{0,44}$
                          isTcp:
                            type: boolean
                            default: true
                          addresses:
                            type: array
                            items:
                              type: object
                              properties:
                                ip:
                                  type: string
                                port:
                                  type: integer
                              required: [ ip , port ]
                        required: [ name, addresses ]
                  required: [ upstreams ]
                hostPorts:
                  type: array
                  items:
                    type: object
                    properties:
                      nameRef:
                        type: string
                        pattern: ^[a-zA-Z0-9]{1,45}Obj$
                      port:
                        type: integer
                        minimum: 1
                        maximum: 65535
                    required: [ nameRef,port ]
              required: [ app, server, subType ]
              oneOf:
                - required: [ tars ]
                - required: [ dCache ]
                - required: [ dCacheProxy ]
                - required: [ dCacheRouter ]
                - required: [ dCacheDBAccess ]
                - required: [ normal ]
                - required: [ external ]
            status:
              type: object
              properties:
                pods:
                  type: array
                  items:
                    type: object
                    properties:
                      uid:
                        type: string
                        format: uuid
                      name:
                        type: string
                      podIP:
                        type: string
                      hostIP:
                        type: string
                      startTime:
                        type: string
                        format: date-time
                      containerStatuses:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            state:
                              type: object
                              properties:
                                waiting:
                                  type: object
                                  properties:
                                    reason:
                                      type: string
                                    message:
                                      type: string
                                running:
                                  type: object
                                  properties:
                                    startedAt:
                                      type: string
                                terminated:
                                  type: object
                                  properties:
                                    exitCode:
                                      type: integer
                                    signal:
                                      type: integer
                                    reason:
                                      type: string
                                    message:
                                      type: string
                                    startedAt:
                                      type: string
                                    finishedAt:
                                      type: string
                                    containerID:
                                      type: string
                              oneOf:
                                - required: [ waiting ]
                                - required: [ running ]
                                - required: [ terminated ]
                            lastState:
                              type: object
                              properties:
                                waiting:
                                  type: object
                                  properties:
                                    reason:
                                      type: string
                                    message:
                                      type: string
                                running:
                                  type: object
                                  properties:
                                    startedAt:
                                      type: string
                                terminated:
                                  type: object
                                  properties:
                                    exitCode:
                                      type: integer
                                    signal:
                                      type: integer
                                    reason:
                                      type: string
                                    message:
                                      type: string
                                    startedAt:
                                      type: string
                                    finishedAt:
                                      type: string
                                    containerID:
                                      type: string
                            #                              oneOf:
                            #                                - required: [ waiting ]
                            #                                - required: [ running ]
                            #                                - required: [ terminated ]

                            ready:
                              type: boolean
                            restartCount:
                              type: integer
                            image:
                              type: string
                            imageID:
                              type: string
                            containerID:
                              type: string
                            started:
                              type: boolean
                      settingState:
                        type: string
                      presentState:
                        type: string
                      presentMessage:
                        type: string
                      tag:
                        type: string
                    required: [ uid,name,podIP,hostIP,settingState,presentState,presentMessage,tag ]
              required: [ pods ]
      subresources:
        # status enables the status subresource.
        status: { }
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: tendpoints
    # singular name to be used as an alias on the CLI and for display
    singular: tendpoint
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: TEndpoint
    shortNames:
      - te