apiVersion: v1
kind: ServiceAccount
metadata:
  name: tars-tarsnotify
  namespace: {{.Release.Namespace}}
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tars-tarsnotify
  namespace: {{.Release.Namespace}}
rules:
  - apiGroups: [ "" ]
    resources: [ pods ]
    verbs: [ get ,list, watch ]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tars-tarsnotify
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tars-tarsnotify
subjects:
  - kind: ServiceAccount
    name: tars-tarsnotify
    namespace: {{.Release.Namespace}}
---


apiVersion: k8s.tars.io/{{ .Chart.AppVersion }}
kind: TImage
metadata:
  name: tars-tarsnotify
  namespace: {{.Release.Namespace}}
  labels:
    tars.io/ServerApp: tars
    tars.io/ServerName: tarsnotify
imageType: server
releases:
  - id: {{.Values.framework.tag | quote }}
    image: "{{.Values.framework.registry }}/tars.tarsnotify:{{.Values.framework.tag}}"
    {{- if.Values.framework.secret}}
    secret: {{.Values.framework.secret |quote }}
    {{- end}}
{{- include "TImageMerger" (dict "version" .Chart.AppVersion "namespace" .Release.Namespace  "name" "tars-tarsnotify" ) | nindent 2 -}}
{{"\n"}}
---

apiVersion: k8s.tars.io/{{ .Chart.AppVersion }}
kind: TServer
metadata:
  name: tars-tarsnotify
  namespace: {{.Release.Namespace}}
  labels:
    tars.io/ServerApp: tars
    tars.io/ServerName: tarsnotify
    tars.io/SubType: tars
    tars.io/Template: tars.es
spec:
  app: tars
  server: tarsnotify
  subType: tars
  tars:
    template: tars.es
    profile: ""
    servants:
      - name: NotifyObj
        port: 13111
  k8s:
    serviceAccount: tars-tarsnotify
    replicas: 1
    env:
      - name: Namespace
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: PodName
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
    mounts:
      - name: host-log-dir
        source:
          hostPath:
            path: /usr/local/app/tars/app_log
            type: DirectoryOrCreate
        mountPath: /usr/local/app/tars/app_log
        subPathExpr: $(Namespace)/$(PodName)
  release:
    id: {{.Values.framework.tag }}
    image: "{{.Values.framework.registry }}/tars.tarsnotify:{{.Values.framework.tag}}"
    {{- if.Values.framework.secret}}
    secret: {{.Values.framework.secret |quote }}
    {{- end}}
