apiVersion: k8s.tars.io/{{ .Chart.AppVersion }}
kind: TImage
metadata:
  name: tars-tarsstat
  namespace: {{.Release.Namespace}}
  labels:
    tars.io/ServerApp: tars
    tars.io/ServerName: tarsstat
imageType: server
releases:
  - id: {{.Values.framework.tag | quote }}
    image: "{{.Values.framework.registry }}/tars.tarsstat:{{.Values.framework.tag}}"
{{- include "TImageMerger" (dict "version" .Chart.AppVersion "namespace" .Release.Namespace  "name" "tars-tarsstat" ) | nindent 2 -}}
{{"\n"}}
---

apiVersion: k8s.tars.io/{{ .Chart.AppVersion }}
kind: TServer
metadata:
  name: tars-tarsstat
  namespace: {{.Release.Namespace}}
  labels:
    tars.io/ServerApp: tars
    tars.io/ServerName: tarsstat
    tars.io/SubType: tars
    tars.io/Template: tars.es
spec:
  app: tars
  server: tarsstat
  subType: tars
  tars:
    template: tars.es
    profile: |
      <tars>
        <hashmap>
          factor=1.5
          file=hashmap.txt
          insertInterval=5
          maxBlock=200
          minBlock=100
          size=128M
        </hashmap>
      </tars>
    servants:
      - name: StatObj
        port: 17000
  k8s:
    replicas: 1
    env:
      - name: Namespace
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: PodName
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
    mounts:
      - name: host-log-dir
        source:
          hostPath:
            path: /usr/local/app/tars/app_log
            type: DirectoryOrCreate
        mountPath: /usr/local/app/tars/app_log
        subPathExpr: $(Namespace)/$(PodName)
  release:
    id: {{.Values.framework.tag | quote }}
    image: "{{.Values.framework.registry }}/tars.tarsstat:{{.Values.framework.tag}}"
    nodeImage: "{{.Values.framework.registry }}/tars.tarsnode:{{.Values.framework.tag}}"
    {{- if.Values.framework.secret}}
    secret: {{.Values.framework.secret |quote }}
    nodeSecret: {{.Values.framework.secret |quote }}
    {{- end}}
