{{ $tt := lookup  (printf "k8s.tars.io/%s" .Chart.AppVersion) "TTemplate" .Release.Namespace "tars.php" -}}
{{- if not $tt -}}
apiVersion: k8s.tars.io/{{ .Chart.AppVersion }}
kind: TTemplate
metadata:
  name: tars.php
  namespace: {{.Release.Namespace}}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-9"
spec:
  content: |
    <tars>
      <application>
        <server>
          php=/usr/bin/php
          buffer_output_size=12582912
          open_tcp_nodelay=1
          open_eof_check=0
          open_eof_split=0
          task_worker_num=1
          dispatch_mode=2
          daemonize=1
        </server>
      </application>
    </tars>
  parent: tars.default
{{- end }}
