apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ttemplates.k8s.tars.io
spec:
  conversion:
    strategy: None
  group: k8s.tars.io
  names:
    kind: TTemplate
    listKind: TTemplateList
    plural: ttemplates
    shortNames:
      - tt
    singular: ttemplate
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                content:
                  type: string
                  maxLength: 8192
                parent:
                  pattern: ^[a-zA-Z][a-zA-Z0-9-.]{1,35}$
                  type: string
              required:
                - content
                - parent
              type: object
          type: object
      served: true
      storage: true
