apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ttrees.k8s.tars.io
spec:
  conversion:
    strategy: None
  group: k8s.tars.io
  names:
    kind: TTree
    listKind: TTreeList
    plural: ttrees
    singular: ttree
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            apps:
              items:
                properties:
                  name:
                    type: string
                    pattern: ^[a-zA-Z][a-zA-Z0-9]{0,23}$
                  businessRef:
                    type: string
                    pattern: ^([a-zA-Z][a-zA-Z0-9]{0,23}){0,1}$
                  createPerson:
                    type: string
                    pattern: ^[a-zA-Z][a-zA-Z0-9_.-]{0,15}$
                  createTime:
                    type: string
                    format: date-time
                  mark:
                    type: string
                    maxLength: 30
                required:
                  - name
                  - businessRef
                type: object
              type: array
            businesses:
              items:
                properties:
                  name:
                    type: string
                    pattern: ^[a-zA-Z][a-zA-Z0-9]{0,23}$
                  show:
                    type: string
                    minLength: 1
                    maxLength: 30
                  createPerson:
                    type: string
                    pattern: ^[a-zA-Z][a-zA-Z0-9_.-]{0,15}$
                  createTime:
                    type: string
                    format: date-time
                  mark:
                    type: string
                    maxLength: 300
                  weight:
                    type: integer
                    default: 3
                    maximum: 5
                    minimum: 1
                required:
                  - name
                  - show
                  - weight
                type: object
              type: array
          required:
            - businesses
            - apps
          type: object
      served: true
      storage: true
