apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: tars-validating-webhook
webhooks:
  - name: validating.crd.tars.io-0
    admissionReviewVersions: [ v1 ]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURUakNDQWphZ0F3SUJBZ0lKQVBPR1ZENlpIZHMvTUEwR0NTcUdTSWIzRFFFQkN3VUFNRHd4Q3pBSkJnTlYKQkFZVEFrTk9NUTR3REFZRFZRUUlEQVZJZFVKbGFURU9NQXdHQTFVRUJ3d0ZWM1ZvWVc0eERUQUxCZ05WQkFvTQpCSFJoY25Nd0hoY05NakV3T1RFMU1Ea3lNREV4V2hjTk5Ea3dNVE13TURreU1ERXhXakE4TVFzd0NRWURWUVFHCkV3SkRUakVPTUF3R0ExVUVDQXdGU0hWQ1pXa3hEakFNQmdOVkJBY01CVmQxYUdGdU1RMHdDd1lEVlFRS0RBUjAKWVhKek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMXVYeFYvK2FxaXFBSkRhaQp6OVJWTmppYnFIeUxDOGpaRFF6UnlkSkNVTnp1R0ZybWNONTJ2NE10T3cxc3U0Z1NQZUdLQzBTRmthTkV1MmZnClVyZFh3TVAydXF5QTR4allCRUZXMXowOWdlMUV5TTlpM0ZJNG12UkltN3c5YmNrb2NQK1hWbklvVFUwaTJ4eFMKOWlrcU1hdklIV0VqMnJnZThvK3BCQ2NDenYxWi9yNnJubnk0aDYyUW1VeXFXalpmMWdYQm9UaU1HZmZtVUxiLwpSSHZMUWtScEJpUktRdytaalFlRk5uTmxYVjVxOTV1emJjSHl4Z1lZZFZQTm4zZFNVSTFBZ0RQRmNwWWlZZ1RYCndUeThVbW93TSszKzBkYzJnR0ZLOTRaRWIxb2ExTmcwYnh6ZjFLbGRnbUxGOHNVN1dPR1hiYXdkY3JEaStWb1EKUGl1bTd3SURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVU0Sm9SRzkwd0xNM01iWWxLd0o1NEZMSmJRdXN3SHdZRApWUjBqQkJnd0ZvQVU0Sm9SRzkwd0xNM01iWWxLd0o1NEZMSmJRdXN3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOCkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUphVXV4NkpDZGRUOGEvWTk3OG9pQUVWaktIcjBmbnhvb3Y3K1FhOGUKbFEwOGNCSVJVZ0pSaUJxcVhheHEreVNvbWhFQk44dkU3SjB6a3lHeWxjSjJDaWRzOWdGK0R3dVZ5NTlXdGxxYgpwR2ZRQVRwLzZlTjlzd0JuSmtsUFNhanBsV3BtdnZZMTJhSENHOGZHYi9vb3J0cTk4UmplaVM1NmoyQStFTVAyCktnMEVBV0RmMFd1YUpCNzJ3K0tyaldVZUJuS1R4c1ZqTjNNK0NCT2xHQkN5QnQ2NS9EMzd4Ukk1R1VYOGR1WVAKM2IxeENKcW5McWZGYVV1NFRUV0t5WlVIQktVUjI0cUlSNHMzWWpRckZObkRMMmVQZ3JTVmFVMEpoYWR0dmlCZApFVG43ZXl2MVNFWUZaWC82L0FEY2lTTTVFNXhaMUhUMFB5S3l3MG42S2lNU3pBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: tars-webhook-service
        path: /validating
        namespace: tars-system
    sideEffects: None
    timeoutSeconds: 15
    failurePolicy: Fail
    rules:
      - apiGroups: [ k8s.tars.io ]
        apiVersions: [ v1beta2 ]
        operations: [ CREATE,UPDATE,DELETE ]
        resources: [ ttrees,tconfigs,ttemplates,tframeworkconfigs ]
        scope: Namespaced
      - apiGroups: [ k8s.tars.io ]
        apiVersions: [ v1beta2 ]
        operations: [ CREATE, UPDATE ]
        resources: [ tdeploys,tservers,taccounts ]
        scope: Namespaced
  - name: validating.k8s.tars.io-0
    admissionReviewVersions: [ v1 ]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURUakNDQWphZ0F3SUJBZ0lKQVBPR1ZENlpIZHMvTUEwR0NTcUdTSWIzRFFFQkN3VUFNRHd4Q3pBSkJnTlYKQkFZVEFrTk9NUTR3REFZRFZRUUlEQVZJZFVKbGFURU9NQXdHQTFVRUJ3d0ZWM1ZvWVc0eERUQUxCZ05WQkFvTQpCSFJoY25Nd0hoY05NakV3T1RFMU1Ea3lNREV4V2hjTk5Ea3dNVE13TURreU1ERXhXakE4TVFzd0NRWURWUVFHCkV3SkRUakVPTUF3R0ExVUVDQXdGU0hWQ1pXa3hEakFNQmdOVkJBY01CVmQxYUdGdU1RMHdDd1lEVlFRS0RBUjAKWVhKek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMXVYeFYvK2FxaXFBSkRhaQp6OVJWTmppYnFIeUxDOGpaRFF6UnlkSkNVTnp1R0ZybWNONTJ2NE10T3cxc3U0Z1NQZUdLQzBTRmthTkV1MmZnClVyZFh3TVAydXF5QTR4allCRUZXMXowOWdlMUV5TTlpM0ZJNG12UkltN3c5YmNrb2NQK1hWbklvVFUwaTJ4eFMKOWlrcU1hdklIV0VqMnJnZThvK3BCQ2NDenYxWi9yNnJubnk0aDYyUW1VeXFXalpmMWdYQm9UaU1HZmZtVUxiLwpSSHZMUWtScEJpUktRdytaalFlRk5uTmxYVjVxOTV1emJjSHl4Z1lZZFZQTm4zZFNVSTFBZ0RQRmNwWWlZZ1RYCndUeThVbW93TSszKzBkYzJnR0ZLOTRaRWIxb2ExTmcwYnh6ZjFLbGRnbUxGOHNVN1dPR1hiYXdkY3JEaStWb1EKUGl1bTd3SURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVU0Sm9SRzkwd0xNM01iWWxLd0o1NEZMSmJRdXN3SHdZRApWUjBqQkJnd0ZvQVU0Sm9SRzkwd0xNM01iWWxLd0o1NEZMSmJRdXN3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOCkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUphVXV4NkpDZGRUOGEvWTk3OG9pQUVWaktIcjBmbnhvb3Y3K1FhOGUKbFEwOGNCSVJVZ0pSaUJxcVhheHEreVNvbWhFQk44dkU3SjB6a3lHeWxjSjJDaWRzOWdGK0R3dVZ5NTlXdGxxYgpwR2ZRQVRwLzZlTjlzd0JuSmtsUFNhanBsV3BtdnZZMTJhSENHOGZHYi9vb3J0cTk4UmplaVM1NmoyQStFTVAyCktnMEVBV0RmMFd1YUpCNzJ3K0tyaldVZUJuS1R4c1ZqTjNNK0NCT2xHQkN5QnQ2NS9EMzd4Ukk1R1VYOGR1WVAKM2IxeENKcW5McWZGYVV1NFRUV0t5WlVIQktVUjI0cUlSNHMzWWpRckZObkRMMmVQZ3JTVmFVMEpoYWR0dmlCZApFVG43ZXl2MVNFWUZaWC82L0FEY2lTTTVFNXhaMUhUMFB5S3l3MG42S2lNU3pBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: tars-webhook-service
        path: /validating
        namespace: tars-system
    objectSelector:
      matchExpressions:
        - key: tars.io/ServerApp
          operator: Exists
        - key: tars.io/ServerName
          operator: Exists
    sideEffects: None
    timeoutSeconds: 15
    matchPolicy: Exact
    failurePolicy: Fail
    rules:
      - apiGroups: [ "" ]
        apiVersions: [ v1 ]
        resources: [ services ]
        operations: [ CREATE,UPDATE ]
        scope: Namespaced
      - apiGroups: [ apps ]
        apiVersions: [ v1 ]
        resources: [ daemonsets,statefulsets ]
        operations: [ CREATE,UPDATE ]
        scope: Namespaced
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: tars-mutating-webhook
webhooks:
  - name: mutating.crd.tars.io
    admissionReviewVersions: [ v1 ]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURUakNDQWphZ0F3SUJBZ0lKQVBPR1ZENlpIZHMvTUEwR0NTcUdTSWIzRFFFQkN3VUFNRHd4Q3pBSkJnTlYKQkFZVEFrTk9NUTR3REFZRFZRUUlEQVZJZFVKbGFURU9NQXdHQTFVRUJ3d0ZWM1ZvWVc0eERUQUxCZ05WQkFvTQpCSFJoY25Nd0hoY05NakV3T1RFMU1Ea3lNREV4V2hjTk5Ea3dNVE13TURreU1ERXhXakE4TVFzd0NRWURWUVFHCkV3SkRUakVPTUF3R0ExVUVDQXdGU0hWQ1pXa3hEakFNQmdOVkJBY01CVmQxYUdGdU1RMHdDd1lEVlFRS0RBUjAKWVhKek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMXVYeFYvK2FxaXFBSkRhaQp6OVJWTmppYnFIeUxDOGpaRFF6UnlkSkNVTnp1R0ZybWNONTJ2NE10T3cxc3U0Z1NQZUdLQzBTRmthTkV1MmZnClVyZFh3TVAydXF5QTR4allCRUZXMXowOWdlMUV5TTlpM0ZJNG12UkltN3c5YmNrb2NQK1hWbklvVFUwaTJ4eFMKOWlrcU1hdklIV0VqMnJnZThvK3BCQ2NDenYxWi9yNnJubnk0aDYyUW1VeXFXalpmMWdYQm9UaU1HZmZtVUxiLwpSSHZMUWtScEJpUktRdytaalFlRk5uTmxYVjVxOTV1emJjSHl4Z1lZZFZQTm4zZFNVSTFBZ0RQRmNwWWlZZ1RYCndUeThVbW93TSszKzBkYzJnR0ZLOTRaRWIxb2ExTmcwYnh6ZjFLbGRnbUxGOHNVN1dPR1hiYXdkY3JEaStWb1EKUGl1bTd3SURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVU0Sm9SRzkwd0xNM01iWWxLd0o1NEZMSmJRdXN3SHdZRApWUjBqQkJnd0ZvQVU0Sm9SRzkwd0xNM01iWWxLd0o1NEZMSmJRdXN3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOCkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUphVXV4NkpDZGRUOGEvWTk3OG9pQUVWaktIcjBmbnhvb3Y3K1FhOGUKbFEwOGNCSVJVZ0pSaUJxcVhheHEreVNvbWhFQk44dkU3SjB6a3lHeWxjSjJDaWRzOWdGK0R3dVZ5NTlXdGxxYgpwR2ZRQVRwLzZlTjlzd0JuSmtsUFNhanBsV3BtdnZZMTJhSENHOGZHYi9vb3J0cTk4UmplaVM1NmoyQStFTVAyCktnMEVBV0RmMFd1YUpCNzJ3K0tyaldVZUJuS1R4c1ZqTjNNK0NCT2xHQkN5QnQ2NS9EMzd4Ukk1R1VYOGR1WVAKM2IxeENKcW5McWZGYVV1NFRUV0t5WlVIQktVUjI0cUlSNHMzWWpRckZObkRMMmVQZ3JTVmFVMEpoYWR0dmlCZApFVG43ZXl2MVNFWUZaWC82L0FEY2lTTTVFNXhaMUhUMFB5S3l3MG42S2lNU3pBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: tars-webhook-service
        namespace: tars-system
        path: /mutating
    rules:
      - apiGroups: [ k8s.tars.io ]
        apiVersions: [ v1beta2 ]
        operations: [ CREATE,UPDATE ]
        resources: [ tdeploys,tservers,tconfigs,ttrees,taccounts,timages,templates ]
    sideEffects: None
    timeoutSeconds: 15
    failurePolicy: Fail
