apiVersion: k8s.taf.io/v1alpha1
kind: TTemplate
metadata:
  name: taf.default
  namespace: {{.Release.Namespace}}
spec:
  content: |
    <taf>
      <application>
        #是否启用SET分组
        enableset=${enableset}
        #SET分组的全名.(mtt.s.1)
        setdivision=${setdivision}
        <client>
          #地址
          locator =${locator}
          #缺省3s(毫秒)
          sync-invoke-timeout = 3000
          #最大超时时间(毫秒)
          async-invoke-timeout =5000
          #重新获取服务列表时间间隔(毫秒)
          refresh-endpoint-interval = 60000
          #模块间调用[可选]
          stat            = taf.tafstat.StatObj
          #属性上报服务
          property                    = taf.tafproperty.PropertyObj
          #上报间隔时间(毫秒)
          report-interval            = 60000
          #stat采样比1:n 例如sample-rate为1000时 采样比为千分之一
          sample-rate = 100000
          #1分钟内stat最大采样条数
          max-sample-count = 50
          #网络发送线程个数
          sendthread      = 1
          #网络接收线程个数
          recvthread      = 1
          #网络异步回调线程个数
          asyncthread      = ${asyncthread}
          #模块名称
          modulename      = ${modulename}
        </client>

        #定义所有绑定的IP
        <server>
          #应用名称
          app      = ${app}
          #服务名称
          server  = ${server}
          #本地ip
          localip  = ${localip}

          #本地管理套接字[可选]
          local  = ${local}
          #服务的数据目录,可执行文件,配置文件等
          basepath = ${basepath}
          #
          datapath = ${datapath}
          #日志路径
          logpath  = ${logpath}
          #日志大小
          logsize = 10M
          #日志数量
          #   lognum = 10
          #配置中心的地址[可选]
          config  = taf.tafconfig.ConfigObj
          #信息中心的地址[可选]
          notify  = taf.tafnotify.NotifyObj
          #远程LogServer[可选]
          log    = taf.taflog.LogObj
          #关闭服务时等待时间
          deactivating-timeout = 2000
          #是否启用用户级线程切换（默认为0，不启用）
          openthreadcontext = 0
          #用户级线程上下文个数 (openthreadcontext为1时生效,默认10000)
          threadcontextnum  = 10000
    
          #用户级线程上下文栈大小 (openthreadcontext为1时生效,默认32k)
          threadcontextstack = 32768
          #滚动日志等级默认值
          logLevel=DEBUG
        </server>
      </application>
     <log>
       logpath=/usr/local/app/taf/remote_app_log
       logthread=2
     </log>
    </taf>
  parent: taf.default