apiVersion: k8s.taf.io/v1alpha1
kind: TTemplate
metadata:
  name: taf.nodejs
  namespace: {{.Release.Namespace}}
spec:
  content: |
    <taf>
      <application>
        <client>
          #网络异步回调线程个数
          asyncthread = 2
        </client>
      </application>
    </taf>
  parent: taf.default
