apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: tservers.k8s.taf.io
  finalizers:
    - finalizers.tservers.k8s.taf.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: k8s.taf.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                app:
                  type: string
                  pattern: ^[a-zA-Z][a-zA-Z0-9]{0,23}$
                server:
                  type: string
                  pattern: ^[a-zA-Z][a-zA-Z0-9]{1,35}$
                important:
                  type: integer
                  minimum: 1
                  maximum: 20
                  default: 3
                subType:
                  type: string
                  enum: [ taf,dCache,dCacheProxy,dCacheRouter,dCacheDBAccess,normal,external ]
                taf:
                  type: object
                  properties:
                    template:
                      type: string
                      pattern: ^[a-zA-Z][a-zA-Z0-9-.]{1,35}$
                    profile:
                      type: string
                    foreground:
                      type: boolean
                      default: false
                    asyncThread:
                      type: integer
                      minimum: 0
                      maximum: 5
                      default: 1
                    servants:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            pattern: ^[a-zA-Z][a-zA-Z0-9]{0,44}Obj$
                          port:
                            type: integer
                            minimum: 1
                            maximum: 65535
                          thread:
                            type: integer
                            minimum: 1
                            maximum: 16
                            default: 1
                          connection:
                            type: integer
                            minimum: 1
                            maximum: 3000000
                            default: 10000
                          capacity:
                            type: integer
                            minimum: 1
                            maximum: 3000000
                            default: 10000
                          timeout:
                            type: integer
                            minimum: 0
                            maximum: 6000000
                            default: 60000
                          isTaf:
                            type: boolean
                            default: true
                          isTcp:
                            type: boolean
                            default: true
                        required: [ name,port ]
                      minItems: 1
                normal:
                  type: object
                  properties:
                    ports:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            pattern: ^[a-zA-Z][a-zA-Z0-9-]{0,44}$
                          port:
                            type: integer
                            minimum: 1
                            maximum: 65535
                          isTcp:
                            type: boolean
                            default: true
                        required: [ name,port ]
                      minItems: 1
                  required: [ ports ]
                k8s:
                  type: object
                  properties:
                    serviceAccount:
                      type: string
                      pattern: ^[a-zA-Z][a-zA-Z0-9-]{1,47}$
                    env:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            pattern: ^[a-zA-Z][a-zA-Z0-9-_]{1,47}$
                          value:
                            type: string
                            pattern: ^[$a-zA-Z0-9{}/:]{0,180}$
                            required: [ value ]
                          valueFrom:
                            type: object
                            properties:
                              fieldRef:
                                type: object
                                properties:
                                  apiVersion:
                                    type: string
                                  fieldPath:
                                    type: string
                                require: [ fieldPath ]
                              resourceFieldRef:
                                type: object
                                properties:
                                  resource:
                                    type: string
                                  containerName:
                                    type: string
                                  divisor:
                                    x-kubernetes-int-or-string: true
                                require: [ resource ]
                              configMapKeyRef:
                                type: object
                                properties:
                                  name:
                                    type: string
                                    pattern: ^[a-zA-Z][a-zA-Z0-9-]{1,47}$
                                  key:
                                    type: string
                                    pattern: ^[a-zA-Z][a-zA-Z0-9-]{1,47}$
                                  optional:
                                    type: boolean
                                required: [ name,key ]
                              secretKeyRef:
                                type: object
                                properties:
                                  name:
                                    type: string
                                    pattern: ^[a-zA-Z][a-zA-Z0-9-]{1,47}$
                                  key:
                                    type: string
                                    pattern: ^[a-zA-Z][a-zA-Z0-9-]{1,47}$h
                                  optional:
                                    type: boolean
                                required: [ name,key ]
                            oneOf:
                              - required: [ fieldRef ]
                              - required: [ resourceFieldRef ]
                              - required: [ configMapKeyRef ]
                              - required: [ secretKeyRef ]
                        required: [ name ]
                        oneOf:
                          - required: [ value ]
                          - required: [ valueFrom ]
                    envFrom:
                      type: array
                      items:
                        type: object
                        properties:
                          prefix:
                            type: string
                          configMapRef:
                            type: object
                            properties:
                              name:
                                type: string
                                pattern: ^[a-zA-Z][a-zA-Z0-9-]{1,47}$
                              optional:
                                type: boolean
                            required: [ name ]
                          secretRef:
                            type: object
                            properties:
                              name:
                                type: string
                                pattern: ^[a-zA-Z][a-zA-Z0-9-]{1,47}$
                              optional:
                                type: boolean
                            required: [ name ]
                        oneOf:
                          - required: [ configMapRef ]
                          - required: [ secretRef ]
                    hostIPC:
                      type: boolean
                      default: false
                    hostPorts:
                      type: array
                      items:
                        type: object
                        properties:
                          nameRef:
                            type: string
                            pattern: ^[a-zA-Z0-9]{1,45}Obj$
                          port:
                            type: integer
                            minimum: 1
                            maximum: 65535
                        required: [ nameRef,port ]
                    mounts:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            pattern: ^[a-zA-Z][a-zA-Z0-9-]{1,47}$
                          source:
                            type: object
                            properties:
                              hostPath:
                                type: object
                                properties:
                                  path:
                                    type: string
                                    parrent: ^(\/\S+){0,}\S+$
                                  type:
                                    type: string
                                    enum: [ "",DirectoryOrCreate,Directory,FileOrCreate,File,Socket,CharDevice,BlockDevice ]
                                required: [ path ]
                              emptyDir:
                                type: object
                                properties:
                                  medium:
                                    type: string
                                    enum: [ "",Memory,HugePages ]
                                  sizeLimit:
                                    type: integer
                              configMap:
                                type: object
                                properties:
                                  name:
                                    type: string
                                  items:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        key:
                                          type: string
                                        path:
                                          type: string
                                        fsType:
                                          type: string
                                    required: [ key, path ]
                              secret:
                                type: object
                                properties:
                                  name:
                                    type: string
                                  items:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        key:
                                          type: string
                                        path:
                                          type: string
                                        fsType:
                                          type: string
                                    required: [ key, path ]
                                    minItems: 1
                                  defaultMode:
                                    type: integer
                                  optional:
                                    type: boolean
                                required: [ name ]
                              persistentVolumeClaim:
                                type: object
                                properties:
                                  claimName:
                                    type: string
                                  readOnly:
                                    type: boolean
                            oneOf:
                              - required: [ hostPath ]
                              - required: [ emptyDir ]
                              - required: [ configMap ]
                              - required: [ secret ]
                              - required: [ persistentVolumeClaim ]
                              - required: [ downwardAPI ]
                          mountPath:
                            type: string
                            parrent: ^(\/\S+){0,}\S+$
                          readOnly:
                            type: boolean
                          subPath:
                            type: string
                          subPathExpr:
                            type: string
                          mountPropagation:
                            type: string
                            enum: [ None,MountPropagationHostToContainer,MountPropagationBidirectional ]
                        reuired: [ name,source,mountPath ]
                    nodeSelector:
                      type: object
                      properties:
                        nodeBind:
                          type: object
                          properties:
                            values:
                              type: array
                              items:
                                type: string
                              minItems: 1
                          required: [ values ]
                        abilityPool:
                          type: object
                          properties:
                            values:
                              type: array
                              items:
                                type: string
                              maxItems: 0
                        publicPool:
                          type: object
                          properties:
                            values:
                              type: array
                              items:
                                type: string
                              maxItems: 0
                      oneOf:
                        - required: [ nodeBind ]
                        - required: [ publicPool ]
                        - required: [ abilityPool ]
                        - required: [ daemonSet ]
                    notStacked:
                      type: boolean
                      default: false
                    podManagementPolicy:
                      type: string
                      enum: [ OrderedReady,Parallel ]
                      default: Parallel
                    readinessGate:
                      type: string
                      enum: [ "" ,taf.io/active ]
                    replicas:
                      type: integer
                      minimum: 0
                      maximum: 12
                  required: [ replicas,nodeSelector ]
                release:
                  type: object
                  properties:
                    source:
                      type: string
                      pattern: ^[a-zA-Z][a-zA-Z0-9-_]{1,47}$
                    tag:
                      type: string
                      pattern: ^[1-9][0-9]{4,5}$
                    image:
                      type: string
                      pattern: ^([a-zA-Z0-9.:-]{1,}\/){0,}[a-zA-Z0-9.-]{1,120}:[a-zA-Z0-9.]{1,32}$
                    imagePullSecret:
                      type: string
                      pattern: ^([a-zA-Z][a-zA-Z0-9-.]{1,50}){0,1}$
                    serverType:
                      type: string
                      enum: [ "",taf_cpp, taf_java_war, taf_java_jar, taf_node, taf_node8, taf_node10, taf_node_pkg, not_taf ]
                  required: [ source,tag ,image , imagePullSecret]
              required: [ app, server, subType ]
              oneOf:
                - required: [ taf , k8s ]
                - required: [ normal , k8s ]
          required: [ spec ]
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: tservers
    # singular name to be used as an alias on the CLI and for display
    singular: tserver
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: TServer
    shortNames:
      - ts