apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: ttemplates.k8s.taf.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: k8s.taf.io
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                content:
                  type: string
                parent:
                  type: string
                  pattern: ^[a-zA-Z][a-zA-Z0-9-.]{1,35}$
              required: [ content,parent ]
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: ttemplates
    # singular name to be used as an alias on the CLI and for display
    singular: ttemplate
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: TTemplate
    shortNames:
      - tt
