// Code generated by go-swagger; DO NOT EDIT.

package server_option

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DoPreviewTemplateContentHandlerFunc turns a function with the right signature into a do preview template content handler
type DoPreviewTemplateContentHandlerFunc func(DoPreviewTemplateContentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DoPreviewTemplateContentHandlerFunc) Handle(params DoPreviewTemplateContentParams) middleware.Responder {
	return fn(params)
}

// DoPreviewTemplateContentHandler interface for that can handle valid do preview template content params
type DoPreviewTemplateContentHandler interface {
	Handle(DoPreviewTemplateContentParams) middleware.Responder
}

// NewDoPreviewTemplateContent creates a new http.Handler for the do preview template content operation
func NewDoPreviewTemplateContent(ctx *middleware.Context, handler DoPreviewTemplateContentHandler) *DoPreviewTemplateContent {
	return &DoPreviewTemplateContent{Context: ctx, Handler: handler}
}

/*DoPreviewTemplateContent swagger:route GET /servers/options/templates server-option k8s doPreviewTemplateContent

获取合并模板，web=/server_option_template

*/
type DoPreviewTemplateContent struct {
	Context *middleware.Context
	Handler DoPreviewTemplateContentHandler
}

func (o *DoPreviewTemplateContent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDoPreviewTemplateContentParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DoPreviewTemplateContentOKBody do preview template content o k body
//
// swagger:model DoPreviewTemplateContentOKBody
type DoPreviewTemplateContentOKBody struct {

	// result
	Result string `json:"result,omitempty"`
}

// Validate validates this do preview template content o k body
func (o *DoPreviewTemplateContentOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DoPreviewTemplateContentOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DoPreviewTemplateContentOKBody) UnmarshalBinary(b []byte) error {
	var res DoPreviewTemplateContentOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
