apiVersion: v1
kind: ServiceAccount
metadata:
  name: taf-tafregistry
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: taf-tafregistry
rules:
  - apiGroups: [ "" ]
    resources: [ pods/status ]
    verbs: [ patch ]
  - apiGroups: [ k8s.taf.io ]
    resources: [ ttemplates,tendpoints ]
    verbs: [ get ,list, watch ]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: taf-tafregistry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: taf-tafregistry
subjects:
  - kind: ServiceAccount
    name: taf-tafregistry

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: taf-tafregistry
data:
  upchain.conf: |
    <upchain>
        <default>
            #tcp -h 110.110.30.31 -p 8888 -t 60000
            #tcp -h 110.110.30.32 -p 8888 -t 60000
        </default>
        <taf.tafalarm.AlarmObj>
            #tcp -h 110.110.30.34 -p 3327 -t 60000
            #tcp -h 110.110.30.35 -p 3325 -t 60000
        </taf.tafalarm.AlarmObj>
    </upchain>
---

apiVersion: k8s.taf.io/v1alpha1
kind: TRelease
metadata:
  name: taf-tafregistry
  namespace: {{.Release.Namespace}}
spec:
  list:
    - image: {{.Values.global.registry.url}}/taf.tafregistry:10000
      imagePullSecret: taf-image-secret
      tag: "10000"
      serverType: taf_cpp
---

apiVersion: k8s.taf.io/v1alpha1
kind: TServer
metadata:
  name: taf-tafregistry
spec:
  app: taf
  server: tafregistry
  subType: taf
  taf:
    template: taf.cpp
    foreground: true
    servants:
      - name: RegistryObj
        port: 17890
        thread: 3
      - name: QueryObj
        port: 17891
        thread: 3
  k8s:
    replicas: 2
    nodeSelector:
      abilityPool:
        values: [ ]
    serviceAccount: taf-tafregistry
    readinessGate: taf.io/active
    env:
      - name: Namespace
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: PodName
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: PodIP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: ServerApp
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.labels['taf.io/ServerApp']
    mounts:
      - name: host-log-dir
        source:
          hostPath:
            path: /usr/local/app/taf/app_log
            type: DirectoryOrCreate
        mountPath: /usr/local/app/taf/app_log
        subPathExpr: $(Namespace).$(PodName)
      - name: upchain
        source:
          configMap:
            name: taf-tafregistry
        mountPath: /etc/upchain
  release:
    source: taf-tafregistry
    tag: '10000'
    image: {{.Values.global.registry.url}}/taf.tafregistry:10000
    imagePullSecret: taf-image-secret
    serverType: taf_cpp