apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ttrees.k8s.tars.io
  annotations:
    "helm.sh/resource-policy": keep
spec:
  conversion:
    strategy: None
  group: k8s.tars.io
  names:
    kind: TTree
    listKind: TTreeList
    plural: ttrees
    singular: ttree
  scope: Namespaced
  versions:
    - name: v1beta1
      {{- if has "v1beta1" .Values.servers}}
      served: true
      {{- else }}
      served: false
      {{- end }}
      {{- if eq "v1beta1" .Values.storage}}
      storage: true
      {{- else }}
      storage: false
      {{- end }}
      {{- if semverCompare ">=1.19.x" $.Capabilities.KubeVersion.Version }}
      deprecated: true
      deprecationWarning: "k8s.tars.io/v1beta1 TTree is deprecated; please migrate to k8s.tars.io/v1beta3 TTree"
      {{- end}}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apps:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    pattern: ^[A-Za-z][0-9A-Za-z]*$
                    maxLength: 63
                  businessRef:
                    type: string
                    pattern: ^(|[\x21-\x7e\p{Han}]{2,32})$
                  createTime:
                    type: string
                    format: date-time
                  createPerson:
                    type: string
                    maxLength: 100
                  mark:
                    type: string
                    maxLength: 1600
                required: [ name,businessRef ]
            businesses:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    pattern: ^[\x21-\x7e\p{Han}]{2,32}$
                  show:
                    type: string
                    minLength: 1
                    maxLength: 100
                  weight:
                    type: integer
                    minimum: 1
                    maximum: 5
                    default: 3
                  createTime:
                    type: string
                    format: date-time
                  createPerson:
                    type: string
                    maxLength: 100
                  mark:
                    type: string
                    maxLength: 1600
                required: [ name,show,weight ]
          required: [ apps,businesses ]
    - name: v1beta2
      {{- if has "v1beta2" .Values.servers}}
      served: true
      {{- else }}
      served: false
      {{- end }}
      {{- if eq "v1beta2" .Values.storage}}
      storage: true
      {{- else }}
      storage: false
      {{- end }}
      {{- if semverCompare ">=1.19.x" $.Capabilities.KubeVersion.Version }}
      deprecated: true
      deprecationWarning: "k8s.tars.io/v1beta2 TTree is deprecated; please migrate to k8s.tars.io/v1beta3 TTree"
      {{- end}}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apps:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    pattern: ^[A-Za-z][0-9A-Za-z]*$
                    maxLength: 63
                  businessRef:
                    type: string
                    pattern: ^(|[\x21-\x7e\p{Han}]{2,32})$
                  createTime:
                    type: string
                    format: date-time
                  createPerson:
                    type: string
                    maxLength: 100
                  mark:
                    type: string
                    maxLength: 1600
                required: [ name,businessRef ]
            businesses:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    pattern: ^[\x21-\x7e\p{Han}]{2,32}$
                  show:
                    type: string
                    minLength: 1
                    maxLength: 100
                  weight:
                    type: integer
                    minimum: 1
                    maximum: 5
                    default: 3
                  createTime:
                    type: string
                    format: date-time
                  createPerson:
                    type: string
                    maxLength: 100
                  mark:
                    type: string
                    maxLength: 1600
                required: [ name,show,weight ]
          required: [ apps,businesses ]
    - name: v1beta3
      {{- if has "v1beta3" .Values.servers}}
      served: true
      {{- else }}
      served: false
      {{- end }}
      {{- if eq "v1beta3" .Values.storage}}
      storage: true
      {{- else }}
      storage: false
      {{- end }}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apps:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    pattern: ^[A-Za-z][0-9A-Za-z]*$
                    maxLength: 63
                  businessRef:
                    type: string
                    pattern: ^(|[\x21-\x7e\p{Han}]{2,32})$
                  createTime:
                    type: string
                    format: date-time
                  createPerson:
                    type: string
                    maxLength: 100
                  mark:
                    type: string
                    maxLength: 1600
                required: [ name,businessRef ]
            businesses:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    pattern: ^[\x21-\x7e\p{Han}]{2,32}$
                  show:
                    type: string
                    minLength: 1
                    maxLength: 100
                  weight:
                    type: integer
                    minimum: 1
                    maximum: 5
                    default: 3
                  createTime:
                    type: string
                    format: date-time
                  createPerson:
                    type: string
                    maxLength: 100
                  mark:
                    type: string
                    maxLength: 1600
                required: [ name,show,weight ]
          required: [ apps,businesses ]
