// Code generated by go-swagger; DO NOT EDIT.

package shell

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"tafadmin/openapi/models"
)

// SSHPodShellOKCode is the HTTP code returned for type SSHPodShellOK
const SSHPodShellOKCode int = 200

/*SSHPodShellOK OK

swagger:response sshPodShellOK
*/
type SSHPodShellOK struct {

	/*
	  In: Body
	*/
	Payload *SSHPodShellOKBody `json:"body,omitempty"`
}

// NewSSHPodShellOK creates SSHPodShellOK with default headers values
func NewSSHPodShellOK() *SSHPodShellOK {

	return &SSHPodShellOK{}
}

// WithPayload adds the payload to the ssh pod shell o k response
func (o *SSHPodShellOK) WithPayload(payload *SSHPodShellOKBody) *SSHPodShellOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the ssh pod shell o k response
func (o *SSHPodShellOK) SetPayload(payload *SSHPodShellOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SSHPodShellOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SSHPodShellInternalServerErrorCode is the HTTP code returned for type SSHPodShellInternalServerError
const SSHPodShellInternalServerErrorCode int = 500

/*SSHPodShellInternalServerError 内部错误

swagger:response sshPodShellInternalServerError
*/
type SSHPodShellInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSSHPodShellInternalServerError creates SSHPodShellInternalServerError with default headers values
func NewSSHPodShellInternalServerError() *SSHPodShellInternalServerError {

	return &SSHPodShellInternalServerError{}
}

// WithPayload adds the payload to the ssh pod shell internal server error response
func (o *SSHPodShellInternalServerError) WithPayload(payload *models.Error) *SSHPodShellInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the ssh pod shell internal server error response
func (o *SSHPodShellInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SSHPodShellInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
