// Code generated by go-swagger; DO NOT EDIT.

package applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"tarsadmin/openapi/models"
)

// DeleteAppOKCode is the HTTP code returned for type DeleteAppOK
const DeleteAppOKCode int = 200

/*DeleteAppOK OK

swagger:response deleteAppOK
*/
type DeleteAppOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteAppOKBody `json:"body,omitempty"`
}

// NewDeleteAppOK creates DeleteAppOK with default headers values
func NewDeleteAppOK() *DeleteAppOK {

	return &DeleteAppOK{}
}

// WithPayload adds the payload to the delete app o k response
func (o *DeleteAppOK) WithPayload(payload *DeleteAppOKBody) *DeleteAppOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete app o k response
func (o *DeleteAppOK) SetPayload(payload *DeleteAppOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAppOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteAppInternalServerErrorCode is the HTTP code returned for type DeleteAppInternalServerError
const DeleteAppInternalServerErrorCode int = 500

/*DeleteAppInternalServerError 内部错误

swagger:response deleteAppInternalServerError
*/
type DeleteAppInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteAppInternalServerError creates DeleteAppInternalServerError with default headers values
func NewDeleteAppInternalServerError() *DeleteAppInternalServerError {

	return &DeleteAppInternalServerError{}
}

// WithPayload adds the payload to the delete app internal server error response
func (o *DeleteAppInternalServerError) WithPayload(payload *models.Error) *DeleteAppInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete app internal server error response
func (o *DeleteAppInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAppInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
