// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// ArrayString array string
//
// swagger:model ArrayString
type ArrayString []string

// Validate validates this array string
func (m ArrayString) Validate(formats strfmt.Registry) error {
	return nil
}
