// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// MapString map string
//
// swagger:model MapString
type MapString map[string]string

// Validate validates this map string
func (m MapString) Validate(formats strfmt.Registry) error {
	return nil
}
