// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NodeSelectorElem node selector elem
//
// swagger:model NodeSelectorElem
type NodeSelectorElem struct {

	// 如果 Kind 为 NodeBind  则值为 NodeName 数组； 如果 Kind 为 AbilityPool 或   PublicPool ,则此值为空
	Value []string `json:"Value"`
}

// Validate validates this node selector elem
func (m *NodeSelectorElem) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NodeSelectorElem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NodeSelectorElem) UnmarshalBinary(b []byte) error {
	var res NodeSelectorElem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
