// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServerElem server elem
//
// swagger:model ServerElem
type ServerElem struct {

	// server Id
	ServerID string `json:"ServerId,omitempty"`

	// server name
	ServerName string `json:"ServerName,omitempty"`
}

// Validate validates this server elem
func (m *ServerElem) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServerElem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServerElem) UnmarshalBinary(b []byte) error {
	var res ServerElem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
