// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"tarsadmin/openapi/models"
)

// CreateServerConfigHandlerFunc turns a function with the right signature into a create server config handler
type CreateServerConfigHandlerFunc func(CreateServerConfigParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateServerConfigHandlerFunc) Handle(params CreateServerConfigParams) middleware.Responder {
	return fn(params)
}

// CreateServerConfigHandler interface for that can handle valid create server config params
type CreateServerConfigHandler interface {
	Handle(CreateServerConfigParams) middleware.Responder
}

// NewCreateServerConfig creates a new http.Handler for the create server config operation
func NewCreateServerConfig(ctx *middleware.Context, handler CreateServerConfigHandler) *CreateServerConfig {
	return &CreateServerConfig{Context: ctx, Handler: handler}
}

/*CreateServerConfig swagger:route POST /configs config k8s createServerConfig

创建配置，web=/server_config_create

*/
type CreateServerConfig struct {
	Context *middleware.Context
	Handler CreateServerConfigHandler
}

func (o *CreateServerConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateServerConfigParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CreateServerConfigBody create server config body
//
// swagger:model CreateServerConfigBody
type CreateServerConfigBody struct {

	// metadata
	Metadata *models.ConfigMeta `json:"metadata,omitempty"`
}

// Validate validates this create server config body
func (o *CreateServerConfigBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateServerConfigBody) validateMetadata(formats strfmt.Registry) error {

	if swag.IsZero(o.Metadata) { // not required
		return nil
	}

	if o.Metadata != nil {
		if err := o.Metadata.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Params" + "." + "metadata")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateServerConfigBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateServerConfigBody) UnmarshalBinary(b []byte) error {
	var res CreateServerConfigBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// CreateServerConfigOKBody create server config o k body
//
// swagger:model CreateServerConfigOKBody
type CreateServerConfigOKBody struct {

	// result
	Result int32 `json:"result,omitempty"`
}

// Validate validates this create server config o k body
func (o *CreateServerConfigOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateServerConfigOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateServerConfigOKBody) UnmarshalBinary(b []byte) error {
	var res CreateServerConfigOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
