// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteServerConfigHistoryHandlerFunc turns a function with the right signature into a delete server config history handler
type DeleteServerConfigHistoryHandlerFunc func(DeleteServerConfigHistoryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteServerConfigHistoryHandlerFunc) Handle(params DeleteServerConfigHistoryParams) middleware.Responder {
	return fn(params)
}

// DeleteServerConfigHistoryHandler interface for that can handle valid delete server config history params
type DeleteServerConfigHistoryHandler interface {
	Handle(DeleteServerConfigHistoryParams) middleware.Responder
}

// NewDeleteServerConfigHistory creates a new http.Handler for the delete server config history operation
func NewDeleteServerConfigHistory(ctx *middleware.Context, handler DeleteServerConfigHistoryHandler) *DeleteServerConfigHistory {
	return &DeleteServerConfigHistory{Context: ctx, Handler: handler}
}

/*DeleteServerConfigHistory swagger:route DELETE /configs/versions config k8s deleteServerConfigHistory

删除历史配置，web=/server_config_history_delete

*/
type DeleteServerConfigHistory struct {
	Context *middleware.Context
	Handler DeleteServerConfigHistoryHandler
}

func (o *DeleteServerConfigHistory) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteServerConfigHistoryParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteServerConfigHistoryBody delete server config history body
//
// swagger:model DeleteServerConfigHistoryBody
type DeleteServerConfigHistoryBody struct {

	// metadata
	Metadata *DeleteServerConfigHistoryParamsBodyMetadata `json:"metadata,omitempty"`
}

// Validate validates this delete server config history body
func (o *DeleteServerConfigHistoryBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteServerConfigHistoryBody) validateMetadata(formats strfmt.Registry) error {

	if swag.IsZero(o.Metadata) { // not required
		return nil
	}

	if o.Metadata != nil {
		if err := o.Metadata.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Params" + "." + "metadata")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteServerConfigHistoryBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteServerConfigHistoryBody) UnmarshalBinary(b []byte) error {
	var res DeleteServerConfigHistoryBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// DeleteServerConfigHistoryOKBody delete server config history o k body
//
// swagger:model DeleteServerConfigHistoryOKBody
type DeleteServerConfigHistoryOKBody struct {

	// result
	Result int32 `json:"result,omitempty"`
}

// Validate validates this delete server config history o k body
func (o *DeleteServerConfigHistoryOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteServerConfigHistoryOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteServerConfigHistoryOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteServerConfigHistoryOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// DeleteServerConfigHistoryParamsBodyMetadata delete server config history params body metadata
//
// swagger:model DeleteServerConfigHistoryParamsBodyMetadata
type DeleteServerConfigHistoryParamsBodyMetadata struct {

	// history Id
	HistoryID string `json:"HistoryId,omitempty"`
}

// Validate validates this delete server config history params body metadata
func (o *DeleteServerConfigHistoryParamsBodyMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteServerConfigHistoryParamsBodyMetadata) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteServerConfigHistoryParamsBodyMetadata) UnmarshalBinary(b []byte) error {
	var res DeleteServerConfigHistoryParamsBodyMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
