// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"tarsadmin/openapi/models"
)

// DeleteServerConfigOKCode is the HTTP code returned for type DeleteServerConfigOK
const DeleteServerConfigOKCode int = 200

/*DeleteServerConfigOK OK

swagger:response deleteServerConfigOK
*/
type DeleteServerConfigOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteServerConfigOKBody `json:"body,omitempty"`
}

// NewDeleteServerConfigOK creates DeleteServerConfigOK with default headers values
func NewDeleteServerConfigOK() *DeleteServerConfigOK {

	return &DeleteServerConfigOK{}
}

// WithPayload adds the payload to the delete server config o k response
func (o *DeleteServerConfigOK) WithPayload(payload *DeleteServerConfigOKBody) *DeleteServerConfigOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete server config o k response
func (o *DeleteServerConfigOK) SetPayload(payload *DeleteServerConfigOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteServerConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteServerConfigInternalServerErrorCode is the HTTP code returned for type DeleteServerConfigInternalServerError
const DeleteServerConfigInternalServerErrorCode int = 500

/*DeleteServerConfigInternalServerError 内部错误

swagger:response deleteServerConfigInternalServerError
*/
type DeleteServerConfigInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteServerConfigInternalServerError creates DeleteServerConfigInternalServerError with default headers values
func NewDeleteServerConfigInternalServerError() *DeleteServerConfigInternalServerError {

	return &DeleteServerConfigInternalServerError{}
}

// WithPayload adds the payload to the delete server config internal server error response
func (o *DeleteServerConfigInternalServerError) WithPayload(payload *models.Error) *DeleteServerConfigInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete server config internal server error response
func (o *DeleteServerConfigInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteServerConfigInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
