// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"tarsadmin/openapi/models"
)

// DeleteServerConfigHistoryOKCode is the HTTP code returned for type DeleteServerConfigHistoryOK
const DeleteServerConfigHistoryOKCode int = 200

/*DeleteServerConfigHistoryOK OK

swagger:response deleteServerConfigHistoryOK
*/
type DeleteServerConfigHistoryOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteServerConfigHistoryOKBody `json:"body,omitempty"`
}

// NewDeleteServerConfigHistoryOK creates DeleteServerConfigHistoryOK with default headers values
func NewDeleteServerConfigHistoryOK() *DeleteServerConfigHistoryOK {

	return &DeleteServerConfigHistoryOK{}
}

// WithPayload adds the payload to the delete server config history o k response
func (o *DeleteServerConfigHistoryOK) WithPayload(payload *DeleteServerConfigHistoryOKBody) *DeleteServerConfigHistoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete server config history o k response
func (o *DeleteServerConfigHistoryOK) SetPayload(payload *DeleteServerConfigHistoryOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteServerConfigHistoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteServerConfigHistoryInternalServerErrorCode is the HTTP code returned for type DeleteServerConfigHistoryInternalServerError
const DeleteServerConfigHistoryInternalServerErrorCode int = 500

/*DeleteServerConfigHistoryInternalServerError 内部错误

swagger:response deleteServerConfigHistoryInternalServerError
*/
type DeleteServerConfigHistoryInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteServerConfigHistoryInternalServerError creates DeleteServerConfigHistoryInternalServerError with default headers values
func NewDeleteServerConfigHistoryInternalServerError() *DeleteServerConfigHistoryInternalServerError {

	return &DeleteServerConfigHistoryInternalServerError{}
}

// WithPayload adds the payload to the delete server config history internal server error response
func (o *DeleteServerConfigHistoryInternalServerError) WithPayload(payload *models.Error) *DeleteServerConfigHistoryInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete server config history internal server error response
func (o *DeleteServerConfigHistoryInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteServerConfigHistoryInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
