// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewDoActiveHistoryConfigParams creates a new DoActiveHistoryConfigParams object
// no default values defined in spec.
func NewDoActiveHistoryConfigParams() DoActiveHistoryConfigParams {

	return DoActiveHistoryConfigParams{}
}

// DoActiveHistoryConfigParams contains all the bound params for the do active history config operation
// typically these are obtained from a http.Request
//
// swagger:parameters doActiveHistoryConfig
type DoActiveHistoryConfigParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	Params DoActiveHistoryConfigBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDoActiveHistoryConfigParams() beforehand.
func (o *DoActiveHistoryConfigParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body DoActiveHistoryConfigBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("params", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Params = body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
