// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
)

// DoPreviewConfigContentURL generates an URL for the do preview config content operation
type DoPreviewConfigContentURL struct {
	ConfigName *string
	PodSeq     *string
	ServerApp  *string
	ServerName *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DoPreviewConfigContentURL) WithBasePath(bp string) *DoPreviewConfigContentURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DoPreviewConfigContentURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *DoPreviewConfigContentURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/configs/join"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/admin/v1alpha1/"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var configNameQ string
	if o.ConfigName != nil {
		configNameQ = *o.ConfigName
	}
	if configNameQ != "" {
		qs.Set("ConfigName", configNameQ)
	}

	var podSeqQ string
	if o.PodSeq != nil {
		podSeqQ = *o.PodSeq
	}
	if podSeqQ != "" {
		qs.Set("PodSeq", podSeqQ)
	}

	var serverAppQ string
	if o.ServerApp != nil {
		serverAppQ = *o.ServerApp
	}
	if serverAppQ != "" {
		qs.Set("ServerApp", serverAppQ)
	}

	var serverNameQ string
	if o.ServerName != nil {
		serverNameQ = *o.ServerName
	}
	if serverNameQ != "" {
		qs.Set("ServerName", serverNameQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *DoPreviewConfigContentURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *DoPreviewConfigContentURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *DoPreviewConfigContentURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on DoPreviewConfigContentURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on DoPreviewConfigContentURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *DoPreviewConfigContentURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
