// Code generated by go-swagger; DO NOT EDIT.

package business

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"tarsadmin/openapi/models"
)

// CreateBusinessOKCode is the HTTP code returned for type CreateBusinessOK
const CreateBusinessOKCode int = 200

/*CreateBusinessOK OK

swagger:response createBusinessOK
*/
type CreateBusinessOK struct {

	/*
	  In: Body
	*/
	Payload *CreateBusinessOKBody `json:"body,omitempty"`
}

// NewCreateBusinessOK creates CreateBusinessOK with default headers values
func NewCreateBusinessOK() *CreateBusinessOK {

	return &CreateBusinessOK{}
}

// WithPayload adds the payload to the create business o k response
func (o *CreateBusinessOK) WithPayload(payload *CreateBusinessOKBody) *CreateBusinessOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create business o k response
func (o *CreateBusinessOK) SetPayload(payload *CreateBusinessOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBusinessOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateBusinessInternalServerErrorCode is the HTTP code returned for type CreateBusinessInternalServerError
const CreateBusinessInternalServerErrorCode int = 500

/*CreateBusinessInternalServerError 内部错误

swagger:response createBusinessInternalServerError
*/
type CreateBusinessInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateBusinessInternalServerError creates CreateBusinessInternalServerError with default headers values
func NewCreateBusinessInternalServerError() *CreateBusinessInternalServerError {

	return &CreateBusinessInternalServerError{}
}

// WithPayload adds the payload to the create business internal server error response
func (o *CreateBusinessInternalServerError) WithPayload(payload *models.Error) *CreateBusinessInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create business internal server error response
func (o *CreateBusinessInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBusinessInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
