// Code generated by go-swagger; DO NOT EDIT.

package business

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeleteBusinessHandlerFunc turns a function with the right signature into a delete business handler
type DeleteBusinessHandlerFunc func(DeleteBusinessParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteBusinessHandlerFunc) Handle(params DeleteBusinessParams) middleware.Responder {
	return fn(params)
}

// DeleteBusinessHandler interface for that can handle valid delete business params
type DeleteBusinessHandler interface {
	Handle(DeleteBusinessParams) middleware.Responder
}

// NewDeleteBusiness creates a new http.Handler for the delete business operation
func NewDeleteBusiness(ctx *middleware.Context, handler DeleteBusinessHandler) *DeleteBusiness {
	return &DeleteBusiness{Context: ctx, Handler: handler}
}

/*DeleteBusiness swagger:route DELETE /businesses business k8s deleteBusiness

删除业务列表，web=/business_delete

*/
type DeleteBusiness struct {
	Context *middleware.Context
	Handler DeleteBusinessHandler
}

func (o *DeleteBusiness) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteBusinessParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteBusinessBody delete business body
//
// swagger:model DeleteBusinessBody
type DeleteBusinessBody struct {

	// metadata
	Metadata *DeleteBusinessParamsBodyMetadata `json:"metadata,omitempty"`
}

// Validate validates this delete business body
func (o *DeleteBusinessBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteBusinessBody) validateMetadata(formats strfmt.Registry) error {

	if swag.IsZero(o.Metadata) { // not required
		return nil
	}

	if o.Metadata != nil {
		if err := o.Metadata.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Params" + "." + "metadata")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteBusinessBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteBusinessBody) UnmarshalBinary(b []byte) error {
	var res DeleteBusinessBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// DeleteBusinessOKBody delete business o k body
//
// swagger:model DeleteBusinessOKBody
type DeleteBusinessOKBody struct {

	// result
	Result int32 `json:"result,omitempty"`
}

// Validate validates this delete business o k body
func (o *DeleteBusinessOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteBusinessOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteBusinessOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteBusinessOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// DeleteBusinessParamsBodyMetadata delete business params body metadata
//
// swagger:model DeleteBusinessParamsBodyMetadata
type DeleteBusinessParamsBodyMetadata struct {

	// business name
	// Required: true
	// Pattern: ^[a-zA-Z0-9.:_-]{1,128}\z
	BusinessName *string `json:"BusinessName"`
}

// Validate validates this delete business params body metadata
func (o *DeleteBusinessParamsBodyMetadata) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBusinessName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteBusinessParamsBodyMetadata) validateBusinessName(formats strfmt.Registry) error {

	if err := validate.Required("Params"+"."+"metadata"+"."+"BusinessName", "body", o.BusinessName); err != nil {
		return err
	}

	if err := validate.Pattern("Params"+"."+"metadata"+"."+"BusinessName", "body", string(*o.BusinessName), `^[a-zA-Z0-9.:_-]{1,128}\z`); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteBusinessParamsBodyMetadata) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteBusinessParamsBodyMetadata) UnmarshalBinary(b []byte) error {
	var res DeleteBusinessParamsBodyMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
