// Code generated by go-swagger; DO NOT EDIT.

package business

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"tafadmin/openapi/models"
)

// DeleteBusinessOKCode is the HTTP code returned for type DeleteBusinessOK
const DeleteBusinessOKCode int = 200

/*DeleteBusinessOK OK

swagger:response deleteBusinessOK
*/
type DeleteBusinessOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteBusinessOKBody `json:"body,omitempty"`
}

// NewDeleteBusinessOK creates DeleteBusinessOK with default headers values
func NewDeleteBusinessOK() *DeleteBusinessOK {

	return &DeleteBusinessOK{}
}

// WithPayload adds the payload to the delete business o k response
func (o *DeleteBusinessOK) WithPayload(payload *DeleteBusinessOKBody) *DeleteBusinessOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete business o k response
func (o *DeleteBusinessOK) SetPayload(payload *DeleteBusinessOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBusinessOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteBusinessInternalServerErrorCode is the HTTP code returned for type DeleteBusinessInternalServerError
const DeleteBusinessInternalServerErrorCode int = 500

/*DeleteBusinessInternalServerError 内部错误

swagger:response deleteBusinessInternalServerError
*/
type DeleteBusinessInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteBusinessInternalServerError creates DeleteBusinessInternalServerError with default headers values
func NewDeleteBusinessInternalServerError() *DeleteBusinessInternalServerError {

	return &DeleteBusinessInternalServerError{}
}

// WithPayload adds the payload to the delete business internal server error response
func (o *DeleteBusinessInternalServerError) WithPayload(payload *models.Error) *DeleteBusinessInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete business internal server error response
func (o *DeleteBusinessInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBusinessInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
