// Code generated by go-swagger; DO NOT EDIT.

package business

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDoListBusinessAppParams creates a new DoListBusinessAppParams object
// no default values defined in spec.
func NewDoListBusinessAppParams() DoListBusinessAppParams {

	return DoListBusinessAppParams{}
}

// DoListBusinessAppParams contains all the bound params for the do list business app operation
// typically these are obtained from a http.Request
//
// swagger:parameters doListBusinessApp
type DoListBusinessAppParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*json.encode([]string)
	  In: query
	*/
	BusinessName *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDoListBusinessAppParams() beforehand.
func (o *DoListBusinessAppParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qBusinessName, qhkBusinessName, _ := qs.GetOK("BusinessName")
	if err := o.bindBusinessName(qBusinessName, qhkBusinessName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindBusinessName binds and validates parameter BusinessName from query.
func (o *DoListBusinessAppParams) bindBusinessName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.BusinessName = &raw

	return nil
}
