// Code generated by go-swagger; DO NOT EDIT.

package business

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"tarsadmin/openapi/models"
)

// SelectBusinessOKCode is the HTTP code returned for type SelectBusinessOK
const SelectBusinessOKCode int = 200

/*SelectBusinessOK OK

swagger:response selectBusinessOK
*/
type SelectBusinessOK struct {

	/*
	  In: Body
	*/
	Payload *models.SelectResult `json:"body,omitempty"`
}

// NewSelectBusinessOK creates SelectBusinessOK with default headers values
func NewSelectBusinessOK() *SelectBusinessOK {

	return &SelectBusinessOK{}
}

// WithPayload adds the payload to the select business o k response
func (o *SelectBusinessOK) WithPayload(payload *models.SelectResult) *SelectBusinessOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the select business o k response
func (o *SelectBusinessOK) SetPayload(payload *models.SelectResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SelectBusinessOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SelectBusinessInternalServerErrorCode is the HTTP code returned for type SelectBusinessInternalServerError
const SelectBusinessInternalServerErrorCode int = 500

/*SelectBusinessInternalServerError 内部错误

swagger:response selectBusinessInternalServerError
*/
type SelectBusinessInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSelectBusinessInternalServerError creates SelectBusinessInternalServerError with default headers values
func NewSelectBusinessInternalServerError() *SelectBusinessInternalServerError {

	return &SelectBusinessInternalServerError{}
}

// WithPayload adds the payload to the select business internal server error response
func (o *SelectBusinessInternalServerError) WithPayload(payload *models.Error) *SelectBusinessInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the select business internal server error response
func (o *SelectBusinessInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SelectBusinessInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
