// Code generated by go-swagger; DO NOT EDIT.

package affinity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DoDeleteNodeEnableServerHandlerFunc turns a function with the right signature into a do delete node enable server handler
type DoDeleteNodeEnableServerHandlerFunc func(DoDeleteNodeEnableServerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DoDeleteNodeEnableServerHandlerFunc) Handle(params DoDeleteNodeEnableServerParams) middleware.Responder {
	return fn(params)
}

// DoDeleteNodeEnableServerHandler interface for that can handle valid do delete node enable server params
type DoDeleteNodeEnableServerHandler interface {
	Handle(DoDeleteNodeEnableServerParams) middleware.Responder
}

// NewDoDeleteNodeEnableServer creates a new http.Handler for the do delete node enable server operation
func NewDoDeleteNodeEnableServer(ctx *middleware.Context, handler DoDeleteNodeEnableServerHandler) *DoDeleteNodeEnableServer {
	return &DoDeleteNodeEnableServer{Context: ctx, Handler: handler}
}

/*DoDeleteNodeEnableServer swagger:route DELETE /affinities/nodes affinity k8s doDeleteNodeEnableServer

Node禁止部署的服务，web=/affinity_del_server

*/
type DoDeleteNodeEnableServer struct {
	Context *middleware.Context
	Handler DoDeleteNodeEnableServerHandler
}

func (o *DoDeleteNodeEnableServer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDoDeleteNodeEnableServerParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DoDeleteNodeEnableServerBody do delete node enable server body
//
// swagger:model DoDeleteNodeEnableServerBody
type DoDeleteNodeEnableServerBody struct {

	// metadata
	Metadata *DoDeleteNodeEnableServerParamsBodyMetadata `json:"metadata,omitempty"`
}

// Validate validates this do delete node enable server body
func (o *DoDeleteNodeEnableServerBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DoDeleteNodeEnableServerBody) validateMetadata(formats strfmt.Registry) error {

	if swag.IsZero(o.Metadata) { // not required
		return nil
	}

	if o.Metadata != nil {
		if err := o.Metadata.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Params" + "." + "metadata")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DoDeleteNodeEnableServerBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DoDeleteNodeEnableServerBody) UnmarshalBinary(b []byte) error {
	var res DoDeleteNodeEnableServerBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// DoDeleteNodeEnableServerOKBody do delete node enable server o k body
//
// swagger:model DoDeleteNodeEnableServerOKBody
type DoDeleteNodeEnableServerOKBody struct {

	// result
	Result int32 `json:"result,omitempty"`
}

// Validate validates this do delete node enable server o k body
func (o *DoDeleteNodeEnableServerOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DoDeleteNodeEnableServerOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DoDeleteNodeEnableServerOKBody) UnmarshalBinary(b []byte) error {
	var res DoDeleteNodeEnableServerOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// DoDeleteNodeEnableServerParamsBodyMetadata do delete node enable server params body metadata
//
// swagger:model DoDeleteNodeEnableServerParamsBodyMetadata
type DoDeleteNodeEnableServerParamsBodyMetadata struct {

	// node name
	NodeName string `json:"NodeName,omitempty"`

	// server app
	ServerApp []string `json:"ServerApp"`
}

// Validate validates this do delete node enable server params body metadata
func (o *DoDeleteNodeEnableServerParamsBodyMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DoDeleteNodeEnableServerParamsBodyMetadata) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DoDeleteNodeEnableServerParamsBodyMetadata) UnmarshalBinary(b []byte) error {
	var res DoDeleteNodeEnableServerParamsBodyMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
