// Code generated by go-swagger; DO NOT EDIT.

package affinity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"tarsadmin/openapi/models"
)

// DoListAffinityGroupByNodeOKCode is the HTTP code returned for type DoListAffinityGroupByNodeOK
const DoListAffinityGroupByNodeOKCode int = 200

/*DoListAffinityGroupByNodeOK OK

swagger:response doListAffinityGroupByNodeOK
*/
type DoListAffinityGroupByNodeOK struct {

	/*
	  In: Body
	*/
	Payload *models.SelectResult `json:"body,omitempty"`
}

// NewDoListAffinityGroupByNodeOK creates DoListAffinityGroupByNodeOK with default headers values
func NewDoListAffinityGroupByNodeOK() *DoListAffinityGroupByNodeOK {

	return &DoListAffinityGroupByNodeOK{}
}

// WithPayload adds the payload to the do list affinity group by node o k response
func (o *DoListAffinityGroupByNodeOK) WithPayload(payload *models.SelectResult) *DoListAffinityGroupByNodeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the do list affinity group by node o k response
func (o *DoListAffinityGroupByNodeOK) SetPayload(payload *models.SelectResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DoListAffinityGroupByNodeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DoListAffinityGroupByNodeInternalServerErrorCode is the HTTP code returned for type DoListAffinityGroupByNodeInternalServerError
const DoListAffinityGroupByNodeInternalServerErrorCode int = 500

/*DoListAffinityGroupByNodeInternalServerError 内部错误

swagger:response doListAffinityGroupByNodeInternalServerError
*/
type DoListAffinityGroupByNodeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDoListAffinityGroupByNodeInternalServerError creates DoListAffinityGroupByNodeInternalServerError with default headers values
func NewDoListAffinityGroupByNodeInternalServerError() *DoListAffinityGroupByNodeInternalServerError {

	return &DoListAffinityGroupByNodeInternalServerError{}
}

// WithPayload adds the payload to the do list affinity group by node internal server error response
func (o *DoListAffinityGroupByNodeInternalServerError) WithPayload(payload *models.Error) *DoListAffinityGroupByNodeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the do list affinity group by node internal server error response
func (o *DoListAffinityGroupByNodeInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DoListAffinityGroupByNodeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
