// Code generated by go-swagger; DO NOT EDIT.

package node

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"tafadmin/openapi/models"
)

// DoListClusterNodeOKCode is the HTTP code returned for type DoListClusterNodeOK
const DoListClusterNodeOKCode int = 200

/*DoListClusterNodeOK OK

swagger:response doListClusterNodeOK
*/
type DoListClusterNodeOK struct {

	/*
	  In: Body
	*/
	Payload *DoListClusterNodeOKBody `json:"body,omitempty"`
}

// NewDoListClusterNodeOK creates DoListClusterNodeOK with default headers values
func NewDoListClusterNodeOK() *DoListClusterNodeOK {

	return &DoListClusterNodeOK{}
}

// WithPayload adds the payload to the do list cluster node o k response
func (o *DoListClusterNodeOK) WithPayload(payload *DoListClusterNodeOKBody) *DoListClusterNodeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the do list cluster node o k response
func (o *DoListClusterNodeOK) SetPayload(payload *DoListClusterNodeOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DoListClusterNodeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DoListClusterNodeInternalServerErrorCode is the HTTP code returned for type DoListClusterNodeInternalServerError
const DoListClusterNodeInternalServerErrorCode int = 500

/*DoListClusterNodeInternalServerError 内部错误

swagger:response doListClusterNodeInternalServerError
*/
type DoListClusterNodeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDoListClusterNodeInternalServerError creates DoListClusterNodeInternalServerError with default headers values
func NewDoListClusterNodeInternalServerError() *DoListClusterNodeInternalServerError {

	return &DoListClusterNodeInternalServerError{}
}

// WithPayload adds the payload to the do list cluster node internal server error response
func (o *DoListClusterNodeInternalServerError) WithPayload(payload *models.Error) *DoListClusterNodeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the do list cluster node internal server error response
func (o *DoListClusterNodeInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DoListClusterNodeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
