// Code generated by go-swagger; DO NOT EDIT.

package deploy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"tarsadmin/openapi/models"
)

// CreateDeployOKCode is the HTTP code returned for type CreateDeployOK
const CreateDeployOKCode int = 200

/*CreateDeployOK OK

swagger:response createDeployOK
*/
type CreateDeployOK struct {

	/*
	  In: Body
	*/
	Payload *CreateDeployOKBody `json:"body,omitempty"`
}

// NewCreateDeployOK creates CreateDeployOK with default headers values
func NewCreateDeployOK() *CreateDeployOK {

	return &CreateDeployOK{}
}

// WithPayload adds the payload to the create deploy o k response
func (o *CreateDeployOK) WithPayload(payload *CreateDeployOKBody) *CreateDeployOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create deploy o k response
func (o *CreateDeployOK) SetPayload(payload *CreateDeployOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateDeployOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateDeployInternalServerErrorCode is the HTTP code returned for type CreateDeployInternalServerError
const CreateDeployInternalServerErrorCode int = 500

/*CreateDeployInternalServerError 内部错误

swagger:response createDeployInternalServerError
*/
type CreateDeployInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateDeployInternalServerError creates CreateDeployInternalServerError with default headers values
func NewCreateDeployInternalServerError() *CreateDeployInternalServerError {

	return &CreateDeployInternalServerError{}
}

// WithPayload adds the payload to the create deploy internal server error response
func (o *CreateDeployInternalServerError) WithPayload(payload *models.Error) *CreateDeployInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create deploy internal server error response
func (o *CreateDeployInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateDeployInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
