apiVersion: k8s.taf.io/v1alpha1
kind: TRelease
metadata:
  name: taf-tafconfig
  namespace: {{.Release.Namespace}}
spec:
  list:
    - image: {{.Values.global.registry.url}}/taf.tafconfig:10000
      imagePullSecret: taf-image-secret
      tag: "10000"
      serverType: taf_cpp
---

apiVersion: k8s.taf.io/v1alpha1
kind: TServer
metadata:
  name: taf-tafconfig
  namespace: {{.Release.Namespace}}
  labels:
    taf.io/ReleaseSource: taf-tafconfig
    taf.io/ReleaseTag: "10000"
    taf.io/ServerApp: taf
    taf.io/ServerName: tafconfig
    taf.io/SubType: taf
    taf.io/Template: taf.default
spec:
  app: taf
  server: tafconfig
  subType: taf
  taf:
    template: taf.cpp
    profile: |
      <taf>
        <application>
          <server>
            #log = taf.taflog4other.LogObj
            logLevel = DEBUG
          </server>
          </application>
          <db>
            charset=utf8
            dbhost={{ .Values.tafDB.host }}
            dbport={{ .Values.tafDB.port }}
            dbname={{ .Values.tafDB.name }}
            dbuser={{ .Values.tafDB.user }}
            dbpass={{ .Values.tafDB.password }}
          </db>
      </taf>
    servants:
      - name: ConfigObj
        port: 10000
  k8s:
    replicas: 1
    nodeSelector:
      abilityPool:
        values: [ ]
    env:
      - name: Namespace
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: PodName
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: PodIP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: ServerApp
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.labels['taf.io/ServerApp']
    mounts:
      - name: host-log-dir
        source:
          hostPath:
            path: /usr/local/app/taf/app_log
            type: DirectoryOrCreate
        mountPath: /usr/local/app/taf/app_log
        subPathExpr: $(Namespace).$(PodName)
    readinessGate: taf.io/active
  release:
    source: taf-tafconfig
    tag: '10000'
    image: {{.Values.global.registry.url}}/taf.tafconfig:10000
    imagePullSecret: taf-image-secret
    serverType: taf_cpp