apiVersion: k8s.taf.io/v1alpha1
kind: TRelease
metadata:
  name: taf-taflog
  namespace: {{.Release.Namespace}}
  labels:
    taf.io/ReleaseSource: taf-taflog
    taf.io/ReleaseTag: "10000"
    taf.io/ServerApp: taf
    taf.io/ServerName: taflog
    taf.io/SubType: taf
    taf.io/Template: taf.default
spec:
  list:
    - image: {{.Values.global.registry.url}}/taf.taflog:10000
      imagePullSecret: taf-image-secret
      tag: "10000"
      serverType: taf_cpp
---

apiVersion: k8s.taf.io/v1alpha1
kind: TServer
metadata:
  name: taf-taflog
spec:
  app: taf
  server: taflog
  subType: taf
  taf:
    template: taf.cpp
    servants:
      - name: LogObj
        port: 10000
        thread: 5
  k8s:
    replicas: 1
    nodeSelector:
      nodeBind:
        values: [{{ .Values.nodeBind.log }}]
    env:
      - name: Namespace
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: PodName
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: PodIP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: ServerApp
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.labels['taf.io/ServerApp']
    mounts:
      - name: host-log-dir
        source:
          hostPath:
            path: /usr/local/app/taf/app_log
            type: DirectoryOrCreate
        mountPath: /usr/local/app/taf/app_log
        subPathExpr: $(Namespace).$(PodName)
    readinessGate: taf.io/active
  release:
    source: taf-taflog
    tag: '10000'
    image: {{.Values.global.registry.url}}/taf.taflog:10000
    imagePullSecret:  taf-image-secret
    serverType: taf_cpp