apiVersion: k8s.taf.io/v1alpha1
kind: TRelease
metadata:
  name: taf-tafquerystat
spec:
  list:
    - image: {{.Values.global.registry.url}}/taf.tafquerystat:10000
      imagePullSecret: taf-image-secret
      tag: "10000"
      serverType: taf_cpp
---

apiVersion: k8s.taf.io/v1alpha1
kind: TServer
metadata:
  name: taf-tafquerystat
  labels:
    taf.io/ReleaseSource: taf-tafquerystat
    taf.io/ReleaseTag: "10000"
    taf.io/ServerApp: taf
    taf.io/ServerName: tafquerystat
    taf.io/SubType: taf
    taf.io/Template: taf.default
spec:
  app: taf
  server: tafquerystat
  subType: taf
  taf:
    template: taf.cpp
    profile: |
      <taf>
        <statdb>
          <db1>
            dbhost={{ .Values.statDB.host }}
            dbport={{ .Values.statDB.port }}
            dbname={{ .Values.statDB.name }}
            dbuser={{ .Values.statDB.user }}
            dbpass={{ .Values.statDB.password }}
          </db1>
        </statdb>
      </taf>
    servants:
      - name: QueryObj
        port: 10000
  k8s:
    replicas: 1
    nodeSelector:
      abilityPool:
        values: [ ]
    env:
      - name: Namespace
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: PodName
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: PodIP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: ServerApp
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.labels['taf.io/ServerApp']
    mounts:
      - name: host-log-dir
        source:
          hostPath:
            path: /usr/local/app/taf/app_log
            type: DirectoryOrCreate
        mountPath: /usr/local/app/taf/app_log
        subPathExpr: $(Namespace).$(PodName)
    readinessGate: taf.io/active
  release:
    source: taf-tafquerystat
    tag: '10000'
    image: {{.Values.global.registry.url}}/taf.tafquerystat:10000
    imagePullSecret:  taf-image-secret