apiVersion: k8s.tars.io/v1alpha1
kind: TRelease
metadata:
  name: tars-tarsagent
  namespace: {{.Release.Namespace}}
spec:
  list:
    - image: {{.Values.global.registry.url}}/tars.tarsagent:10000
      imagePullSecret: tars-image-secret
      tag: "10000"
      serverType: tars_cpp
---

apiVersion: k8s.tars.io/v1alpha1
kind: TServer
metadata:
  name: tars-tarsagent
  namespace: {{.Release.Namespace}}
  labels:
    tars.io/ReleaseSource: tars-tarsagent
    tars.io/ReleaseTag: "10000"
    tars.io/ServerApp: tars
    tars.io/ServerName: tarsagent
    tars.io/SubType: normal
    tars.io/Template: tars.default
spec:
  app: tars
  server: tarsagent
  subType: normal
  normal:
    ports:
      - name: http
        port: 8000
  k8s:
    hostNetwork: true
    replicas: 1
    nodeSelector:
      daemonSet:
        values: [ ]
    env:
      - name: TARS_AGENT_PORT
        value: "8000"
      - name: Namespace
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: PodName
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: PodIP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    mounts:
      - name: host-log-dir
        source:
          hostPath:
            path: /usr/local/app/tars/app_log
            type: DirectoryOrCreate
        mountPath: /usr/local/app/tars/app_log
        subPathExpr: $(Namespace)
  release:
    source: tars-tarsagent
    tag: '10000'
    image: {{.Values.global.registry.url}}/tars.tarsagent:10000
    imagePullSecret: tars-image-secret
    serverType: tars_cpp