apiVersion: k8s.tars.io/v1alpha1
kind: TRelease
metadata:
  name: tars-tarslog
  namespace: {{.Release.Namespace}}
  labels:
    tars.io/ReleaseSource: tars-tarslog
    tars.io/ReleaseTag: "10000"
    tars.io/ServerApp: tars
    tars.io/ServerName: tarslog
    tars.io/SubType: tars
    tars.io/Template: tars.default
spec:
  list:
    - image: {{.Values.global.registry.url}}/tars.tarslog:10000
      imagePullSecret: tars-image-secret
      tag: "10000"
      serverType: tars_cpp
---

apiVersion: k8s.tars.io/v1alpha1
kind: TServer
metadata:
  name: tars-tarslog
spec:
  app: tars
  server: tarslog
  subType: tars
  tars:
    template: tars.cpp
    servants:
      - name: LogObj
        port: 10000
        thread: 5
  k8s:
    replicas: 1
    nodeSelector:
      nodeBind:
        values: [{{ .Values.nodeBind.log }}]
    env:
      - name: Namespace
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: PodName
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: PodIP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: ServerApp
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.labels['tars.io/ServerApp']
    mounts:
      - name: host-log-dir
        source:
          hostPath:
            path: /usr/local/app/tars/app_log
            type: DirectoryOrCreate
        mountPath: /usr/local/app/tars/app_log
        subPathExpr: $(Namespace).$(PodName)
    readinessGate: tars.io/active
  release:
    source: tars-tarslog
    tag: '10000'
    image: {{.Values.global.registry.url}}/tars.tarslog:10000
    imagePullSecret:  tars-image-secret
    serverType: tars_cpp