apiVersion: k8s.tars.io/v1alpha1
kind: TRelease
metadata:
  name: tars-tarsqueryproperty
spec:
  list:
    - image: {{.Values.global.registry.url}}/tars.tarsqueryproperty:10000
      imagePullSecret: tars-image-secret
      tag: "10000"
      serverType: tars_cpp
---

apiVersion: k8s.tars.io/v1alpha1
kind: TServer
metadata:
  name: tars-tarsqueryproperty
  namespace: {{.Release.Namespace}}
  labels:
    tars.io/ReleaseSource: tars-tarsqueryproperty
    tars.io/ReleaseTag: "10000"
    tars.io/ServerApp: tars
    tars.io/ServerName: tarsqueryproperty
    tars.io/SubType: tars
    tars.io/Template: tars.default
spec:
  app: tars
  server: tarsqueryproperty
  subType: tars
  tars:
    template: tars.cpp
    profile: |
      <tars>
        <propertydb>
          <db1>
            dbname= tars_property
            dbhost={{ .Values.propertyDB.host }}
            dbport={{ .Values.propertyDB.port }}
            dbname={{ .Values.propertyDB.name }}
            dbuser={{ .Values.propertyDB.user }}
            dbpass={{ .Values.propertyDB.password }}
          </db1>
        </propertydb>
      </tars>
    servants:
      - name: QueryObj
        port: 10000
  k8s:
    replicas: 1
    nodeSelector:
      abilityPool:
        values: [ ]
    env:
      - name: Namespace
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: PodName
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: PodIP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: ServerApp
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.labels['tars.io/ServerApp']
    mounts:
      - name: host-log-dir
        source:
          hostPath:
            path: /usr/local/app/tars/app_log
            type: DirectoryOrCreate
        mountPath: /usr/local/app/tars/app_log
        subPathExpr: $(Namespace).$(PodName)
    readinessGate: tars.io/active
  release:
    source: tars-tarsqueryproperty
    tag: '10000'
    image: {{.Values.global.registry.url}}/tars.tarsqueryproperty:10000
    imagePullSecret:  tars-image-secret