// Code generated by go-swagger; DO NOT EDIT.

package release

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
)

// SelectServicePoolURL generates an URL for the select service pool operation
type SelectServicePoolURL struct {
	Filter  *string
	Limiter *string
	Order   *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *SelectServicePoolURL) WithBasePath(bp string) *SelectServicePoolURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *SelectServicePoolURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *SelectServicePoolURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/releases"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/admin/v1alpha1/"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var filterQ string
	if o.Filter != nil {
		filterQ = *o.Filter
	}
	if filterQ != "" {
		qs.Set("Filter", filterQ)
	}

	var limiterQ string
	if o.Limiter != nil {
		limiterQ = *o.Limiter
	}
	if limiterQ != "" {
		qs.Set("Limiter", limiterQ)
	}

	var orderQ string
	if o.Order != nil {
		orderQ = *o.Order
	}
	if orderQ != "" {
		qs.Set("Order", orderQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *SelectServicePoolURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *SelectServicePoolURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *SelectServicePoolURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on SelectServicePoolURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on SelectServicePoolURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *SelectServicePoolURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
