apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tconfigs.k8s.tars.io
spec:
  conversion:
    strategy: None
  group: k8s.tars.io
  names:
    kind: TConfig
    listKind: TConfigList
    plural: tconfigs
    shortNames:
      - tc
    singular: tconfig
  scope: Namespaced
  versions:
    - name: v1beta1
      served: _V1BETA1_SERVED_
      storage: _V1BETA1_STORAGE_
      deprecated: true
      deprecationWarning: "k8s.tars.io/v1beta1 TConfig is deprecated; please migrate to k8s.tars.io/v1beta3 TConfig"
      schema:
        openAPIV3Schema:
          type: object
          properties:
            app:
              type: string
              pattern: ^[A-Za-z][0-9A-Za-z]*$
              maxLength: 63
            server:
              type: string
              pattern: ^([A-Za-z][0-9A-Za-z]*)?$
              maxLength: 63
              default: ""
            configName:
              type: string
              pattern: ^([0-9A-Za-z][-._0-9A-Za-z]*)?[0-9A-Za-z]$
              maxLength: 63
            configContent:
              type: string
              maxLength: 1560000
            podSeq:
              type: string
              pattern: ^(m|0|[1-9][0-9]?)$
              default: "m"
            updateTime:
              type: string
              format: date-time
            updatePerson:
              type: string
              maxLength: 100
            updateReason:
              type: string
              maxLength: 1600
            activated:
              type: boolean
              default: true
            version:
              type: string
              pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z]$
              maxLength: 63
          required: [ app, configName,configContent ]
      additionalPrinterColumns:
        - name: App
          type: string
          jsonPath: .app
        - name: Server
          type: string
          jsonPath: .server
        - name: PodSeq
          type: string
          jsonPath: .podSeq
        - name: ConfigName
          type: string
          jsonPath: .configName
        - name: Version
          type: string
          jsonPath: .version
        - name: Activated
          type: boolean
          jsonPath: .activated
    - name: v1beta2
      served: _V1BETA2_SERVED_
      storage: _V1BETA2_STORAGE_
      deprecated: true
      deprecationWarning: "k8s.tars.io/v1beta2 TConfig is deprecated; please migrate to k8s.tars.io/v1beta3 TConfig"
      schema:
        openAPIV3Schema:
          type: object
          properties:
            app:
              type: string
              pattern: ^[A-Za-z][0-9A-Za-z]*$
              maxLength: 63
            server:
              type: string
              pattern: ^([A-Za-z][0-9A-Za-z]*)?$
              maxLength: 63
              default: ""
            configName:
              type: string
              pattern: ^([0-9A-Za-z][-._0-9A-Za-z]*)?[0-9A-Za-z]$
              maxLength: 63
            configContent:
              type: string
              maxLength: 1560000
            podSeq:
              type: string
              pattern: ^(m|0|[1-9][0-9]?)$
              default: "m"
            updateTime:
              type: string
              format: date-time
            updatePerson:
              type: string
              maxLength: 100
            updateReason:
              type: string
              maxLength: 1600
            activated:
              type: boolean
              default: true
            version:
              type: string
              pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z]$
              maxLength: 63
          required: [ app, configName,configContent ]
      additionalPrinterColumns:
        - name: App
          type: string
          jsonPath: .app
        - name: Server
          type: string
          jsonPath: .server
        - name: PodSeq
          type: string
          jsonPath: .podSeq
        - name: ConfigName
          type: string
          jsonPath: .configName
        - name: Version
          type: string
          jsonPath: .version
        - name: Activated
          type: boolean
          jsonPath: .activated
    - name: v1beta3
      served: _V1BETA3_SERVED_
      storage: _V1BETA3_STORAGE_
      schema:
        openAPIV3Schema:
          type: object
          properties:
            app:
              type: string
              pattern: ^[A-Za-z][0-9A-Za-z]*$
              maxLength: 63
            server:
              type: string
              pattern: ^([A-Za-z][0-9A-Za-z]*)?$
              maxLength: 63
              default: ""
            configName:
              type: string
              pattern: ^([0-9A-Za-z][-._0-9A-Za-z]*)?[0-9A-Za-z]$
              maxLength: 63
            configContent:
              type: string
              maxLength: 1560000
            podSeq:
              type: string
              pattern: ^(m|0|[1-9][0-9]?)$
              default: "m"
            updateTime:
              type: string
              format: date-time
            updatePerson:
              type: string
              maxLength: 100
            updateReason:
              type: string
              maxLength: 1600
            activated:
              type: boolean
              default: true
            version:
              type: string
              pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z]$
              maxLength: 63
          required: [ app, configName,configContent ]
      additionalPrinterColumns:
        - name: App
          type: string
          jsonPath: .app
        - name: Server
          type: string
          jsonPath: .server
        - name: PodSeq
          type: string
          jsonPath: .podSeq
        - name: ConfigName
          type: string
          jsonPath: .configName
        - name: Version
          type: string
          jsonPath: .version
        - name: Activated
          type: boolean
          jsonPath: .activated
