apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: texitedrecords.k8s.tars.io
spec:
  conversion:
    strategy: None
  group: k8s.tars.io
  names:
    kind: TExitedRecord
    listKind: TExitedRecordList
    plural: texitedrecords
    singular: texitedrecord
  scope: Namespaced
  versions:
    - name: v1beta1
      served: _V1BETA1_SERVED_
      storage: _V1BETA1_STORAGE_
      deprecated: true
      deprecationWarning: "k8s.tars.io/v1beta1 TExitedRecord is deprecated; please migrate to k8s.tars.io/v1beta3 TExitedRecord"
      schema:
        openAPIV3Schema:
          type: object
          properties:
            app:
              type: string
            server:
              type: string
            pods:
              type: array
              items:
                type: object
                properties:
                  uid:
                    type: string
                  name:
                    type: string
                  id:
                    type: string
                  nodeIP:
                    type: string
                  podIP:
                    type: string
                  createTime:
                    type: string
                  deleteTime:
                    type: string
              maxItems: 150
          required: [ app,server,pods ]
    - name: v1beta2
      served: _V1BETA2_SERVED_
      storage: _V1BETA2_STORAGE_
      deprecated: true
      deprecationWarning: "k8s.tars.io/v1beta2 TExitedRecord is deprecated; please migrate to k8s.tars.io/v1beta3 TExitedRecord"
      schema:
        openAPIV3Schema:
          type: object
          properties:
            app:
              type: string
            server:
              type: string
            pods:
              type: array
              items:
                type: object
                properties:
                  uid:
                    type: string
                  name:
                    type: string
                  id:
                    type: string
                  nodeIP:
                    type: string
                  podIP:
                    type: string
                  createTime:
                    type: string
                  deleteTime:
                    type: string
              maxItems: 150
          required: [ app,server,pods ]
    - name: v1beta3
      served: _V1BETA3_SERVED_
      storage: _V1BETA3_STORAGE_
      schema:
        openAPIV3Schema:
          type: object
          properties:
            app:
              type: string
            server:
              type: string
            pods:
              type: array
              items:
                type: object
                properties:
                  uid:
                    type: string
                  name:
                    type: string
                  id:
                    type: string
                  nodeIP:
                    type: string
                  podIP:
                    type: string
                  createTime:
                    type: string
                  deleteTime:
                    type: string
              maxItems: 150
          required: [ app,server,pods ]
