apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tframeworkkey.k8s.tars.io
spec:
  conversion:
    strategy: None
  group: k8s.tars.io
  names:
    kind: TFrameworkKey
    listKind: TFrameworkKeyList
    plural: tframeworkkey
    singular: tframeworkkey
    shortNames: [ tfk ]
  scope: Namespaced
  versions:
    - name: v1beta2
      served: true
      storage: false
      deprecated: true
      deprecationWarning: "k8s.tars.io/v1beta2 TFrameworkKey is deprecated; please migrate to k8s.tars.io/v1beta3 TFrameworkKey"
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cuid:
                  type: string
                pri_key:
                  type: string
                autologin:
                  type: integer
    - name: v1beta3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cuid:
                  type: string
                pri_key:
                  type: string
                autologin:
                  type: integer
