apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: timages.k8s.tars.io
spec:
  conversion:
    strategy: None
  group: k8s.tars.io
  names:
    kind: TImage
    listKind: TImageList
    plural: timages
    singular: timage
    shortNames: [ ti ]
  scope: Namespaced
  versions:
    - name: v1beta1
      served: _V1BETA1_SERVED_
      storage: _V1BETA1_STORAGE_
      schema:
        openAPIV3Schema:
          type: object
          properties:
            imageType:
              type: string
              enum: [ base,server,node ]
            supportedType:
              type: array
              items:
                type: string
                enum: [ cpp,nodejs,nodejs-pkg,java-war,java-jar,go,php ]
              minItems: 1
            mark:
              type: string
              maxLength: 1600
            releases:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    pattern: ^([0-9A-Za-z][-_.0-9A-Za-z]*)?[0-9A-Za-z]$
                    maxLength: 63
                  image:
                    type: string
                    pattern: ^[\x2E-\x3A\x61-\x7A]*$
                    maxLength: 500
                  secret:
                    type: string
                    pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z]?(\.([0-9a-z][-0-9a-z]*)?[0-9a-z])*$
                    maxLength: 253
                  createPerson:
                    type: string
                    maxLength: 100
                  createTime:
                    type: string
                    format: date-time
                  mark:
                    type: string
                    maxLength: 1600
                required: [ id , image ]
              minItems: 0
              maxItems: 120
            build:
              type: object
              properties:
                last:
                  type: object
                  properties:
                    id:
                      type: string
                      pattern: ^([0-9A-Za-z][-_.0-9A-Za-z]*)?[0-9A-Za-z]$
                      maxLength: 63
                    baseImage:
                      type: string
                      maxLength: 500
                    baseImageSecret:
                      type: string
                      pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z]?(\.([0-9a-z][-0-9a-z]*)?[0-9a-z])*$
                      maxLength: 253
                    image:
                      type: string
                      pattern: ^[\x2D-\x3A\x61-\x7A]*$
                      maxLength: 500
                    secret:
                      type: string
                      pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z]?(\.([0-9a-z][-0-9a-z]*)?[0-9a-z])*$
                      maxLength: 253
                      default: ""
                    serverType:
                      type: string
                      enum: [ cpp,nodejs,nodejs-pkg,java-war,java-jar,go,php ]
                    createPerson:
                      type: string
                      maxLength: 800
                    createTime:
                      type: string
                      format: date-time
                    mark:
                      type: string
                      maxLength: 1600
                    phase:
                      type: string
                    message:
                      type: string
                      maxLength: 1600
                    handler:
                      type: string
                      maxLength: 253
                  required: [ id,baseImage,image ]
                running:
                  type: object
                  properties:
                    id:
                      type: string
                      pattern: ^([0-9A-Za-z][-_.0-9A-Za-z]*)?[0-9A-Za-z]$
                      maxLength: 63
                    baseImage:
                      type: string
                      maxLength: 500
                    baseImageSecret:
                      type: string
                      pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z]?(\.([0-9a-z][-0-9a-z]*)?[0-9a-z])*$
                      maxLength: 253
                    image:
                      type: string
                      pattern: ^[\x2D-\x3A\x61-\x7A]*$
                      maxLength: 500
                    secret:
                      type: string
                      pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z]?(\.([0-9a-z][-0-9a-z]*)?[0-9a-z])*$
                      maxLength: 253
                    serverType:
                      type: string
                      enum: [ cpp,nodejs,nodejs-pkg,java-war,java-jar,go,php ]
                    createPerson:
                      type: string
                      maxLength: 800
                    createTime:
                      type: string
                      format: date-time
                    mark:
                      type: string
                      maxLength: 1600
                    phase:
                      type: string
                    message:
                      type: string
                      maxLength: 1600
                    handler:
                      type: string
                      maxLength: 253
                  required: [ id,baseImage,image ]
    - name: v1beta2
      served: _V1BETA2_SERVED_
      storage: _V1BETA2_STORAGE_
      schema:
        openAPIV3Schema:
          type: object
          properties:
            imageType:
              type: string
              enum: [ base,server,node ]
            supportedType:
              type: array
              items:
                type: string
                enum: [ cpp,nodejs,nodejs-pkg,java-war,java-jar,go,php ]
              minItems: 1
            mark:
              type: string
              maxLength: 1600
            releases:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    pattern: ^([0-9A-Za-z][-_.0-9A-Za-z]*)?[0-9A-Za-z]$
                    maxLength: 63
                  image:
                    type: string
                    maxLength: 500
                  secret:
                    type: string
                    pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z]?(\.([0-9a-z][-0-9a-z]*)?[0-9a-z])*$
                    maxLength: 253
                  createPerson:
                    type: string
                    maxLength: 100
                  createTime:
                    type: string
                    format: date-time
                  mark:
                    type: string
                    maxLength: 1600
                required: [ id , image ]
              minItems: 0
              maxItems: 120
            build:
              type: object
              properties:
                last:
                  type: object
                  properties:
                    id:
                      type: string
                      pattern: ^([0-9A-Za-z][-_.0-9A-Za-z]*)?[0-9A-Za-z]$
                      maxLength: 63
                    baseImage:
                      type: string
                      maxLength: 500
                    baseImageSecret:
                      type: string
                      pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z]?(\.([0-9a-z][-0-9a-z]*)?[0-9a-z])*$
                      maxLength: 253
                    image:
                      type: string
                      pattern: ^[\x2D-\x3A\x61-\x7A]*$
                      maxLength: 500
                    secret:
                      type: string
                      pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z]?(\.([0-9a-z][-0-9a-z]*)?[0-9a-z])*$
                      maxLength: 253
                    serverType:
                      type: string
                      enum: [ cpp,nodejs,nodejs-pkg,java-war,java-jar,go,php ]
                    createPerson:
                      type: string
                      maxLength: 800
                    createTime:
                      type: string
                      format: date-time
                    mark:
                      type: string
                      maxLength: 1600
                    phase:
                      type: string
                    message:
                      type: string
                      maxLength: 1600
                    handler:
                      type: string
                      maxLength: 253
                  required: [ id,baseImage,image ]
                running:
                  type: object
                  properties:
                    id:
                      type: string
                      pattern: ^([0-9A-Za-z][-_.0-9A-Za-z]*)?[0-9A-Za-z]$
                      maxLength: 63
                    baseImage:
                      type: string
                      maxLength: 500
                    baseImageSecret:
                      type: string
                      pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z]?(\.([0-9a-z][-0-9a-z]*)?[0-9a-z])*$
                      maxLength: 253
                    image:
                      type: string
                      pattern: ^[\x2D-\x3A\x61-\x7A]*$
                      maxLength: 500
                    secret:
                      type: string
                      pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z]?(\.([0-9a-z][-0-9a-z]*)?[0-9a-z])*$
                      maxLength: 253
                    serverType:
                      type: string
                      enum: [ cpp,nodejs,nodejs-pkg,java-war,java-jar,go,php ]
                    createPerson:
                      type: string
                      maxLength: 800
                    createTime:
                      type: string
                      format: date-time
                    mark:
                      type: string
                      maxLength: 1600
                    phase:
                      type: string
                    message:
                      type: string
                      maxLength: 1600
                    handler:
                      type: string
                      maxLength: 253
                  required: [ id,baseImage,image ]
    - name: v1beta3
      served: _V1BETA3_SERVED_
      storage: _V1BETA3_STORAGE_
      schema:
        openAPIV3Schema:
          type: object
          properties:
            imageType:
              type: string
              enum: [ base,server,node ]
            supportedType:
              type: array
              items:
                type: string
                enum: [ cpp,nodejs,nodejs-pkg,java-war,java-jar,go,php ]
              minItems: 1
            mark:
              type: string
              maxLength: 1600
            releases:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    pattern: ^([0-9A-Za-z][-_.0-9A-Za-z]*)?[0-9A-Za-z]$
                    maxLength: 63
                  image:
                    type: string
                    maxLength: 500
                  secret:
                    type: string
                    pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z]?(\.([0-9a-z][-0-9a-z]*)?[0-9a-z])*$
                    maxLength: 253
                  createPerson:
                    type: string
                    maxLength: 100
                  createTime:
                    type: string
                    format: date-time
                  mark:
                    type: string
                    maxLength: 1600
                required: [ id , image ]
              minItems: 0
              maxItems: 120
            build:
              type: object
              properties:
                last:
                  type: object
                  properties:
                    id:
                      type: string
                      pattern: ^([0-9A-Za-z][-_.0-9A-Za-z]*)?[0-9A-Za-z]$
                      maxLength: 63
                    baseImage:
                      type: string
                      maxLength: 500
                    baseImageSecret:
                      type: string
                      pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z]?(\.([0-9a-z][-0-9a-z]*)?[0-9a-z])*$
                      maxLength: 253
                    image:
                      type: string
                      pattern: ^[\x2D-\x3A\x61-\x7A]*$
                      maxLength: 500
                    secret:
                      type: string
                      pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z]?(\.([0-9a-z][-0-9a-z]*)?[0-9a-z])*$
                      maxLength: 253
                    serverType:
                      type: string
                      enum: [ cpp,nodejs,nodejs-pkg,java-war,java-jar,go,php ]
                    createPerson:
                      type: string
                      maxLength: 800
                    createTime:
                      type: string
                      format: date-time
                    mark:
                      type: string
                      maxLength: 1600
                    phase:
                      type: string
                    message:
                      type: string
                      maxLength: 1600
                    handler:
                      type: string
                      maxLength: 253
                  required: [ id,baseImage,image ]
                running:
                  type: object
                  properties:
                    id:
                      type: string
                      pattern: ^([0-9A-Za-z][-_.0-9A-Za-z]*)?[0-9A-Za-z]$
                      maxLength: 63
                    baseImage:
                      type: string
                      maxLength: 500
                    baseImageSecret:
                      type: string
                      pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z]?(\.([0-9a-z][-0-9a-z]*)?[0-9a-z])*$
                      maxLength: 253
                    image:
                      type: string
                      pattern: ^[\x2D-\x3A\x61-\x7A]*$
                      maxLength: 500
                    secret:
                      type: string
                      pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z]?(\.([0-9a-z][-0-9a-z]*)?[0-9a-z])*$
                      maxLength: 253
                    serverType:
                      type: string
                      enum: [ cpp,nodejs,nodejs-pkg,java-war,java-jar,go,php ]
                    createPerson:
                      type: string
                      maxLength: 800
                    createTime:
                      type: string
                      format: date-time
                    mark:
                      type: string
                      maxLength: 1600
                    phase:
                      type: string
                    message:
                      type: string
                      maxLength: 1600
                    handler:
                      type: string
                      maxLength: 253
                  required: [ id,baseImage,image ]
