apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tplugins.k8s.tars.io
spec:
  conversion:
    strategy: None
  group: k8s.tars.io
  names:
    kind: TPlugin
    listKind: TPluginList
    plural: tplugins
    singular: tplugin
    shortNames:
      - tp
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: false
      deprecated: true
      deprecationWarning: "k8s.tars.io/v1beta1 TPlugin is deprecated; please migrate to k8s.tars.io/v1beta3 TPlugin"
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                name_en:
                  type: string
                obj:
                  type: string
                type:
                  type: integer
                path:
                  type: string
    - name: v1beta2
      served: true
      storage: false
      deprecated: true
      deprecationWarning: "k8s.tars.io/v1beta2 TPlugin is deprecated; please migrate to k8s.tars.io/v1beta3 TPlugin"
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                name_en:
                  type: string
                obj:
                  type: string
                type:
                  type: integer
                path:
                  type: string
                extern:
                  type: integer
    - name: v1beta3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                name_en:
                  type: string
                obj:
                  type: string
                type:
                  type: integer
                path:
                  type: string
                extern:
                  type: integer
