apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ttemplates.k8s.tars.io
spec:
  conversion:
    strategy: None
  group: k8s.tars.io
  names:
    kind: TTemplate
    listKind: TTemplateList
    plural: ttemplates
    shortNames: [ tt ]
    singular: ttemplate
  scope: Namespaced
  versions:
    - name: v1beta1
      served: _V1BETA1_SERVED_
      storage: _V1BETA1_STORAGE_
      deprecated: true
      deprecationWarning: "k8s.tars.io/v1beta1 TTemplate is deprecated; please migrate to k8s.tars.io/v1beta3 TTemplate"
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                content:
                  type: string
                  maxLength: 1560000
                parent:
                  type: string
                  pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z](\.([0-9a-z][-0-9a-z]*)?[0-9a-z])*$
                  maxLength: 253
              required: [ content,parent ]
    - name: v1beta2
      served: _V1BETA2_SERVED_
      storage: _V1BETA2_STORAGE_
      deprecated: true
      deprecationWarning: "k8s.tars.io/v1beta2 TTemplate is deprecated; please migrate to k8s.tars.io/v1beta3 TTemplate"
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                content:
                  type: string
                  maxLength: 1560000
                parent:
                  type: string
                  pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z](\.([0-9a-z][-0-9a-z]*)?[0-9a-z])*$
                  maxLength: 253
              required: [ content,parent ]
    - name: v1beta3
      served: _V1BETA3_SERVED_
      storage: _V1BETA3_STORAGE_
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                content:
                  type: string
                  maxLength: 1560000
                parent:
                  type: string
                  pattern: ^([0-9a-z][-0-9a-z]*)?[0-9a-z](\.([0-9a-z][-0-9a-z]*)?[0-9a-z])*$
                  maxLength: 253
              required: [ content,parent ]
      additionalPrinterColumns:
        - name: Parent
          type: string
          jsonPath: .spec.parent