name: build-base-compiler-release-3.0


on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build-compiler-release-3.0.yml"
      - "compiler/tools/*"
      - "compiler/tools/yaml-tools/*"
      - "compiler/tools/helm-template/*"
      - "compiler/tools/helm-lib/*"
      - "compiler/base-compiler.Dockerfile"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/build-compiler-release-3.0.yml"
      - "compiler/tools/*"
      - "compiler/tools/helm-template/*"
      - "compiler/tools/helm-lib/*"
      - "compiler/base-compiler.Dockerfile"
      
jobs:
  build:
    runs-on: ubuntu-20.04 
    steps:
      - name: env
        run: env
      # - uses: satackey/action-docker-layer-caching@v0.0.11
      #   continue-on-error: true
      - uses: actions/checkout@v1
      - name: login docker hub
        run: docker login -u ${{ secrets.name }} -p ${{ secrets.pass }}
      - name: Build docker
        run: cd compiler && docker build . -f base-compiler.Dockerfile -t tarscloud/base-compiler:v3.0 --build-arg BRANCH=release/3.0
      - name: push release/3.0 docker
        run: docker push tarscloud/base-compiler:v3.0

