name: build-base-compiler-cor


on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build-compiler-cor.yml"
      - "doc/tools"
      - "doc/base-compiler.Dockerfile"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/build-compiler-cor.yml"
      - "doc/tools"
      - "doc/base-compiler.Dockerfile"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: env
        run: env
      - uses: actions/checkout@v1
      - name: login docker hub
        run: docker login -u ${{ secrets.name }} -p ${{ secrets.pass }}
      - name: Build docker
        run: cd doc && docker build . -f base-compiler.Dockerfile -t tarscloud/base-compiler:cor --build-arg cor
      - name: push master docker
        run: docker push tarscloud/base-compiler:cor

