name: build-cpp-compiler-centos

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build-cpp-compiler-centos.yml"
      - "compiler/tools/**"
      - "compiler/cpp-compiler-centos.Dockerfile"
      - "submodule/TarsCpp/**"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/build-cpp-compiler-centos.yml"
      - "compiler/tools/**"
      - "compiler/cpp-compiler-centos.Dockerfile"
      - "submodule/TarsCpp/**"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: env
        run: env
      - uses: actions/checkout@v1
      - name: login docker hub
        run: docker login -u ${{ secrets.name }} -p ${{ secrets.pass }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:compiler"
          push: true
          tags: tarscloud/cpp-compiler-centos:latest
          file: cpp-compiler-centos.Dockerfile
          build-args: |
            BRANCH=master
            TARS_SSL=OFF
          platforms: linux/amd64,linux/arm64

  build-ssl:
    runs-on: ubuntu-20.04
    steps:
      - name: env
        run: env
      - uses: actions/checkout@v1
      - name: login docker hub
        run: docker login -u ${{ secrets.name }} -p ${{ secrets.pass }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:compiler"
          push: true
          tags: tarscloud/cpp-compiler-centos-ssl:latest
          file: cpp-compiler-centos.Dockerfile
          build-args: |
            BRANCH=master
            TARS_SSL=ON
          platforms: linux/amd64,linux/arm64
