name: build-base-compiler


on:
  push:
    branches:
      - master
    paths:
      - "doc/tools"
      - "doc/base-compiler.Dockerfile"
  pull_request:
    branches:
      - master
    paths:
      - "doc/tools"
      - "doc/base-compiler.Dockerfile"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: env
        run: env
      - uses: actions/checkout@v1
      - name: Build docker
        run: cd doc && docker build . -f base-compiler.Dockerfile -t tarscloud/base-compiler && docker push tarscloud/base-compiler

