name: build
on:
  push:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "charts/**"
      - ".github/workflows/build-compiler-*.yml"
      - ".github/workflows/build-deploy*.yml"
  pull_request:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "charts/**"
      - ".github/workflows/build-compiler-*.yml"
      - ".github/workflows/build-deploy*.yml"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04]
        cli: [docker]
    runs-on: ${{matrix.platform}}
    timeout-minutes: 90
    env:
      ENV_DOCKER: ${{matrix.cli}}
      WITHOUT_DEPENDS_CHECK: 1
      DOCKER_RUN_WITHOUT_IT: 1
      LocalRegistryName: local-registry
      LocalRegistryPort: 5000
      LocalRegistryUrl: localhost:5000/build

      REGISTRY_URL: localhost:5000/build
      BUILD_VERSION: 1.3.0-ci
      CHART_VERSION: 1.3.0-ci

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build Compiler Images
        run: make compiler

      - name: Create Local Registry
        run: ./util/create-local-registry.sh ${{env.LocalRegistryName}} ${{env.LocalRegistryPort}}

      - name: Build And Push Base Images To Registry
        run: make base

      - name: Build And Push Controller Images To Registry
        run: make controller

      - name: Build And Push Framework Images To Registry
        run: make framework

      - name: Build TarsController Chart And TarsFramework Chart
        run: make chart
