name: build-base-compiler-master-stretch

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build-compiler-master-stretch.yml"
      - "compiler/tools/*"
      - "compiler/tools/yaml-tools/*"
      - "compiler/tools/helm-template/*"
      - "compiler/tools/helm-lib/*"
      - "compiler/base-compiler-stretch.Dockerfile"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/build-compiler-master-stretch.yml"
      - "compiler/tools/*"
      - "compiler/tools/helm-template/*"
      - "compiler/tools/helm-lib/*"
      - "compiler/base-compiler-stretch.Dockerfile"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: env
        run: env
      - uses: actions/checkout@v1
      - name: login docker hub
        run: docker login -u ${{ secrets.name }} -p ${{ secrets.pass }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:compiler"
          push: true
          tags: tarscloud/base-compiler-stretch:latest
          file: base-compiler-stretch.Dockerfile
          build-args: BRANCH=master
          platforms: linux/amd64,linux/arm64
      # - name: Build docker
      #   run: cd compiler && docker buildx build . -f base-compiler-stretch.Dockerfile -t tarscloud/base-compiler-stretch:latest --build-arg BRANCH=master --platform=linux/amd64 --push
