name: build-docker-tag

on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: env
        run: env && echo ${{ github.ref }} 
      - uses: actions/checkout@v1
      - name: Pull code
        run: env && ./prepare.sh    
      - name: Build binary
        run: ./buildBinary.sh
      - name: Build docker
        run: ./buildHelm.sh tarscloud ${{ secrets.name }} ${{ secrets.pass }} ${{ github.ref }} 
