name: build-base-compiler

on:
  push:
    tags:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: env
        run: env
      - uses: actions/checkout@v1
      - name: Build docker
        run: cd doc && docker build . -f base-compiler.Dockerfile -t tarscloud/base-compiler && docker push tarscloud/base-compiler

