name: build-base-compiler-master

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build-compiler-master.yml"
      - "compiler/tools/*"
      - "compiler/tools/yaml-tools/*"
      - "compiler/tools/helm-template/*"
      - "compiler/tools/helm-lib/*"
      - "compiler/base-compiler.Dockerfile"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/build-compiler-master.yml"
      - "compiler/tools/*"
      - "compiler/tools/helm-template/*"
      - "compiler/tools/helm-lib/*"
      - "compiler/base-compiler.Dockerfile"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: env
        run: env
      - uses: actions/checkout@v1
      - name: login docker hub
        run: docker login -u ${{ secrets.name }} -p ${{ secrets.pass }}
      - name: prepare docker
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled 
          docker buildx create --use --name builder
          docker buildx inspect builder --bootstrap
          docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
      - name: Build docker
        run: cd compiler && docker buildx build . -f base-compiler.Dockerfile -t tarscloud/base-compiler:latest --build-arg BRANCH=master --platform=linux/amd64,linux/arm64  -o type=docker --push
