name: build-deploy-tag

on:
  push:
    tags:
      - v*
    paths:
      - ".github/workflows/build-deploy.yml"
      - "compiler/tools/**"
      - "compiler/base-deploy.Dockerfile"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: env
        run: env
      - uses: actions/checkout@v1
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: login docker hub
        run: docker login -u ${{ secrets.name }} -p ${{ secrets.pass }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:compiler"
          push: true
          tags: tarscloud/base-deploy:${{ steps.get_version.outputs.VERSION }}
          file: base-deploy.Dockerfile
          platforms: linux/amd64,linux/arm64
