name: build-base-compiler-master-tag

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04 
    steps:
      - name: env
        run: env
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v1
      - name: login docker hub
        run: docker login -u ${{ secrets.name }} -p ${{ secrets.pass }}
      - name: Build docker
        run: cd doc && docker build . -f base-compiler.Dockerfile -t tarscloud/base-compiler:${{ steps.get_version.outputs.VERSION }} --build-arg BRANCH=${{ steps.get_version.outputs.VERSION }}
      - name: push ${{ steps.get_version.outputs.VERSION }} docker
        run: docker push tarscloud/base-compiler:${{ steps.get_version.outputs.VERSION }}

