name: build-docker-tag

on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: env
        run: env
      - uses: actions/checkout@v1
      - name: Pull code
        run: env && ./prepare.sh    
      - name: Build binary
        run: ./buildBinary.sh
      - name: Build docker
        run: ./buildHelm.sh tarscloud ${{ secrets.name }} ${{ secrets.pass }} v1.0.0 
