name: build-base-compiler-master-ssl-tag

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: env
        run: env
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v1
      - name: login docker hub
        run: docker login -u ${{ secrets.name }} -p ${{ secrets.pass }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "compiler"
          push: true
          tags: tarscloud/base-compiler-ssl:${{ steps.get_version.outputs.VERSION }}
          file: base-compiler-ssl.Dockerfile
          build-args: BRANCH=master
          platforms: linux/amd64,linux/arm64
      # - name: Build ssl docker
      #   run: cd compiler && docker buildx build . -f base-compiler-ssl.Dockerfile -t tarscloud/base-compiler-ssl:${{ steps.get_version.outputs.VERSION }} --build-arg BRANCH=master --platform=linux/amd64,linux/arm64 --push
