name: charts

on:
  push:
    tags:
      - 'v[1-9][0-9]?.[1-9][0-9]?.0'
      - 'v[1-9][0-9]?.[1-9][0-9]?.0-[a-z]'
      - 'v[1-9][0-9]?.[1-9][0-9]?.0-[a-z][a-z0-9]+'
      - 'v[1-9][0-9]?.[1-9][0-9]?.[1-9][0-9]?'
      - 'v[1-9][0-9]?.[1-9][0-9]?.[1-9][0-9]?-[a-z]'
      - 'v[1-9][0-9]?.[1-9][0-9]?.[1-9][0-9]?-[a-z][a-z0-9]+'
jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      DOCKER_RUN_WITHOUT_IT: 1
      REGISTRY_URL: docker.io/tarscloud
      REGISTRY_USER: ${{ secrets.name }}
      REGISTRY_PASSWORD: ${{ secrets.pass }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Get Chart Version
        id: chart-version
        run:
          echo ::set-output name=CHART_VERSION::$(echo ${GITHUB_REF/refs\/tags\//} | cut -b2-)

      - name: Get Build Version
        id: build-version
        run:
          echo ::set-output name=BUILD_VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build TarsController Chart
        run: make chart.controller CHART_VERSION=${{ steps.chart-version.outputs.CHART_VERSION }} BUILD_VERSION=${{ steps.build-version.outputs.BUILD_VERSION }}

      - name: Build TarsFramework Chart
        run: make chart.framework CHART_VERSION=${{ steps.chart-version.outputs.CHART_VERSION }} BUILD_VERSION=${{ steps.build-version.outputs.BUILD_VERSION }}

      - name: Helm Index
        run: helm repo index charts --url https://tarscloud.github.io/K8SFramework/charts

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: index chars with version ${{ steps.chart-version.outputs.CHART_VERSION }}
          branch: master
          file_pattern: charts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
