name: e2e
on:
  push:
    branches: [ master ]
    paths-ignore: [ docs/**,charts/** ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ docs/**,charts/** ]

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-20.04 ]
        storage_crd_version: [ v1beta1,v1beta2,v1beta3 ]
    runs-on: ${{matrix.platform}}
    timeout-minutes: 90
    env:
      DOCKER_RUN_WITHOUT_IT: 1
      LocalRegistryName: local-registry
      LocalRegistryPort: 5000
      KindClusterName: e2e

      REGISTRY_URL: localhost:5000/build
      BUILD_VERSION: 1.3.0-e2e
      CHART_VERSION: 1.3.0-e2e
      CRD_STORAGE_VERSION: ${{matrix.storage_crd_version}}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build Compiler Images
        run: make compiler

      - name: Create Local Registry
        run: ./util/create-local-registry.sh ${{env.LocalRegistryName}} ${{env.LocalRegistryPort}}

      - name: Build And Push Controller Images To Registry
        run: make controller

      - name: Build TarsController Chart
        run: make chart.controller

      - name: Create Kind With Local Registry
        run: ./util/create-kind-with-local-registry.sh ${{env.KindClusterName}} ${{env.LocalRegistryName}} ${{env.LocalRegistryPort}}

      - name: Install Controller Chart
        run: make install.controller CHART=charts/tarscontroller-${{env.CHART_VERSION}}.tgz

      - name: Wait Controller Pods Running
        run: kubectl wait --for=condition=Ready nodes --all --timeout=180s

      - name: Run Controller Test
        run: make test.controller
