name: k8s-framework-nightly-build

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: '0 04 * * *'
jobs:

  build:

    runs-on: ubuntu-20.04 

    steps:
    - name: env
      run: env
    - uses: actions/checkout@v1
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Pull code
      run: ./prepare.sh    
    - name: Build binary
      run: ./buildBinary.sh
    - name: Build docker
      run: |
        ./buildHelm.sh tarscloud ${{ secrets.name }} ${{ secrets.pass }} v1.0.0-nightly 
        ./buildHelm.sh tarscloud ${{ secrets.name }} ${{ secrets.pass }} latest 
